{
  "name": "SemanticModel",
  "compatibilityLevel": 1500,
  "model": {
    "culture": "en-US",
    "discourageImplicitMeasures": true,
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/192 168 1 28;ARVA_BI",
        "description": "اتصال به دیتاورهوس جدید که برای اتصال به سیستم جدید طراحی شده است",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "192.168.1.28",
            "database": "ARVA_BI"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "kind": "SQL",
          "path": "192.168.1.28;ARVA_BI",
          "Username": "sa",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "BI DIM_DATE",
        "description": "جدول تقویم",
        "columns": [
          {
            "name": "Miladi",
            "dataType": "dateTime",
            "description": "تاریخ میلادی",
            "sourceColumn": "Miladi"
          },
          {
            "name": "Jalali_1",
            "dataType": "string",
            "description": "تاریخ شمسی",
            "sourceColumn": "Jalali_1"
          },
          {
            "name": "jyear",
            "dataType": "int64",
            "description": "سال شمسی",
            "sourceColumn": "jyear",
            "formatString": "0"
          },
          {
            "name": "jmonthN",
            "dataType": "int64",
            "description": "شماره ماه شمسی",
            "sourceColumn": "jmonthN",
            "formatString": "0"
          },
          {
            "name": "jmonthT",
            "dataType": "string",
            "description": "نام مه شمسی",
            "sourceColumn": "jmonthT",
            "sortByColumn": "jmonthN"
          },
          {
            "name": "jnime",
            "dataType": "string",
            "description": "نام نیمه سال شمسی",
            "sourceColumn": "jnime"
          },
          {
            "name": "JquarterN",
            "dataType": "int64",
            "description": "شماره فصل شمسی",
            "sourceColumn": "JquarterN"
          },
          {
            "name": "JQuarterT",
            "dataType": "string",
            "description": "نام فصل شمسی",
            "sourceColumn": "JQuarterT",
            "sortByColumn": "JquarterN"
          },
          {
            "name": "JWeekDay",
            "dataType": "string",
            "description": "روز هفته شمسی",
            "sourceColumn": "JWeekDay"
          },
          {
            "name": "JWeekNum",
            "dataType": "int64",
            "description": "شماره روز هفته",
            "sourceColumn": "JWeekNum"
          },
          {
            "name": "date_Counter",
            "dataType": "int64",
            "description": "شماره یونیک روز که برای محاسبات اختلاف بین دو تاریخ از آن استفاده می شود",
            "sourceColumn": "date_Counter"
          },
          {
            "name": "Is Holiday",
            "dataType": "string",
            "description": [
              "جدول مشخص کننده روزهای تعطیل",
              "این جدول دارای 3 وضعیت است اولی 1 برای روز های غیر تعطیل و دومی 0 برای روزهای تعطیل و 0.5 برای روزهای پنجشنبه"
            ],
            "sourceColumn": "Is Holiday"
          },
          {
            "name": "day",
            "dataType": "string",
            "description": "روز",
            "sourceColumn": "day",
            "formatString": "0"
          },
          {
            "name": "end_month",
            "dataType": "int64",
            "sourceColumn": "end_month",
            "formatString": "0"
          },
          {
            "name": "Day_number_year",
            "dataType": "int64",
            "description": "مشخص کننده این است که هر تاریخی چندیمن روز از سال است",
            "sourceColumn": "Day_number_year"
          },
          {
            "name": "holiday",
            "dataType": "double",
            "description": "جدول مشخص کننده تعداد روز کاری به این صورت که اگر آن روز تعطیل باشد مقدار صفر را دارد و اگر روز پنجشنبه باشد مقدار 0.5 را دارا و اگر آن روز غیر تعطیل باشد مقدار 1 را دارد.",
            "sourceColumn": "holiday"
          },
          {
            "type": "calculated",
            "name": "02_ selectMonth",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": [
              "   if ('BI DIM_DATE'[Jalali_1] = 'BI DIM_DATE'[01_Today] , 3 , 'BI DIM_DATE'[end_month])",
              "",
              "",
              "",
              "----  مشخص کردن ابتدا و انتها و تاریخ روز  ( برای محاسبه موجودی روز انبار مورد استفاده قرار میگیرد"
            ],
            "formatString": "0"
          },
          {
            "name": "myear",
            "dataType": "int64",
            "sourceColumn": "myear"
          },
          {
            "type": "calculated",
            "name": "003_IsToday",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "   IF('BI DIM_DATE'[Miladi] = TODAY() , \"Today\", 'BI DIM_DATE'[Miladi] & \"\")",
              "",
              "",
              "--جدا کردن  تاریخ روز از سایر تاریخ "
            ]
          },
          {
            "name": "unic_code",
            "dataType": "string",
            "sourceColumn": "unic_code"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    BI_DIM_DATE = Source{[Schema=\"BI\",Item=\"DIM_DATE\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(BI_DIM_DATE,{\"Jalali_2\", \"Miladi_1\", \"mmonthN\", \"mmonthT\", \"mnime\", \"MquarterN\", \"MWeekDay\", \"MWeekNum\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Removed Columns\",\"ي\",\"ی\",Replacer.ReplaceText,{\"jmonthT\", \"jnime\", \"JQuarterT\", \"JWeekDay\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Replaced Value\",{{\"jyear\", Int64.Type}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each [jyear] = 1392 or [jyear] = 1393 or [jyear] = 1394 or [jyear] = 1395 or [jyear] = 1396 or [jyear] = 1397 or [jyear] = 1398 or [jyear] = 1399 or [jyear] = 1400 or [jyear] = 1401 or [jyear] = 1402 or [jyear] = 1403 or [jyear] = 1384 or [jyear] = 1330),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Miladi\", type date}})",
                "in",
                "    #\"Changed Type1\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "01_Today",
            "description": "تاریخ روز ",
            "expression": " LOOKUPVALUE('BI DIM_DATE'[Jalali_1],'BI DIM_DATE'[Miladi],TODAY())"
          },
          {
            "name": "02_flagBinary",
            "description": "محاسبه روز کاری",
            "expression": [
              "   sum( 'BI DIM_DATE'[holiday])",
              " -- محاسبه روز کاری"
            ],
            "formatString": "#,#"
          },
          {
            "name": "Sum of Miladi",
            "expression": "SUM([Miladi])"
          }
        ]
      },
      {
        "name": "BI Dim_Geographic",
        "description": "جدول مشخصات شهر ها و استان ها",
        "columns": [
          {
            "name": "StateCode",
            "dataType": "int64",
            "sourceColumn": "StateCode",
            "formatString": "0"
          },
          {
            "name": "StateName",
            "dataType": "string",
            "sourceColumn": "StateName"
          },
          {
            "name": "ID",
            "dataType": "int64",
            "sourceColumn": "ID"
          },
          {
            "name": "AreaCode",
            "dataType": "string",
            "sourceColumn": "AreaCode"
          },
          {
            "name": "AreaName",
            "dataType": "string",
            "sourceColumn": "AreaName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    BI_DIM_Geographic = Source{[Schema=\"BI\",Item=\"Dim_Geographic\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(BI_DIM_Geographic,\"ي\",\"ی\",Replacer.ReplaceText,{\"StateName\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"ي\",\"ی\",Replacer.ReplaceText,{\"AreaName\", \"StateName\"})",
                "in",
                "    #\"Replaced Value1\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "USERNAME",
            "expression": " USERNAME()"
          },
          {
            "name": "USERPRINCIPALNAME",
            "expression": "USERPRINCIPALNAME()"
          }
        ]
      },
      {
        "name": "VN Dim_Stock",
        "description": "جدول مشخصات انبارها",
        "columns": [
          {
            "name": "StockDC_ID",
            "dataType": "int64",
            "description": "شماره یونیک انبار id",
            "sourceColumn": "StockDC_ID"
          },
          {
            "name": "StockDCName",
            "dataType": "string",
            "description": "نام انبار",
            "sourceColumn": "StockDCName"
          },
          {
            "name": "StockGroup",
            "dataType": "string",
            "sourceColumn": "StockGroup"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    VN_Dim_Stock = Source{[Schema=\"VN\",Item=\"Dim_Stock\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(VN_Dim_Stock,\"ي\",\"ی\",Replacer.ReplaceText,{\"StockDCName\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"ي\",\"ی\",Replacer.ReplaceText,{\"StockGroup\"})",
                "in",
                "    #\"Replaced Value1\""
              ]
            }
          }
        ]
      },
      {
        "name": "VN Dim_Goods",
        "description": "جدول مشخصات کالاها",
        "columns": [
          {
            "name": "Goods_ID",
            "dataType": "int64",
            "description": "id محصول",
            "sourceColumn": "Goods_ID"
          },
          {
            "name": "GoodsCode",
            "dataType": "string",
            "description": "کد تعریف شده کالا",
            "sourceColumn": "GoodsCode"
          },
          {
            "name": "GoodsName",
            "dataType": "string",
            "description": "نام کالا",
            "sourceColumn": "GoodsName"
          },
          {
            "name": "GoodsGroupName",
            "dataType": "string",
            "description": "نام دسته بندی فرعی کالا",
            "sourceColumn": "GoodsGroupName"
          },
          {
            "name": "GoodsGroupName_Parent",
            "dataType": "string",
            "description": "نام دسه بندی اصلی کالا",
            "sourceColumn": "GoodsGroupName_Parent"
          },
          {
            "name": "ManufacturerName",
            "dataType": "string",
            "description": "نام تولید کننده",
            "sourceColumn": "ManufacturerName"
          },
          {
            "type": "calculated",
            "name": "GoodsCode 1",
            "dataType": "string",
            "description": "کد کالا",
            "expression": " RIGHT('VN Dim_Goods'[GoodsCode],5)"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    VN_Dim_Goods = Source{[Schema=\"VN\",Item=\"Dim_Goods\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(VN_Dim_Goods,\"ي\",\"ی\",Replacer.ReplaceText,{\"GoodsName\", \"GoodsGroupName\", \"GoodsGroupName_Parent\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"ي\",\"ی\",Replacer.ReplaceText,{\"ManufacturerName\"})",
                "in",
                "    #\"Replaced Value1\""
              ]
            }
          }
        ]
      },
      {
        "name": "VN Fact_int_Vocher_Itm_Qty",
        "description": "جدول موجودی هر کالا در هر انبار براساس داده های سندهای رسید انبار",
        "columns": [
          {
            "name": "tblVocherItm_ID",
            "dataType": "int64",
            "description": "id سند های انبار",
            "sourceColumn": "tblVocherItm_ID"
          },
          {
            "name": "GoodsRef",
            "dataType": "int64",
            "description": "id کالا",
            "sourceColumn": "GoodsRef"
          },
          {
            "name": "TotalQty",
            "dataType": "double",
            "description": "تعداد ورودی یا خروجی",
            "sourceColumn": "TotalQty",
            "formatString": "#,#"
          },
          {
            "name": "StockDCRef",
            "dataType": "int64",
            "description": "شماره انبار",
            "sourceColumn": "StockDCRef"
          },
          {
            "name": "VocherNo",
            "dataType": "int64",
            "description": "شماره سند رسید انبار",
            "sourceColumn": "VocherNo"
          },
          {
            "name": "VocherDate",
            "dataType": "string",
            "description": "تاریخ سند رسید انبار",
            "sourceColumn": "VocherDate"
          },
          {
            "name": "VocherTypeName",
            "dataType": "string",
            "description": "نوع سند رسید انبار",
            "sourceColumn": "VocherTypeName"
          },
          {
            "name": "AccYear",
            "dataType": "int64",
            "sourceColumn": "AccYear"
          },
          {
            "name": "SalePrice",
            "dataType": "double",
            "sourceColumn": "SalePrice"
          },
          {
            "type": "calculated",
            "name": "08_Rial changes",
            "dataType": "double",
            "isDataTypeInferred": true,
            "description": "ریال کالا* تعداد (تغییرات ) کالا ",
            "expression": [
              " 'VN Fact_int_Vocher_Itm_Qty'[TotalQty] * 'VN Fact_int_Vocher_Itm_Qty'[SalePrice]",
              "----- تغییرات  ریالی در هر ماه ",
              " -- TotalQty تغییرات در هر ماه   را  نمایش میدهد ",
              ""
            ],
            "formatString": "#,#"
          },
          {
            "name": "unic_code_int",
            "dataType": "string",
            "sourceColumn": "unic_code_int"
          },
          {
            "type": "calculated",
            "name": "09_Sleep in the warehouse",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": [
              "   ",
              "            if('VN Fact_int_Vocher_Itm_Qty'[VocherTypeName] = \"رسید انبار\" ||",
              "                  'VN Fact_int_Vocher_Itm_Qty'[VocherTypeName] = \"انبار به انبار بدهكار\"",
              "                  || 'VN Fact_int_Vocher_Itm_Qty'[VocherTypeName] = \"افتتاحیه انبار\"",
              "             && 'VN Fact_int_Vocher_Itm_Qty_history'[06_ CurrentInventory]<> 0,",
              "                 TODAY()-MAX('VN Fact_int_Vocher_Itm_Qty'[MiladiVocherDate]))"
            ]
          },
          {
            "type": "calculated",
            "name": "MiladiVocherDate",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": [
              "  LOOKUPVALUE('BI DIM_DATE'[Miladi] ,'BI DIM_DATE'[Jalali_1], 'VN Fact_int_Vocher_Itm_Qty'[VocherDate])",
              "",
              "-- تاریخ میلادی سند انبار برای محاسبه خواب انبار"
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    VN_Fact_int_Vocher_Itm_Qty = Source{[Schema=\"VN\",Item=\"Fact_int_Vocher_Itm_Qty\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(VN_Fact_int_Vocher_Itm_Qty,\"ي\",\"ی\",Replacer.ReplaceText,{\"VocherTypeName\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "03_NumberSold",
            "description": "تعداد فروش رفته ",
            "expression": [
              "",
              "   (  ( CALCULATE(sum('VN Fact_int_Vocher_Itm_Qty'[TotalQty]),",
              "                         FILTER('VN Fact_int_Vocher_Itm_Qty', 'VN Fact_int_Vocher_Itm_Qty'[VocherTypeName] = ",
              "\"خروجی\"",
              "",
              "",
              "      )))*-1)",
              "-",
              " (  ( CALCULATE(sum('VN Fact_int_Vocher_Itm_Qty'[TotalQty]),",
              "                         FILTER('VN Fact_int_Vocher_Itm_Qty', 'VN Fact_int_Vocher_Itm_Qty'[VocherTypeName] = ",
              "\"برگشت حواله\"",
              "))))"
            ],
            "formatString": "#,#"
          },
          {
            "name": "06_RialSold",
            "description": "فروش ریالی ",
            "expression": [
              "",
              "   (  ( CALCULATE(sum('VN Fact_int_Vocher_Itm_Qty'[08_Rial changes]),",
              "                         FILTER('VN Fact_int_Vocher_Itm_Qty', 'VN Fact_int_Vocher_Itm_Qty'[VocherTypeName] = ",
              "\"خروجی\"",
              "",
              "",
              "      ))))*-1",
              "-",
              "  ( CALCULATE(sum('VN Fact_int_Vocher_Itm_Qty'[08_Rial changes]),",
              "                         FILTER('VN Fact_int_Vocher_Itm_Qty', 'VN Fact_int_Vocher_Itm_Qty'[VocherTypeName] = ",
              "\"برگشت حواله\"",
              ")))"
            ],
            "formatString": "#,#"
          },
          {
            "name": "07_YTD(ExiteOrder)",
            "description": " تعداد فروش سال تا روز ( انبار ",
            "expression": [
              " ",
              "",
              "",
              "       var y = LOOKUPVALUE('BI DIM_DATE'[jyear],'BI DIM_DATE'[Miladi],TODAY())",
              "       var D = LOOKUPVALUE('BI DIM_DATE'[Day_number_year] , 'BI DIM_DATE'[Miladi] , TODAY())",
              "",
              " return",
              " ",
              "(  ( CALCULATE(sum('VN Fact_int_Vocher_Itm_Qty'[TotalQty]),",
              "                       'VN Fact_int_Vocher_Itm_Qty'[VocherTypeName] = ",
              "\"خروجی\",",
              "",
              "",
              "    'BI DIM_DATE'[Day_number_year]<=D ,'BI DIM_DATE'[jyear]=y) *-1))",
              "-",
              "",
              "",
              " (  ( CALCULATE(sum('VN Fact_int_Vocher_Itm_Qty'[TotalQty]),",
              "                        'VN Fact_int_Vocher_Itm_Qty'[VocherTypeName] = ",
              "\"برگشت حواله\",",
              "'BI DIM_DATE'[Day_number_year]<=D,'BI DIM_DATE'[jyear]=y )))",
              "",
              "",
              "---- تعداد فروش سال تا روز ( انبار "
            ],
            "formatString": "#,#"
          },
          {
            "name": "08_MTD(ExiteOrder)",
            "description": " ریا ل فروش سال تا روز ( انبار ",
            "expression": [
              " ",
              "",
              "",
              "       var y = LOOKUPVALUE('BI DIM_DATE'[jyear],'BI DIM_DATE'[Miladi],TODAY())",
              "       var M = LOOKUPVALUE('BI DIM_DATE'[jmonthN] , 'BI DIM_DATE'[Miladi] , TODAY())",
              "",
              " return",
              " ",
              "   (  ( CALCULATE(sum('VN Fact_int_Vocher_Itm_Qty'[08_Rial changes]),",
              "                       'VN Fact_int_Vocher_Itm_Qty'[VocherTypeName] = ",
              "\"خروجی\",  'BI DIM_DATE'[jyear] =y , 'BI DIM_DATE'[Miladi]=M",
              "",
              "",
              "      )))*-1",
              "-",
              "  ( CALCULATE(sum('VN Fact_int_Vocher_Itm_Qty'[08_Rial changes]),",
              "                       'VN Fact_int_Vocher_Itm_Qty'[VocherTypeName] = ",
              "\"برگشت حواله\", 'BI DIM_DATE'[jyear]= y , 'BI DIM_DATE'[jmonthN]=m",
              "))",
              "",
              "",
              "---- ریا ل فروش ماه تا روز ( انبار ",
              "",
              ""
            ],
            "formatString": "#,#"
          },
          {
            "name": "010_Entered the warehouse",
            "description": "وارده های هر روز  در هر انبار ",
            "expression": [
              "  ",
              "          sumx(SUMMARIZE('VN Fact_int_Vocher_Itm_Qty', 'VN Dim_Goods'[GoodsCode], ",
              "                        'VN Dim_Goods'[GoodsGroupName] , 'VN Fact_int_Vocher_Itm_Qty'[VocherTypeName],'VN Dim_Stock'[StockDCName],",
              "   \"max\" , MAX('VN Fact_int_Vocher_Itm_Qty'[VocherDate]),",
              "                         \"sum\" , sum('VN Fact_int_Vocher_Itm_Qty'[TotalQty])),[sum])",
              "",
              "",
              "--- وارده های هر روز  در هر انبار "
            ]
          }
        ]
      },
      {
        "name": "BI last_refresh_time_knime",
        "description": "جدول نشان دهنده آخرین تاریخ و زمان رفرش",
        "columns": [
          {
            "name": "Time",
            "dataType": "string",
            "description": "زمان آخرین رفرش گزارشات",
            "sourceColumn": "Time"
          },
          {
            "name": "Date",
            "dataType": "string",
            "description": "تاریخ آخرین رفرش گزارشات",
            "sourceColumn": "Date"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    BI_last_refresh_time_knime = Source{[Schema=\"BI\",Item=\"last_refresh_time_knime\"]}[Data]",
                "in",
                "    BI_last_refresh_time_knime"
              ]
            }
          }
        ]
      },
      {
        "name": "VN Fact_int_Vocher_Itm_Qty_history",
        "description": "جدول سوابق روزانه موجودی هر کالا در هر انبار براساس داده های سندهای رسید انبار",
        "columns": [
          {
            "name": "StockDCRef",
            "dataType": "int64",
            "description": "کد انبار",
            "sourceColumn": "StockDCRef"
          },
          {
            "name": "GoodsRef",
            "dataType": "int64",
            "description": "id کالا",
            "sourceColumn": "GoodsRef"
          },
          {
            "name": "Sum(TotalQty)",
            "dataType": "double",
            "description": "تعداد موجودی انبار در هر روز در هر انبار",
            "sourceColumn": "Sum(TotalQty)",
            "formatString": "#,#"
          },
          {
            "name": "VocherDate",
            "dataType": "string",
            "description": "تاریخ",
            "sourceColumn": "VocherDate"
          },
          {
            "name": "SalePrice",
            "dataType": "double",
            "description": "قیمت هر روز یک کالا در بک انبار",
            "sourceColumn": "SalePrice",
            "formatString": "#,#"
          },
          {
            "name": "unic_code_int",
            "dataType": "string",
            "sourceColumn": "unic_code_int"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    VN_Fact_int_Vocher_Itm_Qty_history = Source{[Schema=\"VN\",Item=\"Fact_int_Vocher_Itm_Qty_history\"]}[Data]",
                "in",
                "    VN_Fact_int_Vocher_Itm_Qty_history"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "01_product_in_stock_in_last_day",
            "description": "موجودی پایان دوره",
            "expression": [
              " ",
              "     CALCULATE(SUM('VN Fact_int_Vocher_Itm_Qty_history'[Sum(TotalQty)]) , FILTER('BI DIM_DATE','BI DIM_DATE'[end_month] =1)",
              ")"
            ],
            "formatString": "#,#"
          },
          {
            "name": "02_ product_in_stock_in_frist_day",
            "description": "موجودی ابتدای دوره",
            "expression": [
              "",
              "     CALCULATE(SUM('VN Fact_int_Vocher_Itm_Qty_history'[Sum(TotalQty)]) , FILTER('BI DIM_DATE','BI DIM_DATE'[end_month] =2)",
              ")"
            ],
            "formatString": "#,#"
          },
          {
            "name": "04_ average invetory",
            "description": "میانگین موجودی انبار ( ابتدا و انتهای دوره )",
            "expression": [
              "",
              "                 ( 'VN Fact_int_Vocher_Itm_Qty_history'[01_product_in_stock_in_last_day] +",
              "                           'VN Fact_int_Vocher_Itm_Qty_history'[02_ product_in_stock_in_frist_day] )/2"
            ],
            "formatString": "#,#"
          },
          {
            "name": "05_real ITR",
            "description": "محاسبه ITR ",
            "expression": [
              "  if (MAX('VN Dim_Stock'[StockDC_ID]) <> 2, ",
              "    DIVIDE('VN Fact_int_Vocher_Itm_Qty'[03_NumberSold],'VN Fact_int_Vocher_Itm_Qty_history'[04_ average invetory]),",
              "            DIVIDE(CALCULATE(sum('VN Fact_int_Vocher_Itm_Qty'[TotalQty]),FILTER('VN Fact_int_Vocher_Itm_Qty', 'VN Fact_int_Vocher_Itm_Qty'[VocherTypeName] =",
              "\"انبار به انبار بستانكار\"))",
              " , [04_ average invetory]))",
              "",
              "",
              "",
              ""
            ],
            "formatString": "#,#"
          },
          {
            "name": "06_ CurrentInventory",
            "description": "موجودی لحظه ای انبار",
            "expression": [
              "  ",
              "",
              "         --   var mm = SELECTEDVALUE('BI DIM_DATE'[jmonthN])",
              "          --  var MToday= CONVERT(MONTH(TODAY()),INTEGER)",
              "           ",
              " --   return",
              "",
              "    -- if(mm = MToday , CALCULATE(SUM('VN Fact_int_Vocher_Itm_Qty_history'[Sum(TotalQty)]) , ",
              "                              --     'BI DIM_DATE'[Miladi]=TODAY()) , ",
              "                      CALCULATE(sum('VN Fact_int_Vocher_Itm_Qty_history'[Sum(TotalQty)]) , ",
              "                                  'BI DIM_DATE'[end_month] =1)",
              "",
              "",
              "",
              "",
              "",
              " -----   موجودی لحظه ای انبار   "
            ],
            "formatString": "#,#"
          },
          {
            "name": "07_ Current Inventory(Rial)",
            "description": "موجودی ریالی لحظه ای ",
            "expression": [
              "",
              "       --   var mm = SELECTEDVALUE('BI DIM_DATE'[jmonthN])",
              "       --     var MToday= CONVERT(MONTH(TODAY()),INTEGER)",
              "           ",
              "  --  return",
              "",
              "--   (  if(mm = MToday , CALCULATE(SUM('VN Fact_int_Vocher_Itm_Qty_history'[Sum(TotalQty)]) , ",
              "                               --    'BI DIM_DATE'[Miladi]=TODAY()) , ",
              "               --       CALCULATE(sum('VN Fact_int_Vocher_Itm_Qty_history'[Sum(TotalQty)]) , ",
              "                             --     'BI DIM_DATE'[end_month] =1)))",
              "       --       * ",
              "        --      CALCULATE(SUM('VN Fact_int_Vocher_Itm_Qty_history'[SalePrice]) ,  'BI DIM_DATE'[end_month] = 1)",
              "",
              "----  موجودی ریالی لحظه ای  برای  ماه های قبل از ماه جاری ",
              "",
              "",
              "",
              "CALCULATE(",
              "        sumx('VN Fact_int_Vocher_Itm_Qty_history','VN Fact_int_Vocher_Itm_Qty_history'[Sum(TotalQty)] ",
              "                                                                * ",
              "                                                                   'VN Fact_int_Vocher_Itm_Qty_history'[SalePrice]),",
              "                                                                                       'BI DIM_DATE'[end_month]= 1 )            ",
              "               ",
              "",
              "--CALCULATE(AVERAGE('VN Fact_int_Vocher_Itm_Qty_history'[SalePrice]) ,  'BI DIM_DATE'[end_month] = 1)",
              "----موجودی ریالی لحظه ای"
            ],
            "formatString": "#,#"
          },
          {
            "name": "08 _Lastyear'sprice",
            "description": "قیمت سال گذشته",
            "expression": [
              "    ",
              "                         var y = MAX('BI DIM_DATE'[jyear])-1",
              "          return ",
              "                  CALCULATE(MAX('VN Fact_int_Vocher_Itm_Qty_history'[SalePrice]) ,",
              "                                  'BI DIM_DATE'[jyear] = y)",
              "",
              "",
              "---- قیمت سال گذشته"
            ],
            "formatString": "#,#"
          },
          {
            "name": "09_ProductGrowthRate",
            "description": "نرخ تغغیرات (رشد) قیمت کالا",
            "expression": [
              "",
              " ",
              "if( 'VN Fact_int_Vocher_Itm_Qty_history'[08 _Lastyear'sprice] >0 && MAX('VN Fact_int_Vocher_Itm_Qty_history'[SalePrice]) <> BLANK(),",
              "  DIVIDE(MAX('VN Fact_int_Vocher_Itm_Qty_history'[SalePrice]) - 'VN Fact_int_Vocher_Itm_Qty_history'[08 _Lastyear'sprice] ,",
              "                              'VN Fact_int_Vocher_Itm_Qty_history'[08 _Lastyear'sprice]))",
              "",
              "       --   ( MAX('VN Fact_int_Vocher_Itm_Qty_history'[SalePrice]) -'VN Fact_int_Vocher_Itm_Qty_history'[08 _Lastyear'sprice])",
              "                                            --  /'VN Fact_int_Vocher_Itm_Qty_history'[08 _Lastyear'sprice]",
              "",
              "",
              "",
              "------نرخ تغغیرات (رشد) قیمت کالا",
              "                                                "
            ],
            "formatString": "0.00 %;0.00- %;0.00 %"
          },
          {
            "name": "010_CurrentInventory(currentMonth)",
            "expression": [
              "  ",
              "",
              "              var y = LOOKUPVALUE('BI DIM_DATE'[jyear], 'BI DIM_DATE'[Miladi], TODAY())",
              "              var m = LOOKUPVALUE('BI DIM_DATE'[jmonthN] , 'BI DIM_DATE'[Miladi], TODAY())",
              "  ",
              "               return",
              "",
              "",
              "          CALCULATE( sum('VN Fact_int_Vocher_Itm_Qty_history'[Sum(TotalQty)]) ,",
              "                                 'BI DIM_DATE'[jyear]=y , 'BI DIM_DATE'[jmonthN]=m ,  'BI DIM_DATE'[end_month]=1)",
              "                                              ",
              "",
              "",
              "---- محاسبه موجودی روز انبار فقط برای ماه جاری  )"
            ]
          },
          {
            "name": "011_ Current Inventory(Rial_CurrentMonth)",
            "description": "موجودی ریالی لحظه ای ماه جاری ",
            "expression": [
              "",
              "       var yy = SELECTEDVALUE( 'BI DIM_DATE'[jyear])",
              "       ",
              "        var mm = SELECTEDVALUE ('BI DIM_DATE'[jmonthN] )",
              "           ",
              " return",
              "",
              "",
              "",
              "",
              "CALCULATE(",
              "        sumx('VN Fact_int_Vocher_Itm_Qty_history','VN Fact_int_Vocher_Itm_Qty_history'[Sum(TotalQty)] ",
              "                                        * ",
              "                                            'VN Fact_int_Vocher_Itm_Qty_history'[SalePrice]),",
              "                                                          'BI DIM_DATE'[jyear]=yy, 'BI DIM_DATE'[jmonthN]=mm,'BI DIM_DATE'[end_month]=1)            ",
              "               ",
              "",
              "----  موجودی ریالی لحظه ای ماه جاری "
            ],
            "formatString": "#,#"
          },
          {
            "name": "012_ Last Inventory(Rial_LastMonth)",
            "description": "ریال ماه گذشته انبار",
            "expression": [
              "",
              "           var yy = SELECTEDVALUE ('BI DIM_DATE'[jyear] )",
              "       ",
              "           var mm = SELECTEDVALUE ('BI DIM_DATE'[jmonthN] )",
              "           var pm = if(mm=1 , 12, mm-1)",
              "           var py = IF(pm=12 , yy-1, yy)",
              "",
              " return",
              "",
              "",
              "CALCULATE(",
              "        sumx('VN Fact_int_Vocher_Itm_Qty_history','VN Fact_int_Vocher_Itm_Qty_history'[Sum(TotalQty)] ",
              "                                        * ",
              "                                            'VN Fact_int_Vocher_Itm_Qty_history'[SalePrice]),",
              "                                                          'BI DIM_DATE'[jyear]=py, 'BI DIM_DATE'[jmonthN]=pm,'BI DIM_DATE'[end_month]=1) ",
              "",
              "",
              "-- ریال ماه گذشته انبار"
            ],
            "formatString": "#,#"
          },
          {
            "name": "013_ Inventory growth Rate (Rial)",
            "description": "نرخ رشد ریالی انبار ",
            "expression": [
              "",
              "                             if( 'VN Fact_int_Vocher_Itm_Qty_history'[012_ Last Inventory(Rial_LastMonth)]>0 && 'VN Fact_int_Vocher_Itm_Qty_history'[07_ Current Inventory(Rial)]<> BLANK(),",
              "                                 ('VN Fact_int_Vocher_Itm_Qty_history'[07_ Current Inventory(Rial)]- 'VN Fact_int_Vocher_Itm_Qty_history'[012_ Last Inventory(Rial_LastMonth)])",
              "                                                    /'VN Fact_int_Vocher_Itm_Qty_history'[012_ Last Inventory(Rial_LastMonth)])",
              "",
              "-- نرخ رشد ریالی انیار )"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "014_ First Inventory(Rial_FirstMonth)",
            "description": "ریال ابتدای سال انبار برای محاسبه نرخ رشد ریالی نسبت به روز ",
            "expression": [
              "",
              "        ",
              "",
              "        var yy = SELECTEDVALUE ('BI DIM_DATE'[jyear] )",
              "   return",
              "     CALCULATE(",
              "             sumx('VN Fact_int_Vocher_Itm_Qty_history','VN Fact_int_Vocher_Itm_Qty_history'[Sum(TotalQty)] ",
              "                                      * ",
              "                              'VN Fact_int_Vocher_Itm_Qty_history'[SalePrice]),",
              "                                                    'BI DIM_DATE'[jyear]=yy-1, 'BI DIM_DATE'[jmonthN]=12,'BI DIM_DATE'[end_month]=1)",
              "",
              "-- ریال ابتدای سال انبار برای محاسبه نرخ رشد ریالی نسبت به روز ",
              "",
              "",
              "",
              "",
              "",
              "",
              ""
            ],
            "formatString": "#,#"
          },
          {
            "name": "015_Growth Rate(beginning to now)",
            "description": "نرخ رشد ریالی انبار نسبت به ابتدای سال ",
            "expression": [
              "",
              "",
              "",
              " if ( 'VN Fact_int_Vocher_Itm_Qty_history'[014_ First Inventory(Rial_FirstMonth)] <> 0",
              "                 && ",
              "              'VN Fact_int_Vocher_Itm_Qty_history'[011_ Current Inventory(Rial_CurrentMonth)] <> BLANK(),",
              "     ( 'VN Fact_int_Vocher_Itm_Qty_history'[011_ Current Inventory(Rial_CurrentMonth)]- 'VN Fact_int_Vocher_Itm_Qty_history'[014_ First Inventory(Rial_FirstMonth)])",
              "                         /",
              "'VN Fact_int_Vocher_Itm_Qty_history'[014_ First Inventory(Rial_FirstMonth)])",
              "",
              "-- نرخ رشد ریالی انبار نسبت به ابتدای سال ))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "016_ DollarPriceStorage",
            "description": "قیمت دلاری موجودی انبار ",
            "expression": [
              "      ",
              "",
              "    CALCULATE(",
              "        sumx('VN Fact_int_Vocher_Itm_Qty_history','VN Fact_int_Vocher_Itm_Qty_history'[Sum(TotalQty)] ",
              "                   *   'VN Fact_int_Vocher_Itm_Qty_history'[SalePrice] ),",
              "                                                  'BI DIM_DATE'[end_month]= 1 )  /",
              "                                     'BI dollar_price'[001_ maxClose Price_Dollar]",
              "                                                              ",
              "",
              "--- قیمت دلاری موجودی انبار "
            ],
            "formatString": "#,#"
          },
          {
            "name": "017_PreviousDollarPrice(Storage)",
            "description": "دلار انبار  ماه گذشته ",
            "expression": [
              "",
              "",
              "",
              "     --- محاسبه ریال انبار ماه گذشته               ",
              "           var yy = SELECTEDVALUE ('BI DIM_DATE'[jyear] )",
              "           var mm = SELECTEDVALUE ('BI DIM_DATE'[jmonthN] )",
              "           var pm = if(mm=1 , 12, mm-1)",
              "           var py = IF(pm=12 , yy-1, yy)",
              "",
              " return",
              "",
              "",
              "CALCULATE(",
              "        sumx('VN Fact_int_Vocher_Itm_Qty_history','VN Fact_int_Vocher_Itm_Qty_history'[Sum(TotalQty)] ",
              "                                        * ",
              "                                            'VN Fact_int_Vocher_Itm_Qty_history'[SalePrice]),",
              "                                                          'BI DIM_DATE'[jyear]=py, 'BI DIM_DATE'[jmonthN]=pm,'BI DIM_DATE'[end_month]=1) ",
              "                                                             /",
              "                                                     ",
              "",
              " ----- محاسبه دلار انبار ماه گذشته                  ",
              "           var yy = SELECTEDVALUE ('BI DIM_DATE'[jyear] )",
              "           var mm = SELECTEDVALUE ('BI DIM_DATE'[jmonthN] )",
              "           var pm = if(mm=1 , 12, mm-1)",
              "           var py = IF(pm=12 , yy-1, yy)",
              "",
              " return",
              "",
              "",
              "CALCULATE(",
              "        ",
              "                  'BI dollar_price'[001_ maxClose Price_Dollar] ,",
              "                                                          'BI DIM_DATE'[jyear]=py, 'BI DIM_DATE'[jmonthN]=pm) ",
              "",
              "",
              "",
              "",
              "",
              "",
              "-- دلار انبار  ماه گذشته ",
              ""
            ],
            "formatString": "#,#"
          },
          {
            "name": "018_ Inventory growth Rate (Dollar)",
            "description": " نرخ رشد دلاری انبار ",
            "expression": [
              "",
              "                  if( 'VN Fact_int_Vocher_Itm_Qty_history'[017_PreviousDollarPrice(Storage)]>0 && 'VN Fact_int_Vocher_Itm_Qty_history'[016_ DollarPriceStorage]> BLANK(),",
              "                                 ('VN Fact_int_Vocher_Itm_Qty_history'[016_ DollarPriceStorage]- 'VN Fact_int_Vocher_Itm_Qty_history'[017_PreviousDollarPrice(Storage)])",
              "                                                    /'VN Fact_int_Vocher_Itm_Qty_history'[017_PreviousDollarPrice(Storage)]",
              "-- نرخ رشد دلاری انبار ",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "019_ First Inventory(Dollar_FirstMonth)",
            "description": "دلار ابتدای سال انبار",
            "expression": [
              "",
              "        ",
              "",
              "        var yy = SELECTEDVALUE ('BI DIM_DATE'[jyear] )",
              "   return",
              "    CALCULATE(",
              "             sumx('VN Fact_int_Vocher_Itm_Qty_history','VN Fact_int_Vocher_Itm_Qty_history'[Sum(TotalQty)] ",
              "                                      * ",
              "                              'VN Fact_int_Vocher_Itm_Qty_history'[SalePrice]),",
              "                                                    'BI DIM_DATE'[jyear]=yy-1, 'BI DIM_DATE'[jmonthN]=12,'BI DIM_DATE'[end_month]=1)",
              "                                     /  ",
              "",
              " var yy = SELECTEDVALUE ('BI DIM_DATE'[jyear] )",
              "          ",
              "          ",
              " return",
              "",
              "CALCULATE(",
              "        ",
              "                  'BI dollar_price'[001_ maxClose Price_Dollar] ,",
              "                                                          'BI DIM_DATE'[jyear]=yy-1, 'BI DIM_DATE'[jmonthN]=12) ",
              "",
              "-- دلار ابتدای سال انبار برای محاسبه نرخ رشد ریالی نسبت به روز "
            ],
            "formatString": "#,#"
          },
          {
            "name": "020_Growth Rate Dollar(beginning to now)",
            "description": "نرخ رشد دلاری نسبت به ابتدای سال ",
            "expression": [
              "",
              "",
              "",
              " if ( 'VN Fact_int_Vocher_Itm_Qty_history'[019_ First Inventory(Dollar_FirstMonth)]<> 0",
              "                 && ",
              "              'VN Fact_int_Vocher_Itm_Qty_history'[016_ DollarPriceStorage] <> BLANK(),",
              "     ( 'VN Fact_int_Vocher_Itm_Qty_history'[016_ DollarPriceStorage]- 'VN Fact_int_Vocher_Itm_Qty_history'[019_ First Inventory(Dollar_FirstMonth)])",
              "                         /",
              "'VN Fact_int_Vocher_Itm_Qty_history'[019_ First Inventory(Dollar_FirstMonth)])",
              "",
              "--نرخ رشد دلاری نسبت به ابتدای سال ",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "020_PrevouseDollar",
            "description": "دلار ماه گذشته ",
            "expression": [
              "",
              "                      var yy = SELECTEDVALUE ('BI DIM_DATE'[jyear] )",
              "           var mm = SELECTEDVALUE ('BI DIM_DATE'[jmonthN] )",
              "           var pm = if(mm=1 , 12, mm-1)",
              "           var py = IF(pm=12 , yy-1, yy)",
              "",
              " return",
              "",
              "",
              "CALCULATE(",
              "        ",
              "                  'BI dollar_price'[001_ maxClose Price_Dollar] ,",
              "                                                          'BI DIM_DATE'[jyear]=py, 'BI DIM_DATE'[jmonthN]=pm) ",
              "",
              "-- دلار ماه گذشته "
            ],
            "formatString": "#,#"
          }
        ]
      },
      {
        "name": "VN Fact_Order",
        "description": "جدول درخواست فروش",
        "columns": [
          {
            "name": "tblOrderHdr_ID",
            "dataType": "int64",
            "sourceColumn": "tblOrderHdr_ID"
          },
          {
            "name": "OrderNo",
            "dataType": "int64",
            "description": "شماره درخواست ",
            "sourceColumn": "OrderNo"
          },
          {
            "name": "OrderDate",
            "dataType": "string",
            "sourceColumn": "OrderDate"
          },
          {
            "name": "CancelFlag",
            "dataType": "int64",
            "sourceColumn": "CancelFlag"
          },
          {
            "name": "OrderType",
            "dataType": "int64",
            "sourceColumn": "OrderType"
          },
          {
            "name": "StockDcRef",
            "dataType": "int64",
            "sourceColumn": "StockDcRef"
          },
          {
            "name": "CustRef",
            "dataType": "int64",
            "sourceColumn": "CustRef"
          },
          {
            "name": "DealerRef",
            "dataType": "int64",
            "sourceColumn": "DealerRef"
          },
          {
            "name": "SumOrderQty",
            "dataType": "double",
            "sourceColumn": "SumOrderQty"
          },
          {
            "name": "ConfirmDate",
            "dataType": "string",
            "sourceColumn": "ConfirmDate"
          },
          {
            "name": "UserRef",
            "dataType": "int64",
            "sourceColumn": "UserRef"
          },
          {
            "name": "ShipDate",
            "dataType": "string",
            "sourceColumn": "ShipDate"
          },
          {
            "name": "SupervisorRef",
            "dataType": "int64",
            "sourceColumn": "SupervisorRef"
          },
          {
            "name": "GoodsRef",
            "dataType": "int64",
            "sourceColumn": "GoodsRef"
          },
          {
            "name": "OrderQty",
            "dataType": "int64",
            "description": "#,#",
            "sourceColumn": "OrderQty"
          },
          {
            "name": "IsDeleted",
            "dataType": "int64",
            "sourceColumn": "IsDeleted"
          },
          {
            "name": "Order_date_Counter",
            "dataType": "int64",
            "sourceColumn": "Order_date_Counter"
          },
          {
            "name": "Confirm_date_Counter",
            "dataType": "int64",
            "sourceColumn": "Confirm_date_Counter"
          },
          {
            "name": "amount",
            "dataType": "int64",
            "description": "ریال فروش ",
            "sourceColumn": "amount",
            "formatString": "#,#"
          },
          {
            "name": "SaleNo",
            "dataType": "int64",
            "sourceColumn": "SaleNo"
          },
          {
            "name": "unic_code",
            "dataType": "string",
            "sourceColumn": "unic_code"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    VN_Fact_Order = Source{[Schema=\"VN\",Item=\"Fact_Order\"]}[Data]",
                "in",
                "    VN_Fact_Order"
              ]
            }
          }
        ]
      },
      {
        "name": "VN Dim_Cust",
        "description": "جدول مشتریان",
        "columns": [
          {
            "name": "tblCust_ID",
            "dataType": "int64",
            "sourceColumn": "tblCust_ID"
          },
          {
            "name": "CustCode",
            "dataType": "string",
            "sourceColumn": "CustCode"
          },
          {
            "name": "FirstName",
            "dataType": "string",
            "sourceColumn": "FirstName"
          },
          {
            "name": "LastName",
            "dataType": "string",
            "sourceColumn": "LastName"
          },
          {
            "name": "RealName",
            "dataType": "string",
            "sourceColumn": "RealName"
          },
          {
            "name": "Status",
            "dataType": "int64",
            "sourceColumn": "Status"
          },
          {
            "name": "Latitude",
            "dataType": "double",
            "sourceColumn": "Latitude"
          },
          {
            "name": "Longitude",
            "dataType": "double",
            "sourceColumn": "Longitude"
          },
          {
            "name": "CustActName",
            "dataType": "string",
            "sourceColumn": "CustActName"
          },
          {
            "name": "CustCtgrName",
            "dataType": "string",
            "sourceColumn": "CustCtgrName"
          },
          {
            "name": "SalePathName",
            "dataType": "string",
            "sourceColumn": "SalePathName"
          },
          {
            "name": "AreaRef",
            "dataType": "int64",
            "sourceColumn": "AreaRef"
          },
          {
            "name": "Address",
            "dataType": "string",
            "sourceColumn": "Address"
          },
          {
            "name": "Phone",
            "dataType": "string",
            "sourceColumn": "Phone"
          },
          {
            "name": "Mobile",
            "dataType": "string",
            "sourceColumn": "Mobile"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    VN_Dim_Cust = Source{[Schema=\"VN\",Item=\"Dim_Cust\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(VN_Dim_Cust,\"ي\",\"ی\",Replacer.ReplaceText,{\"FirstName\", \"LastName\", \"RealName\", \"CustActName\", \"CustCtgrName\", \"SalePathName\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"ي\",\"ی\",Replacer.ReplaceText,{\"Address\"})",
                "in",
                "    #\"Replaced Value1\""
              ]
            }
          }
        ]
      },
      {
        "name": "VN Fact_Sale",
        "description": "جدول فروش",
        "columns": [
          {
            "name": "SaleHdr_ID",
            "dataType": "int64",
            "sourceColumn": "SaleHdr_ID"
          },
          {
            "name": "OrderRef",
            "dataType": "int64",
            "sourceColumn": "OrderRef"
          },
          {
            "name": "TotalAmount",
            "dataType": "double",
            "sourceColumn": "TotalAmount"
          },
          {
            "name": "CustRef",
            "dataType": "int64",
            "sourceColumn": "CustRef"
          },
          {
            "name": "DealerRef",
            "dataType": "int64",
            "description": "کد ویزیتور ",
            "sourceColumn": "DealerRef"
          },
          {
            "name": "OrderType",
            "dataType": "string",
            "sourceColumn": "OrderType"
          },
          {
            "name": "DisType",
            "dataType": "string",
            "sourceColumn": "DisType"
          },
          {
            "name": "SaleVocherNo",
            "dataType": "int64",
            "description": "شماره حواله",
            "sourceColumn": "SaleVocherNo"
          },
          {
            "name": "OtherDiscount",
            "dataType": "double",
            "sourceColumn": "OtherDiscount"
          },
          {
            "name": "OtherAddition",
            "dataType": "double",
            "sourceColumn": "OtherAddition"
          },
          {
            "name": "GoodsRef",
            "dataType": "int64",
            "sourceColumn": "GoodsRef"
          },
          {
            "name": "UnitCapasity",
            "dataType": "double",
            "sourceColumn": "UnitCapasity"
          },
          {
            "name": "UnitQty",
            "dataType": "double",
            "sourceColumn": "UnitQty"
          },
          {
            "name": "TotalQty",
            "dataType": "double",
            "sourceColumn": "TotalQty"
          },
          {
            "name": "AmountNut",
            "dataType": "double",
            "sourceColumn": "AmountNut"
          },
          {
            "name": "Discount",
            "dataType": "double",
            "sourceColumn": "Discount"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "sourceColumn": "Amount"
          },
          {
            "name": "CPriceRef",
            "dataType": "int64",
            "sourceColumn": "CPriceRef"
          },
          {
            "name": "IsDeleted",
            "dataType": "int64",
            "sourceColumn": "IsDeleted"
          },
          {
            "name": "MainQty",
            "dataType": "double",
            "sourceColumn": "MainQty"
          },
          {
            "name": "Dis1 (item)",
            "dataType": "double",
            "sourceColumn": "Dis1 (item)"
          },
          {
            "name": "Dis2 (item)",
            "dataType": "double",
            "sourceColumn": "Dis2 (item)"
          },
          {
            "name": "Dis3 (item)",
            "dataType": "double",
            "sourceColumn": "Dis3 (item)"
          },
          {
            "name": "ExitRef",
            "dataType": "int64",
            "sourceColumn": "ExitRef"
          },
          {
            "name": "SaleDate",
            "dataType": "string",
            "description": "تاریخ فاکتور",
            "sourceColumn": "SaleDate"
          },
          {
            "name": "DraftDate",
            "dataType": "string",
            "description": "تاریخ حواله",
            "sourceColumn": "DraftDate"
          },
          {
            "name": "SupervisorRef",
            "dataType": "int64",
            "sourceColumn": "SupervisorRef"
          },
          {
            "name": "Item_ID",
            "dataType": "int64",
            "sourceColumn": "Item_ID"
          },
          {
            "name": "year",
            "dataType": "string",
            "sourceColumn": "year"
          },
          {
            "name": "SaleNo",
            "dataType": "string",
            "sourceColumn": "SaleNo"
          },
          {
            "name": "PaymentUsance",
            "dataType": "string",
            "sourceColumn": "PaymentUsance"
          },
          {
            "name": "Sale_date_Counter",
            "dataType": "int64",
            "sourceColumn": "Sale_date_Counter"
          },
          {
            "name": "Draft_date_Counter",
            "dataType": "int64",
            "sourceColumn": "Draft_date_Counter"
          },
          {
            "name": "type",
            "dataType": "string",
            "sourceColumn": "type"
          },
          {
            "name": "ExitRef_status",
            "dataType": "string",
            "sourceColumn": "ExitRef_status"
          },
          {
            "type": "calculated",
            "name": "033_MiladiSalesDate",
            "dataType": "string",
            "isDataTypeInferred": true,
            "description": "تبدیل تاریخ فاکتور به میلادی",
            "expression": [
              "",
              "      FORMAT( LOOKUPVALUE('BI DIM_DATE'[Miladi], 'BI DIM_DATE'[Jalali_1], 'VN Fact_Sale'[SaleDate]) , \"yyyy/mm/dd\")",
              "",
              "--  تبدیل تاریخ فاکتور به میلادی برای محاسبه تفاضل دو تاریخ )"
            ]
          },
          {
            "type": "calculated",
            "name": "034_MiladiDraftDate",
            "dataType": "string",
            "isDataTypeInferred": true,
            "description": "تبدیل تاریخ حواله به میلادی ",
            "expression": [
              "",
              "                  FORMAT( LOOKUPVALUE('BI DIM_DATE'[Miladi], 'BI DIM_DATE'[Jalali_1], 'VN Fact_Sale'[DraftDate]) , \"yyyy/mm/dd\")",
              "",
              "",
              "-- تبدیل تاریخ حواله به میلادی "
            ]
          },
          {
            "type": "calculated",
            "name": "035_ DateDiff (draft and sale)",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "description": "تفاضل بین تاریخ حواله و تاریخ فاکتور ",
            "expression": [
              " ",
              "                    DATEDIFF( 'VN Fact_Sale'[034_MiladiDraftDate],'VN Fact_Sale'[033_MiladiSalesDate],DAY)",
              "",
              "--تفاضل بین تاریخ حواله و تاریخ فاکتور )"
            ]
          },
          {
            "name": "unic_code",
            "dataType": "string",
            "sourceColumn": "unic_code"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    VN_Fact_Sale = Source{[Schema=\"VN\",Item=\"Fact_Sale\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(VN_Fact_Sale,\"ي\",\"ی\",Replacer.ReplaceText,{\"OrderType\", \"DisType\", \"PaymentUsance\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"ي\",\"ی\",Replacer.ReplaceText,{\"type\", \"ExitRef_status\"})",
                "in",
                "    #\"Replaced Value1\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "01_AmountNut",
            "description": "فروش خالص ( با محدودیت باطل نشده)",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'VN Fact_Sale'[Amountnut] ),",
              "",
              "    FILTER('VN Fact_Sale','VN Fact_Sale'[IsDeleted] <>1",
              "))"
            ],
            "formatString": "#,#"
          },
          {
            "name": "02_Amount",
            "description": "فروش ناخالص با فیلتر باطل نشده ",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'VN Fact_Sale'[Amount] ),",
              "",
              "    FILTER('VN Fact_Sale','VN Fact_Sale'[IsDeleted] <>1",
              "))"
            ],
            "formatString": "#,#"
          },
          {
            "name": "03_Discount",
            "description": "تخفیف با فیلتر باطل نشده ",
            "expression": [
              "",
              "",
              "    SUM ( 'VN Fact_Sale'[Discount] )",
              ""
            ],
            "formatString": "#,#"
          },
          {
            "name": "04_YTD Sales(AmountNut)",
            "description": " فروش خالص سال تا روز ",
            "expression": [
              "",
              "VAR Y = LOOKUPVALUE('BI DIM_DATE'[jyear], 'BI DIM_DATE'[Miladi], TODAY())",
              "VAR D = LOOKUPVALUE('BI DIM_DATE'[Day_number_year], 'BI DIM_DATE'[Miladi], TODAY())",
              "RETURN",
              "    CALCULATE('VN Fact_Sale'[01_AmountNut], 'BI DIM_DATE'[Day_number_year] <= D , 'BI DIM_DATE'[jyear]= Y)",
              "",
              "--- فروش خالص سال  تا روز "
            ],
            "formatString": "#,#"
          },
          {
            "name": "05_YTD Sales(Amount)",
            "description": "فروش ناخالص سال تا روز ",
            "expression": [
              "",
              "VAR Y = LOOKUPVALUE('BI DIM_DATE'[jyear], 'BI DIM_DATE'[Miladi], TODAY())",
              "VAR D = LOOKUPVALUE('BI DIM_DATE'[Day_number_year], 'BI DIM_DATE'[Miladi], TODAY())",
              "RETURN",
              "    CALCULATE('VN Fact_Sale'[02_Amount], ",
              "                    'BI DIM_DATE'[Day_number_year] <= D , ",
              "                                        'BI DIM_DATE'[jyear]= Y )",
              "",
              "                                ",
              "---- فروس ناخالص سال تا روز "
            ],
            "formatString": "#,#"
          },
          {
            "name": "06_YTD Sales LastYear(AmountNut)",
            "description": "فروش خالص سال گذشته تا روز ",
            "expression": [
              "",
              "                   VAR Y = LOOKUPVALUE('BI DIM_DATE'[jyear], 'BI DIM_DATE'[Miladi], TODAY())",
              "                   VAR D = LOOKUPVALUE('BI DIM_DATE'[Day_number_year], 'BI DIM_DATE'[Miladi], TODAY())",
              "                RETURN",
              " ",
              "      if(  CALCULATE('VN Fact_Sale'[01_AmountNut], ",
              "                       'BI DIM_DATE'[Day_number_year] <= D ,",
              "                                 'BI DIM_DATE'[jyear]= Y-1) <> BLANK(),",
              "                                              CALCULATE('VN Fact_Sale'[01_AmountNut], ",
              "                                                      'BI DIM_DATE'[Day_number_year] <= D ,",
              "                                                                   'BI DIM_DATE'[jyear]= Y-1),",
              "                                                                            \"حواله باز موجود نیست\")",
              "",
              "---  فروش خالص سال گذشته  تا روز "
            ],
            "formatString": "#,#"
          },
          {
            "name": "07_YTD Sales LastYear(Amount)",
            "description": "فروش ناخالص  سال گذشته  تا روز ",
            "expression": [
              "",
              "VAR Y = LOOKUPVALUE('BI DIM_DATE'[jyear], 'BI DIM_DATE'[Miladi], TODAY())",
              "VAR D = LOOKUPVALUE('BI DIM_DATE'[Day_number_year], 'BI DIM_DATE'[Miladi], TODAY())",
              "RETURN",
              "   ",
              " if(  CALCULATE('VN Fact_Sale'[02_Amount], ",
              "                       'BI DIM_DATE'[Day_number_year] <= D ,",
              "                                 'BI DIM_DATE'[jyear]= Y-1) <> BLANK(),",
              "                                              CALCULATE('VN Fact_Sale'[02_Amount], ",
              "                                                      'BI DIM_DATE'[Day_number_year] <= D ,",
              "                                                                   'BI DIM_DATE'[jyear]= Y-1),",
              "                                                                            \"حواله باز موجود نیست\")",
              "",
              "---  فروش ناخالص سال گذشته  تا روز ))"
            ],
            "formatString": "#,#"
          },
          {
            "name": "08_ MTD AmountNut",
            "description": "فروش خالص ماه تا روز ",
            "expression": [
              " ",
              "                VAR Y = LOOKUPVALUE('BI DIM_DATE'[jyear], 'BI DIM_DATE'[Miladi], TODAY())",
              "                 ",
              "                 VAR m = LOOKUPVALUE('BI DIM_DATE'[jmonthN], 'BI DIM_DATE'[Miladi], TODAY())",
              "",
              "               VAR D = LOOKUPVALUE('BI DIM_DATE'[day], 'BI DIM_DATE'[Miladi], TODAY())",
              "",
              "        RETURN",
              "           CALCULATE('VN Fact_Sale'[01_AmountNut], 'BI DIM_DATE'[jmonthN] = m , 'BI DIM_DATE'[jyear]= Y,",
              "                                                     'BI DIM_DATE'[day]<=d)",
              "                                            ",
              "---- فروش خالص ماه تا روز "
            ],
            "formatString": "#,#"
          },
          {
            "name": "09_LastYear MTD AmountNut",
            "description": "فروش خالص سال گذشته  ماه  تا روز",
            "expression": [
              " ",
              "                VAR Y = LOOKUPVALUE('BI DIM_DATE'[jyear], 'BI DIM_DATE'[Miladi], TODAY())",
              "                 ",
              "                 VAR m = LOOKUPVALUE('BI DIM_DATE'[jmonthN], 'BI DIM_DATE'[Miladi], TODAY())",
              "",
              "               VAR D = LOOKUPVALUE('BI DIM_DATE'[day], 'BI DIM_DATE'[Miladi], TODAY())",
              "",
              "        RETURN",
              "          if( CALCULATE('VN Fact_Sale'[01_AmountNut], 'BI DIM_DATE'[jmonthN] = m , 'BI DIM_DATE'[jyear]= Y-1,",
              "                                                     'BI DIM_DATE'[day]<=d)<> BLANK() ,",
              "                  CALCULATE('VN Fact_Sale'[01_AmountNut], 'BI DIM_DATE'[jmonthN] = m , 'BI DIM_DATE'[jyear]= Y-1,",
              "                                                     'BI DIM_DATE'[day]<=d), \"حواله باز موجود نیست \")",
              "",
              "---- فروش خالص سال گذشته ماه تا روز"
            ],
            "formatString": "#,#"
          },
          {
            "name": "010_ MTD Amount",
            "description": "فروش ناخالص ماه  تا روز ",
            "expression": [
              " ",
              "                VAR Y = LOOKUPVALUE('BI DIM_DATE'[jyear], 'BI DIM_DATE'[Miladi], TODAY())",
              "                 ",
              "                 VAR m = LOOKUPVALUE('BI DIM_DATE'[jmonthN], 'BI DIM_DATE'[Miladi], TODAY())",
              "",
              "               VAR D = LOOKUPVALUE('BI DIM_DATE'[day], 'BI DIM_DATE'[Miladi], TODAY())",
              "",
              "        RETURN",
              "           CALCULATE('VN Fact_Sale'[02_Amount], 'BI DIM_DATE'[jmonthN] = m , 'BI DIM_DATE'[jyear]= Y,",
              "                                                     'BI DIM_DATE'[day]<=d)",
              "                                            ",
              "---- فروش ناخالص ماه تا روز "
            ],
            "formatString": "#,#"
          },
          {
            "name": "011_LastYear MTD Amount",
            "description": "فروش ناخالص سال گذشته ماه تا روز",
            "expression": [
              " ",
              "                VAR Y = LOOKUPVALUE('BI DIM_DATE'[jyear], 'BI DIM_DATE'[Miladi], TODAY())",
              "                 ",
              "                 VAR m = LOOKUPVALUE('BI DIM_DATE'[jmonthN], 'BI DIM_DATE'[Miladi], TODAY())",
              "",
              "               VAR D = LOOKUPVALUE('BI DIM_DATE'[day], 'BI DIM_DATE'[Miladi], TODAY())",
              "",
              "        RETURN",
              "            if (CALCULATE('VN Fact_Sale'[02_Amount], 'BI DIM_DATE'[jmonthN] = m , 'BI DIM_DATE'[jyear]= Y-1,",
              "                                                     'BI DIM_DATE'[day]<=d) <> BLANK(), ",
              "              CALCULATE('VN Fact_Sale'[02_Amount], 'BI DIM_DATE'[jmonthN] = m , 'BI DIM_DATE'[jyear]= Y-1,",
              "                                                     'BI DIM_DATE'[day]<=d) , \"حواله باز موجود نیست \")",
              "",
              "---- فروش ناخالص سال گذشته ماه تا روز)"
            ],
            "formatString": "#,#"
          },
          {
            "name": "012_ DailySalesTarget",
            "description": "محاسبه  تارگت روزانه (ماه تا روز ) بر اساس فروش ناخالص ",
            "expression": [
              " ",
              "  ",
              "  DIVIDE( 'VN Fact_Sale'[010_ MTD Amount],",
              "                                  ",
              "          ",
              "         SUM('VN Fact_Target'[target_amount_per_day]) , BLANK()) ",
              "",
              "",
              "----- محاسبه  تارگت روزانه (ماه تا روز ) بر اساس فروش ناخالص "
            ],
            "formatString": "0.00 %;0.00- %;0.00 %"
          },
          {
            "name": "015_SalesTarget",
            "description": "تارگت  فروش ناخالص ",
            "expression": [
              " ",
              "                    DIVIDE( 'VN Fact_Sale'[02_Amount]",
              "                                  ",
              "                    ,SUM('VN Fact_Target'[target_amount_per_day]) , BLANK()) ",
              "",
              "",
              "",
              "------ درصد تحقق فروش ناخاص (فاکتور و حواله)"
            ],
            "formatString": "0.00 %;0.00- %;0.00 %"
          },
          {
            "name": "016_QTY",
            "description": " تعداد فروش ",
            "expression": [
              "",
              "     CALCULATE (",
              "              SUM ( 'VN Fact_Sale'[TotalQty] ),",
              "",
              "              FILTER('VN Fact_Sale','VN Fact_Sale'[IsDeleted] <>1",
              "))",
              "",
              "",
              "-----   تعداد فروش "
            ],
            "formatString": "#,#"
          },
          {
            "name": "017_GrowthRate YTD AmountNut",
            "description": "نرخ رشد فروش خالص( سال تا روز )",
            "expression": [
              "   if('VN Fact_Sale'[06_YTD Sales LastYear(AmountNut)]>0,",
              "                             ('VN Fact_Sale'[04_YTD Sales(AmountNut)] -'VN Fact_Sale'[06_YTD Sales LastYear(AmountNut)]) ",
              "                                       / 'VN Fact_Sale'[06_YTD Sales LastYear(AmountNut)])",
              "",
              "",
              "",
              "---- محاسبه نرخ رشد ناخالص سال  تا روز "
            ],
            "formatString": "0.00 %;0.00- %;0.00 %"
          },
          {
            "name": "018_GrowthRate YTD Amount",
            "description": " محاسبه نرخ رشد ناخالص سال  تا روز ",
            "expression": [
              "   if('VN Fact_Sale'[05_YTD Sales(Amount)]>0,",
              "                             ('VN Fact_Sale'[05_YTD Sales(Amount)] -'VN Fact_Sale'[07_YTD Sales LastYear(Amount)]) ",
              "                                       / 'VN Fact_Sale'[07_YTD Sales LastYear(Amount)])",
              "",
              "",
              "",
              "---- محاسبه نرخ رشد ناخالص سال  تا روز "
            ],
            "formatString": "0.00 %;0.00- %;0.00 %"
          },
          {
            "name": "019_GrowthRate MTD AmountNut",
            "description": "محاسبه نرخ رشد خالص ماه  تا روز ",
            "expression": [
              "   if('VN Fact_Sale'[09_LastYear MTD AmountNut]>0,",
              "                             ('VN Fact_Sale'[08_ MTD AmountNut] -'VN Fact_Sale'[09_LastYear MTD AmountNut]) ",
              "                                       / 'VN Fact_Sale'[09_LastYear MTD AmountNut])",
              "",
              "",
              "",
              "---- محاسبه نرخ رشد خالص ماه  تا روز "
            ],
            "formatString": "0.00 %;0.00- %;0.00 %"
          },
          {
            "name": "021_ Lastyear's sales",
            "description": "فروش ناخالص سال گذشته ",
            "expression": [
              " ",
              "               var y  = MAX('BI DIM_DATE'[jyear]) -1",
              " return ",
              " CALCULATE('VN Fact_Sale'[02_Amount] , 'BI DIM_DATE'[jyear] = y )",
              "",
              "",
              "----   فروش ناخالص سال گذشته ",
              "",
              ""
            ],
            "formatString": "#,#"
          },
          {
            "name": "022_SalesGrowthRate",
            "description": "نرخ رشد فروش ناخالص  نسبت به ماه مشابه سال قبل ",
            "expression": [
              "  ",
              "              ",
              "            if('VN Fact_Sale'[02_Amount] > 0  && 'VN Fact_Sale'[021_ Lastyear's sales] <> 0 , ",
              "",
              "               DIVIDE('VN Fact_Sale'[02_Amount]- 'VN Fact_Sale'[021_ Lastyear's sales] , ",
              "                                                'VN Fact_Sale'[021_ Lastyear's sales]))",
              "",
              "---- نرخ رشد فروش ناخالص نسبت به ماه مشابه سال قبل "
            ],
            "formatString": "0.00 %;0.00- %;0.00 %"
          },
          {
            "name": "020_GrowthRate MTD Amount",
            "description": " محاسبه نرخ رشد ناخالص ماه  تا روز ",
            "expression": [
              "  ",
              "-- if('VN Fact_Sale'[011_LastYear MTD Amount]>0,",
              "                           --  ('VN Fact_Sale'[010_ MTD Amount] -'VN Fact_Sale'[011_LastYear MTD Amount]) ",
              "                               --        / 'VN Fact_Sale'[011_LastYear MTD Amount])",
              "",
              "",
              "",
              "---- محاسبه نرخ رشد ناخالص ماه  تا روز ",
              "",
              "VAR X =",
              "    MAX ( 'BI DIM_DATE'[jyear]) -1",
              "VAR Y =",
              "    CALCULATE ( 'VN Fact_Sale'[02_Amount],'BI DIM_DATE'[jyear] = X )",
              "RETURN",
              "    IF ( Y > 0, DIVIDE ( 'VN Fact_Sale'[02_Amount], Y ) -1)"
            ],
            "formatString": "0.00 %;0.00- %;0.00 %"
          },
          {
            "name": "023_ Daily Amount",
            "description": "محاسبه فروش روزانه",
            "expression": [
              " ",
              "                VAR Y = LOOKUPVALUE('BI DIM_DATE'[jyear], 'BI DIM_DATE'[Miladi], TODAY())",
              "                 ",
              "                 VAR m = LOOKUPVALUE('BI DIM_DATE'[jmonthN], 'BI DIM_DATE'[Miladi], TODAY())",
              "",
              "               VAR D = LOOKUPVALUE('BI DIM_DATE'[day], 'BI DIM_DATE'[Miladi], TODAY())",
              "",
              "        RETURN",
              "           CALCULATE('VN Fact_Sale'[02_Amount], 'BI DIM_DATE'[jmonthN] = m , 'BI DIM_DATE'[jyear]= Y,",
              "                                                     'BI DIM_DATE'[day]=d)",
              "",
              "",
              "",
              "-- محاسبه فروش روزانه"
            ],
            "formatString": "#,#"
          },
          {
            "name": "024_YTD Sales LastYear(Amount)* growth Rate Arva",
            "description": "فروش ناخالص سال گذشته  تا روز با نرخ تورم جدید آروا در سال 1402",
            "expression": [
              "",
              "VAR Y = LOOKUPVALUE('BI DIM_DATE'[jyear], 'BI DIM_DATE'[Miladi], TODAY())",
              "VAR D = LOOKUPVALUE('BI DIM_DATE'[Day_number_year], 'BI DIM_DATE'[Miladi], TODAY())",
              "RETURN",
              "   ",
              " (if(  CALCULATE('VN Fact_Sale'[02_Amount], ",
              "                       'BI DIM_DATE'[Day_number_year] <= D ,",
              "                                 'BI DIM_DATE'[jyear]= Y-1) <> BLANK(),",
              "                                              CALCULATE('VN Fact_Sale'[02_Amount], ",
              "                                                      'BI DIM_DATE'[Day_number_year] <= D ,",
              "                                                                   'BI DIM_DATE'[jyear]= Y-1),",
              "                                                                            \"حواله باز موجود نیست\")  ) ",
              "                                                      +",
              "",
              " (if(  CALCULATE('VN Fact_Sale'[02_Amount], ",
              "                       'BI DIM_DATE'[Day_number_year] <= D ,",
              "                                 'BI DIM_DATE'[jyear]= Y-1) <> BLANK(),",
              "                                              CALCULATE('VN Fact_Sale'[02_Amount], ",
              "                                                      'BI DIM_DATE'[Day_number_year] <= D ,",
              "                                                                   'BI DIM_DATE'[jyear]= Y-1),",
              "                                                                            \"حواله باز موجود نیست\") *45 ) /100",
              "",
              "---  فروش ناخالص سال گذشته  تا روز با نرخ تورم جدید آروا در سال 1402))"
            ],
            "formatString": "#,#"
          },
          {
            "name": "025_GrowthRate YTD Amount(growth Rate Arva)",
            "description": " محاسبه نرخ رشد ناخالص سال  تا روز   با احتساب افزایش قیمت 45درصدی آروا در سال 1402 ",
            "expression": [
              "  ",
              "         if('VN Fact_Sale'[05_YTD Sales(Amount)]>0,",
              "                       ('VN Fact_Sale'[05_YTD Sales(Amount)] -'VN Fact_Sale'[024_YTD Sales LastYear(Amount)* growth Rate Arva]) ",
              "                                       / 'VN Fact_Sale'[024_YTD Sales LastYear(Amount)* growth Rate Arva])",
              "",
              "",
              "",
              "---- محاسبه نرخ رشد ناخالص سال  تا روز   با احتساب افزایش قیمت 45درصدی آروا در سال 1402 ",
              "---- در این مژر نرخ رشد محصولات شرکت با تورم حدودی 45 درصدی قیمت نسبت  به سال جدید محاسبه شده است",
              "--- یعنی  به طور میانگین اگر محصولات گذشته با  نرخ  امسال به فروش میرفت  نرخ رشد چقدر محاسبه میشد"
            ],
            "formatString": "0.00 %;0.00- %;0.00 %"
          },
          {
            "name": "026_YTD Sales LastYear(AmountNut)* growth Rate Arva",
            "description": " فروش خالص سال گذشته  تا روز با احتساب نرخ تورم 45 درصدی آروا",
            "expression": [
              "",
              "                   VAR Y = LOOKUPVALUE('BI DIM_DATE'[jyear], 'BI DIM_DATE'[Miladi], TODAY())",
              "                   VAR D = LOOKUPVALUE('BI DIM_DATE'[Day_number_year], 'BI DIM_DATE'[Miladi], TODAY())",
              "                RETURN",
              " ",
              "     ( if(  CALCULATE('VN Fact_Sale'[01_AmountNut], ",
              "                       'BI DIM_DATE'[Day_number_year] <= D ,",
              "                                 'BI DIM_DATE'[jyear]= Y-1) <> BLANK(),",
              "                                              CALCULATE('VN Fact_Sale'[01_AmountNut], ",
              "                                                      'BI DIM_DATE'[Day_number_year] <= D ,",
              "                                                                   'BI DIM_DATE'[jyear]= Y-1),",
              "                                                                            \"حواله باز موجود نیست\")) ",
              "                +",
              "",
              "           ( if(  CALCULATE('VN Fact_Sale'[01_AmountNut], ",
              "                       'BI DIM_DATE'[Day_number_year] <= D ,",
              "                                 'BI DIM_DATE'[jyear]= Y-1) <> BLANK(),",
              "                                              CALCULATE('VN Fact_Sale'[01_AmountNut], ",
              "                                                      'BI DIM_DATE'[Day_number_year] <= D ,",
              "                                                                   'BI DIM_DATE'[jyear]= Y-1),",
              "                                                                            \"حواله باز موجود نیست\")*45) /100 ",
              "",
              "---  فروش خالص سال گذشته  تا روز با احتساب نرخ تورم 45 درصدی آروا",
              "-- این مژرفروش سال جدید را بر مبنای نرخ تورم 45 درصدی شرکت محاسبه میکند"
            ],
            "formatString": "#,#"
          },
          {
            "name": "027_GrowthRate YTD AmountNut(growth Rate Arva)",
            "description": " محاسبه نرخ رشد ناخالص سال  تا روز بر مبنای نرخ رشد قیمت  45درصدی سال جدید",
            "expression": [
              "  ",
              "",
              "       if('VN Fact_Sale'[06_YTD Sales LastYear(AmountNut)]>0,",
              "                    ('VN Fact_Sale'[04_YTD Sales(AmountNut)] -'VN Fact_Sale'[026_YTD Sales LastYear(AmountNut)* growth Rate Arva]) ",
              "                                       / 'VN Fact_Sale'[026_YTD Sales LastYear(AmountNut)* growth Rate Arva])",
              "",
              "",
              "",
              "---- محاسبه نرخ رشد ناخالص سال  تا روز بر مبنای نرخ رشد قیمت  45درصدی سال جدید"
            ],
            "formatString": "0.00 %;0.00- %;0.00 %"
          },
          {
            "name": "028_LastYear MTD Amount *growth Rate Arva",
            "description": "فروش ناخالص سال گذشته ماه تا روز با احتساب نرخ رشد 45 درصدی قیمت کالا",
            "expression": [
              " ",
              "                VAR Y = LOOKUPVALUE('BI DIM_DATE'[jyear], 'BI DIM_DATE'[Miladi], TODAY())",
              "                 ",
              "                 VAR m = LOOKUPVALUE('BI DIM_DATE'[jmonthN], 'BI DIM_DATE'[Miladi], TODAY())",
              "",
              "               VAR D = LOOKUPVALUE('BI DIM_DATE'[day], 'BI DIM_DATE'[Miladi], TODAY())",
              "",
              "        RETURN",
              "          ",
              " ( if (CALCULATE('VN Fact_Sale'[02_Amount], 'BI DIM_DATE'[jmonthN] = m , 'BI DIM_DATE'[jyear]= Y-1,",
              "                                                     'BI DIM_DATE'[day]<=d) <> BLANK(), ",
              "              CALCULATE('VN Fact_Sale'[02_Amount], 'BI DIM_DATE'[jmonthN] = m , 'BI DIM_DATE'[jyear]= Y-1,",
              "                                                     'BI DIM_DATE'[day]<=d) , \"حواله باز موجود نیست \")) ",
              "                                +",
              "     ",
              "",
              "          ",
              " ( if (CALCULATE('VN Fact_Sale'[02_Amount], 'BI DIM_DATE'[jmonthN] = m , 'BI DIM_DATE'[jyear]= Y-1,",
              "                                                     'BI DIM_DATE'[day]<=d) <> BLANK(), ",
              "              CALCULATE('VN Fact_Sale'[02_Amount], 'BI DIM_DATE'[jmonthN] = m , 'BI DIM_DATE'[jyear]= Y-1,",
              "                                                     'BI DIM_DATE'[day]<=d) , \"حواله باز موجود نیست \")*45) /100",
              "",
              "",
              "---- فروش ناخالص سال گذشته ماه تا روز با احتساب نرخ رشد 45 درصدی قیمت کالا)",
              "-- این مژر فروش سال گذشته را با قیمت جدید محاسبه میکند"
            ],
            "formatString": "#,#"
          },
          {
            "name": "029_GrowthRate MTD Amount",
            "description": "محاسبه نرخ رشد ناخالص ماه  تا روز با احتساب رشد 45درصدی قیمت ",
            "expression": [
              "   if('VN Fact_Sale'[011_LastYear MTD Amount]>0,",
              "                             ('VN Fact_Sale'[010_ MTD Amount] -'VN Fact_Sale'[028_LastYear MTD Amount *growth Rate Arva]) ",
              "                                       / 'VN Fact_Sale'[028_LastYear MTD Amount *growth Rate Arva])",
              "",
              "",
              "",
              "---- محاسبه نرخ رشد ناخالص ماه  تا روز با احتساب رشد 45درصدی قیمت "
            ],
            "formatString": "0.00 %;0.00- %;0.00 %"
          },
          {
            "name": "030_LastYear MTD AmountNut*GrowthRate Arva",
            "description": "فروش خالص سال گذشته ماه تا روز با احتساب نرخ رشد 45 درصدی قیمت کالا آروا",
            "expression": [
              " ",
              "                VAR Y = LOOKUPVALUE('BI DIM_DATE'[jyear], 'BI DIM_DATE'[Miladi], TODAY())",
              "                 ",
              "                 VAR m = LOOKUPVALUE('BI DIM_DATE'[jmonthN], 'BI DIM_DATE'[Miladi], TODAY())",
              "",
              "               VAR D = LOOKUPVALUE('BI DIM_DATE'[day], 'BI DIM_DATE'[Miladi], TODAY())",
              "",
              "        RETURN",
              "        (  if( CALCULATE('VN Fact_Sale'[01_AmountNut], 'BI DIM_DATE'[jmonthN] = m , 'BI DIM_DATE'[jyear]= Y-1,",
              "                                                     'BI DIM_DATE'[day]<=d)<> BLANK() ,",
              "                  CALCULATE('VN Fact_Sale'[01_AmountNut], 'BI DIM_DATE'[jmonthN] = m , 'BI DIM_DATE'[jyear]= Y-1,",
              "                                                     'BI DIM_DATE'[day]<=d), \"حواله باز موجود نیست \"))",
              "                                                 ",
              "                                                       +",
              " (  if( CALCULATE('VN Fact_Sale'[01_AmountNut], 'BI DIM_DATE'[jmonthN] = m , 'BI DIM_DATE'[jyear]= Y-1,",
              "                                                     'BI DIM_DATE'[day]<=d)<> BLANK() ,",
              "                  CALCULATE('VN Fact_Sale'[01_AmountNut], 'BI DIM_DATE'[jmonthN] = m , 'BI DIM_DATE'[jyear]= Y-1,",
              "                                                     'BI DIM_DATE'[day]<=d), \"حواله باز موجود نیست \")*45)/100",
              "",
              "----  فروش خالص سال گذشته ماه تا روز با احتساب نرخ رشد 45 درصدی قیمت کالا آروا"
            ],
            "formatString": "#,#"
          },
          {
            "name": "031_GrowthRate MTD AmountNUT(GrowthRate Arva)",
            "description": "محاسبه نرخ رشد خالص ماه  تا روز با احتساب رشد 45درصدی قیمت ",
            "expression": [
              "",
              "  if('VN Fact_Sale'[030_LastYear MTD AmountNut*GrowthRate Arva]>0,",
              "                             ('VN Fact_Sale'[08_ MTD AmountNut] -'VN Fact_Sale'[030_LastYear MTD AmountNut*GrowthRate Arva])",
              "                                       / 'VN Fact_Sale'[030_LastYear MTD AmountNut*GrowthRate Arva])",
              "",
              "",
              "",
              "---- محاسبه نرخ رشد خالص ماه  تا روز با احتساب رشد 45درصدی قیمت )"
            ],
            "formatString": "0.00 %;0.00- %;0.00 %"
          },
          {
            "name": "032_TOP 10 Personel in Sale in (CurrentMonth)",
            "description": "محاسبه  10 فروشنده برتر در ماه جاری ",
            "expression": [
              " ",
              "",
              "      VAR YY = LOOKUPVALUE('BI DIM_DATE'[jyear], 'BI DIM_DATE'[Miladi], TODAY())",
              "      var MM = LOOKUPVALUE('BI DIM_DATE'[jmonthN] , 'BI DIM_DATE'[Miladi], TODAY())",
              "           return",
              "",
              "",
              "      CALCULATE( 'VN Fact_Sale'[02_Amount] ,  ",
              "                  TOPN(10 , ",
              "                           ALL('VN Dim_Personnel'[ContactName]) , 'VN Fact_Sale'[02_Amount]) ,                                 ",
              "                                              VALUES( 'VN Dim_Personnel'[ContactName])) ",
              "                                       ",
              "",
              "",
              "",
              "",
              "-- محاسبه  10 فروشنده برتر  )"
            ],
            "formatString": "#,#"
          },
          {
            "name": "036_Ave DateDiff( Draft & Sale )",
            "description": " میانگین فاصله زمانی بین  تاریخ حواله  تا فاکتور ",
            "expression": [
              "",
              "      ",
              "   AVERAGEX(SUMMARIZE('VN Fact_Sale','VN Fact_Sale'[SaleDate],'VN Fact_Sale'[DraftDate], 'BI Dim_Geographic'[StateName],",
              "                     \"x\",max('VN Fact_Sale'[035_ DateDiff (draft and sale)])),[x])",
              "",
              "",
              "                                   ",
              "",
              "",
              "",
              "-- میانگین فاصله زمانی بین  تاریخ حواله  تا فاکتور ",
              ""
            ]
          },
          {
            "name": "037_ Last month's sale",
            "description": " فروش ناخالص ماه گذشته ",
            "expression": [
              " ",
              "      var m = MAX('BI DIM_DATE'[jmonthN])",
              "var pm= if(m=1,12,m-1)",
              "var y= if(pm=12,MAX('BI DIM_DATE'[jyear])-1, MAX('BI DIM_DATE'[jyear]))",
              "",
              "   return",
              "   ",
              "       CALCULATE('VN Fact_Sale'[02_Amount] , 'BI DIM_DATE'[jmonthN]= pm , 'BI DIM_DATE'[jyear] = y)",
              "",
              "--  فروش ناخالص ماه گذشته  "
            ],
            "formatString": "#,#"
          },
          {
            "name": "038_MonthlyGrothRate",
            "description": "نرخ رشد ماهانه فروش ناخالص ",
            "expression": [
              "     if('VN Fact_Sale'[037_ Last month's sale]> 0 && 'VN Fact_Sale'[02_Amount]<> BLANK(), ",
              "                            ( 'VN Fact_Sale'[02_Amount]- 'VN Fact_Sale'[037_ Last month's sale])",
              "                                         / 'VN Fact_Sale'[037_ Last month's sale])",
              "",
              "-- نرخ رشد ماهانه فروش ناخالص )"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "039 _Net sales with return deductions",
            "description": "فروش خالص با کسر برگشتی ",
            "expression": [
              " ",
              "     ",
              "",
              "                     'VN Fact_Sale'[01_AmountNut]  -  'VN Fact_RetSale'[02_returnedAmountNut]",
              "               ",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "--فروش خالص با کسر برگشتی "
            ],
            "formatString": "#,#"
          }
        ]
      },
      {
        "name": "BI select_value",
        "columns": [
          {
            "name": "select",
            "dataType": "string",
            "sourceColumn": "select"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    BI_select_value = Source{[Schema=\"BI\",Item=\"select_value\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(BI_select_value,\"ي\",\"ی\",Replacer.ReplaceText,{\"select\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "04_ select",
            "description": "اسلایسر نوع فروش",
            "expression": [
              " if ( SELECTEDVALUE('BI select_value'[select]) = \"فروش\", ",
              "                               'VN Fact_Sale'[01_AmountNut],",
              "             IF(SELECTEDVALUE('BI select_value'[select] )= \"فروش ناخالص\",",
              "                               'VN Fact_Sale'[02_Amount],",
              "            if(SELECTEDVALUE( 'BI select_value'[select] ) = \"تخفیفات\",",
              "                               'VN Fact_Sale'[03_Discount], ",
              "             IF(SELECTEDVALUE('BI select_value'[select] ) = \"برگشتی\",",
              "                                'VN Fact_RetSale'[01_returnedAmountNut]))))",
              "",
              "",
              "",
              "",
              "               ------- با  انتخاب هر یک در یک صفحه در پاور بی ای مشخصات مربوطه نمایش داده  می شود برای جلوگیری از ساخت بوک مارک این مژر ساخته شد)))))))"
            ],
            "formatString": "#,#"
          },
          {
            "name": "05 _ Title(به تفکیک ماه)",
            "expression": "CONCATENATE( MAX('BI select_value'[select]) ,\" به تفکیک سال و ماه   \")"
          },
          {
            "name": "06 _ Title(رتبه بندی استان ها)",
            "expression": "CONCATENATE( \"   رتبه بندی استان ها  بر اساس \",MAX('BI select_value'[select]) )"
          },
          {
            "name": "07 _ Title(سهم مشتریان از )",
            "expression": "CONCATENATE( \" سهم مشتریان از \",MAX('BI select_value'[select]) )"
          },
          {
            "name": "08 _ Title(سهم گروه کالا از)",
            "expression": "CONCATENATE( \" سهم گروه کالا از \",MAX('BI select_value'[select]) )"
          },
          {
            "name": "09_Title(به تفکیک سال )",
            "expression": "CONCATENATE( MAX('BI select_value'[select]) ,\" به تفکیک سال   \")"
          }
        ]
      },
      {
        "name": "VN Fact_RetSale",
        "description": "جدول برگشت از فروش",
        "columns": [
          {
            "name": "ID",
            "dataType": "int64",
            "sourceColumn": "ID"
          },
          {
            "name": "SaleDate",
            "dataType": "string",
            "description": "تاریخ فروش",
            "sourceColumn": "SaleDate"
          },
          {
            "name": "SaleHdr_ID",
            "dataType": "int64",
            "description": "id فاکتور اصلی",
            "sourceColumn": "SaleHdr_ID"
          },
          {
            "name": "HealthCode",
            "dataType": "string",
            "description": "وضعیت سلامت کالا",
            "sourceColumn": "HealthCode"
          },
          {
            "name": "RetTypeCode",
            "dataType": "string",
            "description": "نوع برگشت کالا",
            "sourceColumn": "RetTypeCode"
          },
          {
            "name": "RetCauseRef",
            "dataType": "string",
            "description": "علت برگشت کالا",
            "sourceColumn": "RetCauseRef"
          },
          {
            "name": "CustRef",
            "dataType": "int64",
            "description": "کد مشتری",
            "sourceColumn": "CustRef"
          },
          {
            "name": "DealerRef",
            "dataType": "int64",
            "description": "کد فروشنده",
            "sourceColumn": "DealerRef"
          },
          {
            "name": "RetSaleNo",
            "dataType": "int64",
            "description": "شماره برگشت",
            "sourceColumn": "RetSaleNo"
          },
          {
            "name": "GoodsRef",
            "dataType": "int64",
            "description": "کد کالا",
            "sourceColumn": "GoodsRef"
          },
          {
            "name": "MainQty",
            "dataType": "double",
            "description": "تعداد برگشتی",
            "sourceColumn": "MainQty"
          },
          {
            "name": "AmountNut",
            "dataType": "double",
            "description": "مبلغ خالص برگشت از فروش",
            "sourceColumn": "AmountNut"
          },
          {
            "name": "Discount",
            "dataType": "double",
            "description": "مبلغ تخفیف",
            "sourceColumn": "Discount"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "description": "مبلغ ناخالص برگشت از فروش",
            "sourceColumn": "Amount"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    VN_Fact_RetSale = Source{[Schema=\"VN\",Item=\"Fact_RetSale\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(VN_Fact_RetSale,\"ي\",\"ی\",Replacer.ReplaceText,{\"HealthCode\", \"RetTypeCode\", \"RetCauseRef\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "01_returnedAmountNut",
            "description": "خالص برگشت از فروش ",
            "expression": [
              "",
              "",
              "CALCULATE(    SUM ( 'VN Fact_RetSale'[Amount] ))",
              "",
              "",
              "",
              "----  ناخالص  برگشت از فروش ",
              ""
            ],
            "formatString": "#,#"
          },
          {
            "name": "02_returnedAmountNut",
            "description": "خالص برگشتی",
            "expression": [
              "",
              "",
              "CALCULATE(    SUM ( 'VN Fact_RetSale'[AmountNut] ))",
              "",
              "-- خالص برگشتی"
            ]
          }
        ]
      },
      {
        "name": "VN Fact_Target",
        "description": "جدول تارگت ها",
        "columns": [
          {
            "name": "Jalali_1",
            "dataType": "string",
            "description": "تاریخ",
            "sourceColumn": "Jalali_1"
          },
          {
            "name": "target_amount_per_day",
            "dataType": "int64",
            "description": "مقدار تارگت روزانه هر شهر در هر تاریخ خاص",
            "sourceColumn": "target_amount_per_day",
            "formatString": "#,#"
          },
          {
            "name": "StateCode",
            "dataType": "string",
            "description": "کد شهر",
            "sourceColumn": "StateCode"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    VN_Fact_Target = Source{[Schema=\"VN\",Item=\"Fact_Target\"]}[Data]",
                "in",
                "    VN_Fact_Target"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Target",
            "expression": " CALCULATE( SUM('VN Fact_Target'[target_amount_per_day]))"
          },
          {
            "name": "02__ MTD Target",
            "description": "تارگت ماه تا روز ",
            "expression": [
              " ",
              "                VAR Y = LOOKUPVALUE('BI DIM_DATE'[jyear], 'BI DIM_DATE'[Miladi], TODAY())",
              "                 ",
              "                 VAR m = LOOKUPVALUE('BI DIM_DATE'[jmonthN], 'BI DIM_DATE'[Miladi], TODAY())",
              "",
              "               VAR D = LOOKUPVALUE('BI DIM_DATE'[day], 'BI DIM_DATE'[Miladi], TODAY())",
              "",
              "        RETURN",
              "           CALCULATE(sum('VN Fact_Target'[target_amount_per_day]),",
              "                                        'BI DIM_DATE'[jmonthN] = m , ",
              "                                                       'BI DIM_DATE'[jyear]= Y,",
              "                                                                   'BI DIM_DATE'[day]<=d)             ",
              "           ",
              "-- تارگت ماه تا روز "
            ],
            "formatString": "#,#"
          },
          {
            "name": "03_MTD Target percentage",
            "description": "درصد تحقق ماه تا روز ",
            "expression": [
              "       ",
              "                                     DIVIDE('VN Fact_Sale'[010_ MTD Amount] , 'VN Fact_Target'[02__ MTD Target])",
              "",
              "                    -- درصد تحقق ماه تا روز "
            ],
            "formatString": "0.00 %;0.00- %;0.00 %"
          },
          {
            "name": "04__Daily Target",
            "description": "محاسبه تارگت روزانه ",
            "expression": [
              " ",
              "                VAR Y = LOOKUPVALUE('BI DIM_DATE'[jyear], 'BI DIM_DATE'[Miladi], TODAY())",
              "                 ",
              "                 VAR m = LOOKUPVALUE('BI DIM_DATE'[jmonthN], 'BI DIM_DATE'[Miladi], TODAY())",
              "",
              "               VAR D = LOOKUPVALUE('BI DIM_DATE'[day], 'BI DIM_DATE'[Miladi], TODAY())",
              "",
              "        RETURN",
              "           CALCULATE(sum('VN Fact_Target'[target_amount_per_day]),",
              "                                        'BI DIM_DATE'[jmonthN] = m , ",
              "                                                       'BI DIM_DATE'[jyear]= Y,",
              "                                                                   'BI DIM_DATE'[day]=d)  ",
              "",
              "----- محاسبه تارگت روزانه "
            ],
            "formatString": "#,#"
          },
          {
            "name": "05_daily target percentage",
            "description": "محاسبه تارگت روزانه",
            "expression": [
              "",
              "",
              "",
              "             DIVIDE('VN Fact_Sale'[023_ Daily Amount] , 'VN Fact_Target'[04__Daily Target])",
              "",
              "",
              "",
              "---- محاسبه تارگت روزانه"
            ],
            "formatString": "0.00 %;0.00- %;0.00 %"
          },
          {
            "name": "06_YTD Target",
            "description": "محاسبه تارگت سال تا روز",
            "expression": [
              " ",
              "                VAR Y = LOOKUPVALUE('BI DIM_DATE'[jyear], 'BI DIM_DATE'[Miladi], TODAY())",
              "                 ",
              "         VAR D = LOOKUPVALUE('BI DIM_DATE'[Day_number_year], 'BI DIM_DATE'[Miladi], TODAY())",
              "",
              "         ",
              "        RETURN",
              "           CALCULATE(sum('VN Fact_Target'[target_amount_per_day]), ",
              "                                     'BI DIM_DATE'[jyear]= Y,",
              "                                      'BI DIM_DATE'[Day_number_year] <= D)",
              "                                       ",
              "                                                    ",
              "-- محاسبه تارگت سال تا روز "
            ],
            "formatString": "#,#"
          },
          {
            "name": "07_ YTD Target percentage",
            "description": "درصد تحقق سال تا روز",
            "expression": [
              "",
              "",
              "",
              "             DIVIDE('VN Fact_Sale'[05_YTD Sales(Amount)] , 'VN Fact_Target'[06_YTD Target])",
              "",
              "--درصد تحقق سال تا روز"
            ],
            "formatString": "0.00 %;0.00- %;0.00 %"
          },
          {
            "name": "05_YTD target",
            "expression": [
              "",
              "VAR Y = LOOKUPVALUE('BI DIM_DATE'[jyear], 'BI DIM_DATE'[Miladi], TODAY())",
              "--VAR D = LOOKUPVALUE('BI DIM_DATE'[Day_number_year], 'BI DIM_DATE'[Miladi], TODAY())",
              "RETURN",
              "    CALCULATE(sum('VN Fact_Target'[target_amount_per_day]), ",
              "                  --    'BI DIM_DATE'[Day_number_year] <= D , ",
              "                                        'BI DIM_DATE'[jyear]= Y , 'BI DIM_DATE'[Miladi]<=TODAY())",
              "",
              "",
              "",
              "---- تارگت سال تا روز "
            ]
          }
        ]
      },
      {
        "name": "VN Dim_Personnel",
        "description": "جدول نام ",
        "columns": [
          {
            "name": "PersonnelCode",
            "dataType": "string",
            "sourceColumn": "PersonnelCode"
          },
          {
            "name": "PersonnelId",
            "dataType": "int64",
            "sourceColumn": "PersonnelId"
          },
          {
            "name": "ContactName",
            "dataType": "string",
            "sourceColumn": "ContactName"
          },
          {
            "name": "IsDealer",
            "dataType": "string",
            "description": "ویزیتور",
            "sourceColumn": "IsDealer"
          },
          {
            "name": "IsActiveDealer",
            "dataType": "boolean",
            "sourceColumn": "IsActiveDealer"
          },
          {
            "type": "calculated",
            "name": "003_Number of visitors",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "description": "مشخص شدن ویزیتور با عدد 1",
            "expression": [
              " if( 'VN Dim_Personnel'[IsDealer] = \"TRUE\" , 1 , 0)",
              "",
              "-- مشخص شدن ویزیتور از پرسنل"
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    VN_Dim_Personnel = Source{[Schema=\"VN\",Item=\"Dim_Personnel\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(VN_Dim_Personnel,\"ي\",\"ی\",Replacer.ReplaceText,{\"ContactName\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "01_BestSeller",
            "expression": [
              "   ",
              "-- \"بهترین فروشنده \" &",
              "                    LOOKUPVALUE('VN Fact_Sale'[DealerRef], 'VN Dim_Personnel'[PersonnelId], MAX('VN Fact_Sale'[Amount]))",
              "-- max('VN Fact_RetSale'[Amount]) ,",
              "                                               --  FILTER('VN Fact_Sale','VN Fact_Sale'[IsDeleted] <>1)))",
              "               ",
              "",
              "",
              "",
              "----- بهترین فروشنده))))"
            ]
          },
          {
            "name": "002_CountPersonel",
            "description": "تعداد کل پرسنل ",
            "expression": [
              "    ",
              "       DISTINCTCOUNT('VN Dim_Personnel'[PersonnelId])",
              "    ",
              "---- تعداد کل پرسنل ",
              ""
            ],
            "formatString": "#,#"
          }
        ]
      },
      {
        "name": "VN RFM",
        "columns": [
          {
            "name": "CustRef",
            "dataType": "int64",
            "sourceColumn": "CustRef"
          },
          {
            "name": "Recency_day",
            "dataType": "int64",
            "sourceColumn": "Recency_day"
          },
          {
            "name": "Age_of_customer",
            "dataType": "int64",
            "sourceColumn": "Age_of_customer"
          },
          {
            "name": "Frequency",
            "dataType": "int64",
            "sourceColumn": "Frequency"
          },
          {
            "name": "Mean_diff_date",
            "dataType": "double",
            "sourceColumn": "Mean_diff_date"
          },
          {
            "name": "SUM(Amount)",
            "dataType": "double",
            "sourceColumn": "SUM(Amount)"
          },
          {
            "name": "ave_sum_amount",
            "dataType": "double",
            "sourceColumn": "ave_sum_amount"
          },
          {
            "name": "Cluster",
            "dataType": "string",
            "sourceColumn": "Cluster"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    VN_RFM = Source{[Schema=\"VN\",Item=\"RFM\"]}[Data]",
                "in",
                "    VN_RFM"
              ]
            }
          }
        ]
      },
      {
        "name": "NL BSC",
        "columns": [
          {
            "name": "Row",
            "dataType": "int64",
            "sourceColumn": "Row"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year"
          },
          {
            "name": "Month",
            "dataType": "int64",
            "sourceColumn": "Month"
          },
          {
            "name": "Indicator status",
            "dataType": "int64",
            "sourceColumn": "Indicator status"
          },
          {
            "name": "the unit",
            "dataType": "string",
            "sourceColumn": "the unit"
          },
          {
            "name": "Index code",
            "dataType": "int64",
            "sourceColumn": "Index code"
          },
          {
            "name": "Organization indicators",
            "dataType": "string",
            "sourceColumn": "Organization indicators"
          },
          {
            "name": "scale of measurement",
            "dataType": "string",
            "sourceColumn": "scale of measurement"
          },
          {
            "name": "index direction",
            "dataType": "string",
            "sourceColumn": "index direction"
          },
          {
            "name": "index direction_code",
            "dataType": "int64",
            "sourceColumn": "index direction_code"
          },
          {
            "name": "monitoring period",
            "dataType": "string",
            "sourceColumn": "monitoring period"
          },
          {
            "name": "The starting point of the course",
            "dataType": "double",
            "sourceColumn": "The starting point of the course"
          },
          {
            "name": "Amount achieved during the period",
            "dataType": "double",
            "sourceColumn": "Amount achieved during the period"
          },
          {
            "name": "Acceptance limit",
            "dataType": "double",
            "sourceColumn": "Acceptance limit"
          },
          {
            "name": "Target",
            "dataType": "double",
            "sourceColumn": "Target"
          },
          {
            "name": "the trustee",
            "dataType": "string",
            "sourceColumn": "the trustee"
          },
          {
            "name": "Senior user",
            "dataType": "string",
            "sourceColumn": "Senior user"
          },
          {
            "name": "Unit code",
            "dataType": "int64",
            "sourceColumn": "Unit code"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    NL_BSC = Source{[Schema=\"NL\",Item=\"BSC\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(NL_BSC,\"ي\",\"ی\",Replacer.ReplaceText,{\"the unit\", \"Organization indicators\", \"scale of measurement\", \"index direction\", \"monitoring period\", \"the trustee\", \"Senior user\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "001_BSCTahaghogh",
            "description": " مقدار تحقق طی دوره  به درصد برای BSC",
            "expression": [
              " ",
              "",
              "           IF(MAX('NL BSC'[scale of measurement]) = \"درصد\",",
              "                                        AVERAGE(('NL BSC'[Amount achieved during the period])))",
              "",
              "",
              "----  مقدار تحقق طی دوره  به درصد برای BSC)"
            ]
          },
          {
            "name": "002_Gauge Color",
            "description": "رنگ گیج BSc",
            "expression": [
              " ",
              "",
              " IF(MAX('NL BSC'[Target]) >= MAX('NL BSC'[Acceptance limit] ) && MAX('NL BSC'[index direction]) = \"افزایشی\" && MAX('NL BSC'[Amount achieved during the period]) > MAX('NL BSC'[Target]), \"#01533D\",  ----- افزایشی",
              "--IF(MAX(BSC[هدف]) >= MAX(BSC[حد پذیرش] ) && MAX(BSC[جهت شاخص]) = \"افزایشی\" && MAX(BSC[هدف])> MAX(BSC[مقدار محقق شده طی دوره]) >= MAX(BSC[حد پذیرش]), \"#DBDE1C\",   ----- افزایشی",
              "            ",
              "              ",
              "      if( MAX('NL BSC'[Target]) >= MAX('NL BSC'[Acceptance limit])    && MAX('NL BSC'[index direction]) = \"افزایشی\" && MAX('NL BSC'[Acceptance limit])> MAX('NL BSC'[Amount achieved during the period]) ,\"#BB0E0E\",",
              "          if( MAX('NL BSC'[Target]) <= MAX('NL BSC'[Acceptance limit] ) && MAX('NL BSC'[index direction]) = \"کاهشی\"  &&   MAX('NL BSC'[Target])< MAX('NL BSC'[Amount achieved during the period]) ,\"#BB0E0E\" , ",
              "",
              "  if( MAX('NL BSC'[Target]) <= MAX('NL BSC'[Acceptance limit] ) && MAX('NL BSC'[index direction]) = \"کاهشی\"     &&   MAX('NL BSC'[Acceptance limit])> MAX('NL BSC'[Amount achieved during the period]) ,\"#01533D\"))))",
              "       --       if (MAX(BSC[هدف]) <= MAX(BSC[حد پذیرش] )&& MAX(BSC[هدف])< MAX(BSC[مقدار محقق شده طی دوره]) < MAX(BSC[حد پذیرش]), \"#DBDE1C\", ",
              "  --  \"#01533D\"))",
              "    --     ))))",
              "",
              "",
              "",
              "---- رنگ گیج BSc"
            ]
          }
        ]
      },
      {
        "name": "NL payment_report",
        "description": "گزارش پرداخت نیلرام ",
        "columns": [
          {
            "name": "payment_date",
            "dataType": "string",
            "sourceColumn": "payment_date"
          },
          {
            "name": "due_date",
            "dataType": "string",
            "sourceColumn": "due_date"
          },
          {
            "name": "Date_of_operation",
            "dataType": "string",
            "sourceColumn": "Date_of_operation"
          },
          {
            "name": "payment_number",
            "dataType": "string",
            "sourceColumn": "payment_number"
          },
          {
            "name": "Amount",
            "dataType": "int64",
            "description": "تغییر فرمت ",
            "sourceColumn": "Amount",
            "formatString": "#,#"
          },
          {
            "name": "the_last_situation",
            "dataType": "string",
            "sourceColumn": "the_last_situation"
          },
          {
            "name": "Payment_request_number",
            "dataType": "string",
            "sourceColumn": "Payment_request_number"
          },
          {
            "name": "Accounting_document_number",
            "dataType": "string",
            "sourceColumn": "Accounting_document_number"
          },
          {
            "name": "payment_method",
            "dataType": "string",
            "sourceColumn": "payment_method"
          },
          {
            "name": "Description_how_to_pay",
            "dataType": "string",
            "sourceColumn": "Description_how_to_pay"
          },
          {
            "name": "Payment_To",
            "dataType": "string",
            "sourceColumn": "Payment_To"
          },
          {
            "name": "Description_payment",
            "dataType": "string",
            "sourceColumn": "Description_payment"
          },
          {
            "name": "for",
            "dataType": "string",
            "sourceColumn": "for"
          },
          {
            "name": "type_of_Document",
            "dataType": "string",
            "sourceColumn": "type_of_Document"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    NL_payment_report = Source{[Schema=\"NL\",Item=\"payment_report\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(NL_payment_report,\"ي\",\"ی\",Replacer.ReplaceText,{\"the_last_situation\", \"payment_method\", \"Description_how_to_pay\", \"Payment_To\", \"Description_payment\", \"for\", \"type_of_Document\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ]
      },
      {
        "name": "NL receipt_report",
        "description": "گزارش دریافت نیلرام ",
        "columns": [
          {
            "name": "Detailed_code_1",
            "dataType": "string",
            "sourceColumn": "Detailed_code_1"
          },
          {
            "name": "date_change_status",
            "dataType": "string",
            "sourceColumn": "date_change_status"
          },
          {
            "name": "history",
            "dataType": "string",
            "sourceColumn": "history"
          },
          {
            "name": "receiving_row",
            "dataType": "string",
            "sourceColumn": "receiving_row"
          },
          {
            "name": "receipt_number",
            "dataType": "string",
            "sourceColumn": "receipt_number"
          },
          {
            "name": "description_receipt",
            "dataType": "string",
            "sourceColumn": "description_receipt"
          },
          {
            "name": "Amount",
            "dataType": "int64",
            "description": "تغییر فرمت ",
            "sourceColumn": "Amount",
            "formatString": "#,#"
          },
          {
            "name": "Bank",
            "dataType": "string",
            "sourceColumn": "Bank"
          },
          {
            "name": "account_number",
            "dataType": "string",
            "sourceColumn": "account_number"
          },
          {
            "name": "Accounting_document_number",
            "dataType": "string",
            "sourceColumn": "Accounting_document_number"
          },
          {
            "name": "Branch",
            "dataType": "string",
            "sourceColumn": "Branch"
          },
          {
            "name": "cashier",
            "dataType": "string",
            "sourceColumn": "cashier"
          },
          {
            "name": "for",
            "dataType": "string",
            "sourceColumn": "for"
          },
          {
            "name": "The_nature_of_the_sale",
            "dataType": "string",
            "sourceColumn": "The_nature_of_the_sale"
          },
          {
            "name": "type_of_Document",
            "dataType": "string",
            "sourceColumn": "type_of_Document"
          },
          {
            "name": "row",
            "dataType": "int64",
            "sourceColumn": "row"
          },
          {
            "name": "receive_from",
            "dataType": "string",
            "sourceColumn": "receive_from"
          },
          {
            "name": "the_last_situation",
            "dataType": "string",
            "sourceColumn": "the_last_situation"
          },
          {
            "name": "the_document_number",
            "dataType": "string",
            "sourceColumn": "the_document_number"
          },
          {
            "name": "due_date",
            "dataType": "string",
            "sourceColumn": "due_date"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    NL_receipt_report = Source{[Schema=\"NL\",Item=\"receipt_report\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(NL_receipt_report,\"ي\",\"ی\",Replacer.ReplaceText,{\"description_receipt\", \"Bank\", \"Branch\", \"cashier\", \"for\", \"The_nature_of_the_sale\", \"type_of_Document\", \"receive_from\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ]
      },
      {
        "name": "NL Forecast_report",
        "columns": [
          {
            "name": "Year",
            "dataType": "string",
            "sourceColumn": "Year"
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month"
          },
          {
            "name": "budget",
            "dataType": "string",
            "sourceColumn": "budget"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "sourceColumn": "Amount"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    NL_Forecast_report = Source{[Schema=\"NL\",Item=\"Forecast_report\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(NL_Forecast_report,\"ي\",\"ی\",Replacer.ReplaceText,{\"budget\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Replaced Value\",{{\"Amount\", type number}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "001_Realization of program budget",
            "description": "تحقق بودجه برنامه ای برای BSC مالی نیلرام ",
            "expression": [
              " (CALCULATE(sum('NL payment_report'[Amount])/MAX('NL Forecast_report'[Amount]) ,",
              "                                          FILTER('NL Forecast_report', 'NL Forecast_report'[budget] = \"کل پرداخت های پیش بینی شده\"))) *100",
              "",
              "--  تحقق بودجه برنامه ای برای BSC مالی نیلرام "
            ]
          },
          {
            "name": "002_Realization of liquidity deficit",
            "description": " تحقق کسری نقدینگی برای BSC مالی نیلرام ",
            "expression": [
              " ",
              " (CALCULATE(sum('NL receipt_report'[Amount])",
              "                              /max('NL Forecast_report'[Amount]) ,",
              "                                          FILTER('NL Forecast_report', 'NL Forecast_report'[budget] = \"کل دریافت های پیش بینی شده\")))*100",
              "-- تحقق کسری نقدینگی برای BSC مالی نیلرام "
            ]
          }
        ]
      },
      {
        "name": "GA Google_Analytics",
        "description": "گزارش روزانه آنالیتیکس",
        "columns": [
          {
            "name": "date",
            "dataType": "string",
            "sourceColumn": "date"
          },
          {
            "name": "sessionDefaultChannelGroup",
            "dataType": "string",
            "sourceColumn": "sessionDefaultChannelGroup"
          },
          {
            "name": "totalUsers",
            "dataType": "int64",
            "sourceColumn": "totalUsers"
          },
          {
            "name": "engagementRate",
            "dataType": "double",
            "sourceColumn": "engagementRate",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "userEngagementDuration",
            "dataType": "double",
            "sourceColumn": "userEngagementDuration"
          },
          {
            "name": "dateRange",
            "dataType": "string",
            "sourceColumn": "dateRange"
          },
          {
            "name": "fromDate",
            "dataType": "dateTime",
            "sourceColumn": "fromDate"
          },
          {
            "name": "toDate",
            "dataType": "dateTime",
            "sourceColumn": "toDate"
          },
          {
            "name": "activeUsers",
            "dataType": "int64",
            "description": "#,#",
            "sourceColumn": "activeUsers"
          },
          {
            "name": "newUsers",
            "dataType": "int64",
            "description": "#,#",
            "sourceColumn": "newUsers"
          },
          {
            "name": "sessions",
            "dataType": "int64",
            "description": "#,#",
            "sourceColumn": "sessions"
          },
          {
            "name": "level",
            "dataType": "string",
            "sourceColumn": "level"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    GA_Google_Analytics = Source{[Schema=\"GA\",Item=\"Google_Analytics\"]}[Data]",
                "in",
                "    GA_Google_Analytics"
              ]
            }
          }
        ]
      },
      {
        "name": "GA Google_Search_Console_API",
        "description": "جدول اطلاعات google search api",
        "columns": [
          {
            "name": "date",
            "dataType": "dateTime",
            "description": "تاریخ",
            "sourceColumn": "date"
          },
          {
            "name": "country",
            "dataType": "string",
            "description": "کشور مبدا",
            "sourceColumn": "country"
          },
          {
            "name": "query",
            "dataType": "string",
            "description": "کلید واژه در نظر گرفته شده برای لینک",
            "sourceColumn": "query"
          },
          {
            "name": "clicks",
            "dataType": "int64",
            "description": "تعداد کلیلک ها",
            "sourceColumn": "clicks"
          },
          {
            "name": "impressions",
            "dataType": "int64",
            "description": "تعداد نمایش لینک توسط گوگل",
            "sourceColumn": "impressions"
          },
          {
            "name": "ctr",
            "dataType": "double",
            "description": "نسبت تعداد کلیلک به تعداد نمایش لینک توسط گوگل",
            "sourceColumn": "ctr"
          },
          {
            "name": "position",
            "dataType": "double",
            "description": "رتبه لینک در گوگل",
            "sourceColumn": "position"
          },
          {
            "name": "device",
            "dataType": "string",
            "description": "نوع دستگاه مورد استفاده برای ورود",
            "sourceColumn": "device"
          },
          {
            "name": "page",
            "dataType": "string",
            "description": "لینک صفحه وب مورد بررسی",
            "sourceColumn": "page"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    GA_Google_Search_Console_API = Source{[Schema=\"GA\",Item=\"Google_Search_Console_API\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(GA_Google_Search_Console_API,{{\"date\", type date}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"ي\",\"ی\",Replacer.ReplaceText,{\"query\", \"page\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Replaced Value\",{{\"date\", type date}})",
                "in",
                "    #\"Changed Type1\""
              ]
            }
          }
        ]
      },
      {
        "name": "GA Google_Analytics_month",
        "description": "گزارش ماهانه آنالیتیکس",
        "columns": [
          {
            "name": "dateRange",
            "dataType": "string",
            "sourceColumn": "dateRange"
          },
          {
            "name": "fromDate",
            "dataType": "dateTime",
            "sourceColumn": "fromDate"
          },
          {
            "name": "toDate",
            "dataType": "dateTime",
            "sourceColumn": "toDate"
          },
          {
            "name": "totalUsers",
            "dataType": "int64",
            "sourceColumn": "totalUsers",
            "formatString": "#,#"
          },
          {
            "name": "activeUsers",
            "dataType": "int64",
            "sourceColumn": "activeUsers",
            "formatString": "#,#"
          },
          {
            "name": "newUsers",
            "dataType": "int64",
            "sourceColumn": "newUsers"
          },
          {
            "name": "userEngagementDuration",
            "dataType": "double",
            "sourceColumn": "userEngagementDuration"
          },
          {
            "name": "engagementRate",
            "dataType": "double",
            "sourceColumn": "engagementRate",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "sessions",
            "dataType": "int64",
            "sourceColumn": "sessions",
            "formatString": "#,#"
          },
          {
            "name": "level",
            "dataType": "string",
            "sourceColumn": "level"
          },
          {
            "name": "sessionDefaultChannelGroup",
            "dataType": "string",
            "sourceColumn": "sessionDefaultChannelGroup"
          },
          {
            "name": "jyear",
            "dataType": "int64",
            "sourceColumn": "jyear"
          },
          {
            "name": "jmonthN",
            "dataType": "int64",
            "sourceColumn": "jmonthN"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    GA_Google_Analytics_month = Source{[Schema=\"GA\",Item=\"Google_Analytics_month\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(GA_Google_Analytics_month,{{\"jmonthN\", Int64.Type}, {\"jyear\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "VN Fact_Tour_detail",
        "description": "اطلاعات جزئیات تور ویزیت",
        "columns": [
          {
            "name": "Id",
            "dataType": "string",
            "sourceColumn": "Id"
          },
          {
            "name": "TourUniqueId",
            "dataType": "string",
            "sourceColumn": "TourUniqueId"
          },
          {
            "name": "CallPDate",
            "dataType": "string",
            "sourceColumn": "CallPDate"
          },
          {
            "name": "Longitude",
            "dataType": "double",
            "sourceColumn": "Longitude"
          },
          {
            "name": "Latitude",
            "dataType": "double",
            "sourceColumn": "Latitude"
          },
          {
            "name": "IsOutOfPath",
            "dataType": "boolean",
            "description": "مشتریان داخل و خارج از مسیر ",
            "sourceColumn": "IsOutOfPath"
          },
          {
            "name": "VisitStatus",
            "dataType": "string",
            "sourceColumn": "VisitStatus"
          },
          {
            "name": "CallStatus",
            "dataType": "string",
            "sourceColumn": "CallStatus"
          },
          {
            "name": "CustomerCode",
            "dataType": "string",
            "sourceColumn": "CustomerCode"
          },
          {
            "name": "NoSaleReasonName",
            "dataType": "string",
            "sourceColumn": "NoSaleReasonName"
          },
          {
            "name": "NoSaleReasonType",
            "dataType": "string",
            "sourceColumn": "NoSaleReasonType"
          },
          {
            "name": "time_duration_min",
            "dataType": "int64",
            "sourceColumn": "time_duration_min"
          },
          {
            "name": "unic_code",
            "dataType": "string",
            "sourceColumn": "unic_code"
          },
          {
            "type": "calculated",
            "name": "002_VisitTime",
            "dataType": "double",
            "isDataTypeInferred": true,
            "description": "محاسبه مدت تور به ساعت ",
            "expression": [
              "",
              "                          DIVIDE('VN Fact_Tour_detail'[time_duration_min],60)",
              "",
              "-- محاسبه مدت تور به ساعت ",
              "                           ",
              "                           "
            ]
          },
          {
            "name": "CityId",
            "dataType": "int64",
            "sourceColumn": "CityId"
          },
          {
            "name": "Start_date",
            "dataType": "string",
            "sourceColumn": "Start_date"
          },
          {
            "name": "Start_Time",
            "dataType": "string",
            "sourceColumn": "Start_Time"
          },
          {
            "name": "End_date",
            "dataType": "string",
            "sourceColumn": "End_date"
          },
          {
            "name": "End_Time",
            "dataType": "string",
            "sourceColumn": "End_Time"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    VN_Fact_Tour_detail = Source{[Schema=\"VN\",Item=\"Fact_Tour_detail\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(VN_Fact_Tour_detail,\"ي\",\"ی\",Replacer.ReplaceText,{\"VisitStatus\", \"CallStatus\", \"NoSaleReasonName\", \"NoSaleReasonType\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "001_TourVisit",
            "description": "تعداد ویزیت ",
            "expression": [
              "       ",
              "                var x = CALCULATE(DISTINCTCOUNT('VN Fact_Tour_detail'[CustomerCode]) , ",
              "                                   filter ('VN Fact_Tour_detail' , 'VN Fact_Tour_detail'[VisitStatus] = \"عدم ویزیت\")) -- تعداد عدم ویزیت",
              "",
              "",
              "",
              "              var y = CALCULATE(DISTINCTCOUNT('VN Fact_Tour_detail'[CustomerCode])) --تعداد کل مشتریان",
              "",
              "    return ",
              "              CALCULATE(  y-x) -- تعداد ویزیت "
            ]
          },
          {
            "name": "002_ min Start Time",
            "expression": [
              "",
              "                 MIN('VN Fact_Tour_detail'[Start_Time])",
              "",
              "-- کمترین زمان شروع تور "
            ]
          },
          {
            "name": "003_Max End Time",
            "description": "بیشترین ساعت پایان ",
            "expression": [
              "",
              "                 MIN('VN Fact_Tour_detail'[End_Time])",
              "",
              "-- بیشترین ساعت پایان "
            ]
          }
        ]
      },
      {
        "name": "VN Fact_Tour",
        "description": "اطلاعات کلی مربوط به تور ویزیت ",
        "columns": [
          {
            "name": "Id",
            "dataType": "string",
            "sourceColumn": "Id"
          },
          {
            "name": "TourPDate",
            "dataType": "string",
            "sourceColumn": "TourPDate"
          },
          {
            "name": "StartTime",
            "dataType": "dateTime",
            "sourceColumn": "StartTime"
          },
          {
            "name": "EndTime",
            "dataType": "dateTime",
            "sourceColumn": "EndTime"
          },
          {
            "name": "TourNo",
            "dataType": "int64",
            "sourceColumn": "TourNo"
          },
          {
            "name": "TourStatusUniqueId",
            "dataType": "string",
            "sourceColumn": "TourStatusUniqueId"
          },
          {
            "name": "PersonnelCode_agent",
            "dataType": "string",
            "sourceColumn": "PersonnelCode_agent"
          },
          {
            "name": "time_duration_min",
            "dataType": "int64",
            "sourceColumn": "time_duration_min"
          },
          {
            "type": "calculated",
            "name": "001_TourTime",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "description": "زمان ارسال تور",
            "expression": [
              " ",
              "            ",
              "        DATEDIFF('VN Fact_Tour'[StartTime], 'VN Fact_Tour'[EndTime],DAY)",
              "",
              "",
              "",
              "-- زمان ارسال تور "
            ]
          },
          {
            "name": "target_amount_per_day",
            "dataType": "double",
            "description": "تارگت روزانه ویزیتور",
            "sourceColumn": "target_amount_per_day",
            "formatString": "#,#"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    VN_Fact_Tour = Source{[Schema=\"VN\",Item=\"Fact_Tour\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(VN_Fact_Tour,\"ي\",\"ی\",Replacer.ReplaceText,{\"TourStatusUniqueId\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "001_ Visitor Target percentage",
            "expression": [
              " ",
              "                           ",
              "                               DIVIDE('VN Fact_Sale'[02_Amount] , sum('VN Fact_Tour'[target_amount_per_day]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "002__Daily Visitor Target",
            "description": "تارگت  روزانه ویزیتور",
            "expression": [
              " ",
              "                VAR Y = LOOKUPVALUE('BI DIM_DATE'[jyear], 'BI DIM_DATE'[Miladi], TODAY())",
              "                 ",
              "                 VAR m = LOOKUPVALUE('BI DIM_DATE'[jmonthN], 'BI DIM_DATE'[Miladi], TODAY())",
              "",
              "               VAR D = LOOKUPVALUE('BI DIM_DATE'[day], 'BI DIM_DATE'[Miladi], TODAY())",
              "",
              "        RETURN",
              "           CALCULATE(sum('VN Fact_Tour'[target_amount_per_day]),",
              "                                        'BI DIM_DATE'[jmonthN] = m , ",
              "                                                       'BI DIM_DATE'[jyear]= Y,",
              "                                                                   'BI DIM_DATE'[day]=d)  ",
              "",
              "--تارگت روزانه ویزیتور "
            ]
          },
          {
            "name": "003_Daily visitor Target",
            "description": "درصد تحقق روزانه ویزیتور ",
            "expression": [
              " ",
              "                  DIVIDE('VN Fact_Sale'[023_ Daily Amount],'VN Fact_Tour'[002__Daily Visitor Target])",
              "",
              "-- درصد تحقق روزانه ویزیتور"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "004_ MTD Target",
            "description": "تارگت ماه تا روز ویزیتور ",
            "expression": [
              " ",
              "                VAR Y = LOOKUPVALUE('BI DIM_DATE'[jyear], 'BI DIM_DATE'[Miladi], TODAY())",
              "                 ",
              "                 VAR m = LOOKUPVALUE('BI DIM_DATE'[jmonthN], 'BI DIM_DATE'[Miladi], TODAY())",
              "",
              "               VAR D = LOOKUPVALUE('BI DIM_DATE'[day], 'BI DIM_DATE'[Miladi], TODAY())",
              "",
              "        RETURN",
              "           CALCULATE(sum('VN Fact_Tour'[target_amount_per_day]),",
              "                                        'BI DIM_DATE'[jmonthN] = m , ",
              "                                                       'BI DIM_DATE'[jyear]= Y,",
              "                                                                   'BI DIM_DATE'[day]<=d)             ",
              "           ",
              "",
              "--تارگت ماه تا روز "
            ]
          },
          {
            "name": "005_MTD Visitor Target Percentage",
            "description": "درصد تحقق ماه تاروز ویزیتور ",
            "expression": [
              " ",
              "                    DIVIDE('VN Fact_Sale'[010_ MTD Amount] , 'VN Fact_Tour'[004_ MTD Target])",
              "",
              "-- درصد تحقق ماه تاروز ویزیتور "
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "NL personnel_HR",
        "columns": [
          {
            "name": "personnel number",
            "dataType": "string",
            "sourceColumn": "personnel number"
          },
          {
            "name": "name",
            "dataType": "string",
            "sourceColumn": "name"
          },
          {
            "name": "family name",
            "dataType": "string",
            "sourceColumn": "family name"
          },
          {
            "name": "employment_date",
            "dataType": "string",
            "sourceColumn": "employment_date"
          },
          {
            "name": "history",
            "dataType": "string",
            "sourceColumn": "history"
          },
          {
            "name": "gender",
            "dataType": "string",
            "sourceColumn": "gender"
          },
          {
            "name": "the unit",
            "dataType": "string",
            "sourceColumn": "the unit"
          },
          {
            "name": "Sub-unit 1",
            "dataType": "string",
            "sourceColumn": "Sub-unit 1"
          },
          {
            "name": "Sub-unit 2",
            "dataType": "string",
            "sourceColumn": "Sub-unit 2"
          },
          {
            "name": "Description of the organizational post",
            "dataType": "string",
            "sourceColumn": "Description of the organizational post"
          },
          {
            "name": "Organizational job",
            "dataType": "string",
            "sourceColumn": "Organizational job"
          },
          {
            "name": "employment_category",
            "dataType": "string",
            "sourceColumn": "employment_category"
          },
          {
            "name": "date_of_separation",
            "dataType": "string",
            "sourceColumn": "date_of_separation"
          },
          {
            "name": "Reason for separation",
            "dataType": "string",
            "sourceColumn": "Reason for separation"
          },
          {
            "name": "Educational certificate",
            "dataType": "string",
            "sourceColumn": "Educational certificate"
          },
          {
            "name": "Field of Study",
            "dataType": "string",
            "sourceColumn": "Field of Study"
          },
          {
            "name": "separation month",
            "dataType": "string",
            "sourceColumn": "separation month"
          },
          {
            "name": "year of separation",
            "dataType": "string",
            "sourceColumn": "year of separation"
          },
          {
            "name": "cost center",
            "dataType": "string",
            "sourceColumn": "cost center"
          },
          {
            "name": "002_Active or NotActive",
            "dataType": "string",
            "sourceColumn": "002_Active or NotActive"
          },
          {
            "name": "004_Miladi Employment Date",
            "dataType": "dateTime",
            "sourceColumn": "004_Miladi Employment Date"
          },
          {
            "name": "005_ Miladi Separation Date",
            "dataType": "dateTime",
            "sourceColumn": "005_ Miladi Separation Date"
          },
          {
            "name": "003_work experience",
            "dataType": "int64",
            "sourceColumn": "003_work experience"
          },
          {
            "name": "003_work experience_cat",
            "dataType": "string",
            "sourceColumn": "003_work experience_cat",
            "sortByColumn": "003_work experience_cat_No"
          },
          {
            "name": "003_work experience_cat_No",
            "dataType": "string",
            "sourceColumn": "003_work experience_cat_No"
          },
          {
            "name": "Date of birth",
            "dataType": "string",
            "sourceColumn": "Date of birth"
          },
          {
            "name": "Miladi Date of birth",
            "dataType": "dateTime",
            "sourceColumn": "Miladi Date of birth"
          },
          {
            "name": "age",
            "dataType": "int64",
            "sourceColumn": "age"
          },
          {
            "name": "age_cat",
            "dataType": "string",
            "sourceColumn": "age_cat",
            "sortByColumn": "age_cat_No"
          },
          {
            "name": "age_cat_No",
            "dataType": "string",
            "sourceColumn": "age_cat_No"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    NL_personnel_HR = Source{[Schema=\"NL\",Item=\"personnel_HR\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(NL_personnel_HR,\"ي\",\"ی\",Replacer.ReplaceText,{\"name\", \"family name\", \"the unit\", \"Sub-unit 1\", \"Sub-unit 2\", \"Description of the organizational post\", \"Organizational job\", \"employment_category\", \"Reason for separation\", \"Educational certificate\", \"Field of Study\", \"cost center\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"ي\",\"ی\",Replacer.ReplaceText,{\"003_work experience_cat\", \"age_cat\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Replaced Value1\", each not Text.StartsWith([personnel number], \"6000\"))",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "001_PersonelCount",
            "description": "تعداد پرسنل ",
            "expression": [
              " ",
              "                                       DISTINCTCOUNT('NL personnel_HR'[personnel number])",
              "                                       -- تعداد پرسنل "
            ]
          },
          {
            "name": "002_ CountPersonelInfirtPeriod",
            "description": "تعداد پرسنل اول دوره ",
            "expression": [
              " ",
              "           CALCULATE(DISTINCTCOUNT('NL personnel_HR_history'[personnel number]),",
              "                               FILTER('NL personnel_HR_history', 'NL personnel_HR_history'[status]=\"فعال\" &&",
              "                                             'NL personnel_HR_history'[type]<>\"استخدام\"))",
              "-- تعداد پرسنل اول دوره )"
            ]
          },
          {
            "name": "003_ CountPersonelendofPeriod",
            "description": "تعداد پرسنل آخر دوره ",
            "expression": [
              " ",
              "              CALCULATE(DISTINCTCOUNT('NL personnel_HR_history'[personnel number]),",
              "                    ",
              "                               FILTER('NL personnel_HR_history', 'NL personnel_HR_history'[status]=\"فعال\"))",
              "           -",
              "  CALCULATE(DISTINCTCOUNT('NL personnel_HR_history'[personnel number]),",
              "         ",
              "                               FILTER('NL personnel_HR_history',  'NL personnel_HR_history'[type]=\"خروج\")) ",
              "",
              "-- تعداد پرسنل آخر دوره "
            ]
          },
          {
            "name": "004_ExitRate",
            "description": "نرخ خروج پرسنل ",
            "expression": [
              " ",
              "        DIVIDE(   CALCULATE(DISTINCTCOUNT('NL personnel_HR_history'[personnel number]),",
              "         ",
              "                              FILTER('NL personnel_HR_history',  'NL personnel_HR_history'[type]=\"خروج\"))",
              "                       ,",
              "                 ('NL personnel_HR'[002_ CountPersonelInfirtPeriod]+'NL personnel_HR'[003_ CountPersonelendofPeriod])/2)",
              "",
              "",
              "--نرخ خروج پرسنل ",
              "                             ",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "oracle VW_BI_INS_PERSONEL",
        "columns": [
          {
            "name": "TYP",
            "dataType": "double",
            "sourceColumn": "TYP"
          },
          {
            "name": "TYP_DSC",
            "dataType": "string",
            "description": "نوع کارمندان ",
            "sourceColumn": "TYP_DSC"
          },
          {
            "name": "PRSL_UNIQUE",
            "dataType": "string",
            "sourceColumn": "PRSL_UNIQUE"
          },
          {
            "name": "NAME",
            "dataType": "string",
            "sourceColumn": "NAME"
          },
          {
            "name": "SEX",
            "dataType": "string",
            "sourceColumn": "SEX"
          },
          {
            "name": "ID_DAT",
            "dataType": "dateTime",
            "sourceColumn": "ID_DAT"
          },
          {
            "name": "CD_ASLI",
            "dataType": "int64",
            "description": "کد پرسنلی",
            "sourceColumn": "CD_ASLI"
          },
          {
            "name": "CD_FAREI",
            "dataType": "string",
            "sourceColumn": "CD_FAREI"
          },
          {
            "name": "PER_COM_CD",
            "dataType": "string",
            "sourceColumn": "PER_COM_CD"
          },
          {
            "name": "M_WAGE",
            "dataType": "double",
            "sourceColumn": "M_WAGE"
          },
          {
            "name": "MAIN_F_BK_CD",
            "dataType": "string",
            "sourceColumn": "MAIN_F_BK_CD"
          },
          {
            "name": "NUM_ID",
            "dataType": "string",
            "sourceColumn": "NUM_ID"
          },
          {
            "name": "PER_SODUR_LOC",
            "dataType": "string",
            "sourceColumn": "PER_SODUR_LOC"
          },
          {
            "name": "PER_LOG_GUID",
            "dataType": "string",
            "sourceColumn": "PER_LOG_GUID"
          },
          {
            "name": "L_SEMAT_CD",
            "dataType": "string",
            "description": "آخرین کد سمت سازمانی ",
            "sourceColumn": "L_SEMAT_CD"
          },
          {
            "name": "L_SEMAT_DSC",
            "dataType": "string",
            "description": "آخرین سمت سازمانی",
            "sourceColumn": "L_SEMAT_DSC"
          },
          {
            "name": "FROM_DATE",
            "dataType": "string",
            "description": "تاریخ شروع از ",
            "sourceColumn": "FROM_DATE"
          },
          {
            "name": "TO_DATE",
            "dataType": "string",
            "description": "تاریخ پایان ",
            "sourceColumn": "TO_DATE"
          },
          {
            "name": "L_RECP_CD",
            "dataType": "string",
            "sourceColumn": "L_RECP_CD"
          },
          {
            "name": "L_GROUP_CD",
            "dataType": "string",
            "sourceColumn": "L_GROUP_CD"
          },
          {
            "name": "L_CNR_CD",
            "dataType": "string",
            "sourceColumn": "L_CNR_CD"
          },
          {
            "name": "L_HOKM_GROUP",
            "dataType": "string",
            "description": "حکم",
            "sourceColumn": "L_HOKM_GROUP"
          },
          {
            "name": "LAST_HOKM",
            "dataType": "string",
            "sourceColumn": "LAST_HOKM"
          },
          {
            "name": "TABAGHE",
            "dataType": "double",
            "sourceColumn": "TABAGHE"
          },
          {
            "name": "JOB_CODE",
            "dataType": "string",
            "sourceColumn": "JOB_CODE"
          },
          {
            "name": "POST_STATUS",
            "dataType": "string",
            "description": "وضعیت حکم ",
            "sourceColumn": "POST_STATUS"
          },
          {
            "name": "LOC_ID",
            "dataType": "double",
            "sourceColumn": "LOC_ID"
          },
          {
            "name": "TABAGHE_DSC",
            "dataType": "string",
            "description": "سمت سازمانی",
            "sourceColumn": "TABAGHE_DSC"
          },
          {
            "name": "JOB_DSC",
            "dataType": "string",
            "description": "نوع شغل ",
            "sourceColumn": "JOB_DSC"
          },
          {
            "type": "calculated",
            "name": "001_StartDate",
            "dataType": "string",
            "isDataTypeInferred": true,
            "description": "تاریخ شمسی شروع به کار ",
            "expression": [
              "",
              "                LOOKUPVALUE('BI DIM_DATE'[Jalali_1],'BI DIM_DATE'[Miladi],'oracle VW_BI_INS_PERSONEL'[ID_DAT])"
            ]
          },
          {
            "type": "calculated",
            "name": "003_Active or NotActive Personel",
            "dataType": "string",
            "isDataTypeInferred": true,
            "description": "پرسنل فعال و غیر فعال",
            "expression": [
              "",
              "",
              "                                 IF('oracle VW_BI_INS_PERSONEL'[TO_DATE]  = BLANK(), \"فعال\" , \"غیر فعال\")",
              "",
              "--پرسنل فعال و غیر فعال"
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    oracle_VW_BI_INS_PERSONEL = Source{[Schema=\"oracle\",Item=\"VW_BI_INS_PERSONEL\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(oracle_VW_BI_INS_PERSONEL,\"ي\",\"ی\",Replacer.ReplaceText,{\"TYP_DSC\", \"NAME\", \"SEX\", \"MAIN_F_BK_CD\", \"L_SEMAT_DSC\", \"L_HOKM_GROUP\", \"LAST_HOKM\", \"POST_STATUS\", \"TABAGHE_DSC\", \"JOB_DSC\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Replaced Value\",{{\"ID_DAT\", type date}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "002_Number of Personel",
            "description": "تعداد کل پرسنل ",
            "expression": [
              "",
              "                           DISTINCTCOUNT('oracle VW_BI_INS_PERSONEL'[CD_ASLI])",
              "",
              "-- تعداد کل پرسنل "
            ],
            "formatString": "#,#"
          }
        ]
      },
      {
        "name": "PA Hokm",
        "columns": [
          {
            "name": "HokmId",
            "dataType": "string",
            "sourceColumn": "HokmId"
          },
          {
            "name": "HokmNo",
            "dataType": "int64",
            "sourceColumn": "HokmNo"
          },
          {
            "name": "IssueDate",
            "dataType": "string",
            "sourceColumn": "IssueDate"
          },
          {
            "name": "EffectiveDate",
            "dataType": "string",
            "sourceColumn": "EffectiveDate"
          },
          {
            "name": "AccountNo",
            "dataType": "string",
            "sourceColumn": "AccountNo"
          },
          {
            "name": "StartWorkDate",
            "dataType": "string",
            "sourceColumn": "StartWorkDate"
          },
          {
            "name": "EndWorkDate",
            "dataType": "string",
            "sourceColumn": "EndWorkDate"
          },
          {
            "name": "ContractStartDate",
            "dataType": "string",
            "sourceColumn": "ContractStartDate"
          },
          {
            "name": "ContractEndDate",
            "dataType": "string",
            "sourceColumn": "ContractEndDate"
          },
          {
            "name": "EndDate",
            "dataType": "string",
            "sourceColumn": "EndDate"
          },
          {
            "name": "PersonnelInfoId",
            "dataType": "int64",
            "sourceColumn": "PersonnelInfoId"
          },
          {
            "name": "IsActive",
            "dataType": "boolean",
            "sourceColumn": "IsActive"
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description"
          },
          {
            "name": "OrgChartId",
            "dataType": "int64",
            "sourceColumn": "OrgChartId"
          },
          {
            "name": "OrgLocationId",
            "dataType": "int64",
            "sourceColumn": "OrgLocationId"
          },
          {
            "name": "PostPostTitle",
            "dataType": "string",
            "sourceColumn": "PostPostTitle"
          },
          {
            "name": "CostCenterTitle",
            "dataType": "string",
            "sourceColumn": "CostCenterTitle"
          },
          {
            "name": "EmploymentTypeName",
            "dataType": "string",
            "sourceColumn": "EmploymentTypeName"
          },
          {
            "name": "InsuranceTypeName",
            "dataType": "string",
            "sourceColumn": "InsuranceTypeName"
          },
          {
            "name": "HokmTypeName",
            "dataType": "string",
            "sourceColumn": "HokmTypeName"
          },
          {
            "name": "HokmMainTypeName",
            "dataType": "string",
            "sourceColumn": "HokmMainTypeName"
          },
          {
            "name": "JobInfoTitle",
            "dataType": "string",
            "sourceColumn": "JobInfoTitle"
          },
          {
            "name": "EmploymentStatusTypeName",
            "dataType": "string",
            "sourceColumn": "EmploymentStatusTypeName"
          },
          {
            "name": "TaxCalculationTypeName",
            "dataType": "string",
            "sourceColumn": "TaxCalculationTypeName"
          },
          {
            "name": "OrgChartName",
            "dataType": "string",
            "sourceColumn": "OrgChartName"
          },
          {
            "name": "HokmStatusName",
            "dataType": "string",
            "sourceColumn": "HokmStatusName"
          },
          {
            "name": "OrgLocationTitle",
            "dataType": "string",
            "sourceColumn": "OrgLocationTitle"
          },
          {
            "name": "WorkingCalendarName",
            "dataType": "string",
            "sourceColumn": "WorkingCalendarName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    PA_Hokm = Source{[Schema=\"PA\",Item=\"Hokm\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(PA_Hokm,\"ي\",\"ی\",Replacer.ReplaceValue,{\"HokmId\", \"Description\", \"PostPostTitle\", \"CostCenterTitle\", \"EmploymentTypeName\", \"InsuranceTypeName\", \"HokmTypeName\", \"HokmMainTypeName\", \"JobInfoTitle\", \"EmploymentStatusTypeName\", \"TaxCalculationTypeName\", \"OrgChartName\", \"HokmStatusName\", \"OrgLocationTitle\", \"WorkingCalendarName\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ]
      },
      {
        "name": "PA MonthlySalary",
        "columns": [
          {
            "name": "CalculationPeriodId",
            "dataType": "int64",
            "sourceColumn": "CalculationPeriodId"
          },
          {
            "name": "PersonnelInfoId",
            "dataType": "int64",
            "sourceColumn": "PersonnelInfoId"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year"
          },
          {
            "name": "Month",
            "dataType": "int64",
            "sourceColumn": "Month"
          },
          {
            "name": "LastHokmId",
            "dataType": "int64",
            "sourceColumn": "LastHokmId"
          },
          {
            "name": "OrgChartId",
            "dataType": "int64",
            "sourceColumn": "OrgChartId"
          },
          {
            "name": "WSEidiVaSanavat_DArsadMAliat",
            "dataType": "int64",
            "sourceColumn": "WSEidiVaSanavat_DArsadMAliat"
          },
          {
            "name": "WSEidiVaSanavat_TedadRozEidi",
            "dataType": "int64",
            "sourceColumn": "WSEidiVaSanavat_TedadRozEidi"
          },
          {
            "name": "TedadRoozSanavat",
            "dataType": "int64",
            "sourceColumn": "TedadRoozSanavat"
          },
          {
            "name": "MandeMorakhasi",
            "dataType": "string",
            "sourceColumn": "MandeMorakhasi"
          },
          {
            "name": "KhalessanavatKhedmat",
            "dataType": "double",
            "sourceColumn": "KhalessanavatKhedmat"
          },
          {
            "name": "LastHokmNo",
            "dataType": "string",
            "sourceColumn": "LastHokmNo"
          },
          {
            "name": "JameKosooratMostamer",
            "dataType": "int64",
            "sourceColumn": "JameKosooratMostamer"
          },
          {
            "name": "JameMazayayeMostamer",
            "dataType": "int64",
            "sourceColumn": "JameMazayayeMostamer"
          },
          {
            "name": "JameKosourateGheyreMostamer",
            "dataType": "int64",
            "sourceColumn": "JameKosourateGheyreMostamer"
          },
          {
            "name": "JameMazayayeGheiremostamar1",
            "dataType": "int64",
            "sourceColumn": "JameMazayayeGheiremostamar1"
          },
          {
            "name": "JameHoghoghMazaya1",
            "dataType": "int64",
            "sourceColumn": "JameHoghoghMazaya1"
          },
          {
            "name": "JameKosour",
            "dataType": "int64",
            "sourceColumn": "JameKosour"
          },
          {
            "name": "KhalesPardakhtHoghoghKol",
            "dataType": "int64",
            "sourceColumn": "KhalesPardakhtHoghoghKol"
          },
          {
            "name": "ShomarehHesab",
            "dataType": "string",
            "sourceColumn": "ShomarehHesab"
          },
          {
            "name": "JamTahodateKarfarma",
            "dataType": "int64",
            "sourceColumn": "JamTahodateKarfarma"
          },
          {
            "name": "JameMazayayeMostamer2",
            "dataType": "int64",
            "sourceColumn": "JameMazayayeMostamer2"
          },
          {
            "name": "JameMazayayeMostamerKol",
            "dataType": "int64",
            "sourceColumn": "JameMazayayeMostamerKol"
          },
          {
            "name": "JameMazayayeGheiremostamar2",
            "dataType": "int64",
            "sourceColumn": "JameMazayayeGheiremostamar2"
          },
          {
            "name": "JameMazayayeGheiremostamarKol",
            "dataType": "int64",
            "sourceColumn": "JameMazayayeGheiremostamarKol"
          },
          {
            "name": "JameHoghoghMazaya2",
            "dataType": "int64",
            "sourceColumn": "JameHoghoghMazaya2"
          },
          {
            "name": "JameHoghoghMazayaKol",
            "dataType": "int64",
            "sourceColumn": "JameHoghoghMazayaKol"
          },
          {
            "name": "JameKosourateGheyreMostamer2",
            "dataType": "int64",
            "sourceColumn": "JameKosourateGheyreMostamer2"
          },
          {
            "name": "JameKosourateGheyreMostamerKol",
            "dataType": "int64",
            "sourceColumn": "JameKosourateGheyreMostamerKol"
          },
          {
            "name": "JameKosour2",
            "dataType": "int64",
            "sourceColumn": "JameKosour2"
          },
          {
            "name": "JameKosourKol",
            "dataType": "int64",
            "sourceColumn": "JameKosourKol"
          },
          {
            "name": "KhalesPardakhtHoghogh1",
            "dataType": "int64",
            "sourceColumn": "KhalesPardakhtHoghogh1"
          },
          {
            "name": "KhalesPardakhtHoghogh2",
            "dataType": "int64",
            "sourceColumn": "KhalesPardakhtHoghogh2"
          },
          {
            "name": "Ezafehkar",
            "dataType": "string",
            "sourceColumn": "Ezafehkar"
          },
          {
            "name": "takhir",
            "dataType": "string",
            "sourceColumn": "takhir"
          },
          {
            "name": "roozkarkard",
            "dataType": "int64",
            "sourceColumn": "roozkarkard"
          },
          {
            "name": "roozemamooriyat",
            "dataType": "int64",
            "sourceColumn": "roozemamooriyat"
          },
          {
            "name": "roozegheybat",
            "dataType": "int64",
            "sourceColumn": "roozegheybat"
          },
          {
            "name": "roozebimari",
            "dataType": "int64",
            "sourceColumn": "roozebimari"
          },
          {
            "name": "TedadRozEidi",
            "dataType": "int64",
            "sourceColumn": "TedadRozEidi"
          },
          {
            "name": "TedadRoozSanavat2",
            "dataType": "int64",
            "sourceColumn": "TedadRoozSanavat2"
          },
          {
            "name": "MandeMorakhasi2",
            "dataType": "string",
            "sourceColumn": "MandeMorakhasi2"
          },
          {
            "name": "KarkardTatilKari",
            "dataType": "string",
            "sourceColumn": "KarkardTatilKari"
          },
          {
            "name": "KarkardShabKari",
            "dataType": "string",
            "sourceColumn": "KarkardShabKari"
          },
          {
            "name": "MandemorakhasiManfi",
            "dataType": "string",
            "sourceColumn": "MandemorakhasiManfi"
          },
          {
            "name": "SalaryHagheOlad",
            "dataType": "double",
            "sourceColumn": "SalaryHagheOlad"
          },
          {
            "name": "BasesSalary",
            "dataType": "double",
            "sourceColumn": "BasesSalary"
          },
          {
            "name": "SalaryHagheMaskan",
            "dataType": "double",
            "sourceColumn": "SalaryHagheMaskan"
          },
          {
            "name": "TedadRoozEstandardMah",
            "dataType": "double",
            "sourceColumn": "TedadRoozEstandardMah"
          },
          {
            "name": "EsPayeHoghogh",
            "dataType": "double",
            "sourceColumn": "EsPayeHoghogh"
          },
          {
            "name": "FeeKarkard",
            "dataType": "int64",
            "sourceColumn": "FeeKarkard"
          },
          {
            "name": "EsHagheOlad",
            "dataType": "double",
            "sourceColumn": "EsHagheOlad"
          },
          {
            "name": "EsHagheMaskan",
            "dataType": "double",
            "sourceColumn": "EsHagheMaskan"
          },
          {
            "name": "EsBonNaghdi",
            "dataType": "double",
            "sourceColumn": "EsBonNaghdi"
          },
          {
            "name": "EsPayeSanavat",
            "dataType": "double",
            "sourceColumn": "EsPayeSanavat"
          },
          {
            "name": "SalaryBonKargari",
            "dataType": "double",
            "sourceColumn": "SalaryBonKargari"
          },
          {
            "name": "SalaryPayeSanavat",
            "dataType": "double",
            "sourceColumn": "SalaryPayeSanavat"
          },
          {
            "name": "SalaryCBD3",
            "dataType": "double",
            "sourceColumn": "SalaryCBD3"
          },
          {
            "name": "ESCBD3",
            "dataType": "double",
            "sourceColumn": "ESCBD3"
          },
          {
            "name": "ESCBD1",
            "dataType": "double",
            "sourceColumn": "ESCBD1"
          },
          {
            "name": "ESCBD2",
            "dataType": "double",
            "sourceColumn": "ESCBD2"
          },
          {
            "name": "SalaryCBD1",
            "dataType": "double",
            "sourceColumn": "SalaryCBD1"
          },
          {
            "name": "SalaryCBD2",
            "dataType": "double",
            "sourceColumn": "SalaryCBD2"
          },
          {
            "name": "PadashMahaneh",
            "dataType": "double",
            "sourceColumn": "PadashMahaneh"
          },
          {
            "name": "SaatKareMahaneh",
            "dataType": "double",
            "sourceColumn": "SaatKareMahaneh"
          },
          {
            "name": "ZaribEzafehkariAddi",
            "dataType": "double",
            "sourceColumn": "ZaribEzafehkariAddi"
          },
          {
            "name": "NCBenefit",
            "dataType": "int64",
            "sourceColumn": "NCBenefit"
          },
          {
            "name": "NCBenefit2",
            "dataType": "int64",
            "sourceColumn": "NCBenefit2"
          },
          {
            "name": "NCBenefit3",
            "dataType": "int64",
            "sourceColumn": "NCBenefit3"
          },
          {
            "name": "NCBenefit4",
            "dataType": "int64",
            "sourceColumn": "NCBenefit4"
          },
          {
            "name": "PourSant",
            "dataType": "double",
            "sourceColumn": "PourSant"
          },
          {
            "name": "EzafekareSabet",
            "dataType": "double",
            "sourceColumn": "EzafekareSabet"
          },
          {
            "name": "HoghogheMoavagheh",
            "dataType": "double",
            "sourceColumn": "HoghogheMoavagheh"
          },
          {
            "name": "SalaryEzafehkar",
            "dataType": "double",
            "sourceColumn": "SalaryEzafehkar"
          },
          {
            "name": "SalaryMamooriyat",
            "dataType": "double",
            "sourceColumn": "SalaryMamooriyat"
          },
          {
            "name": "EsSaatEzafehKar",
            "dataType": "double",
            "sourceColumn": "EsSaatEzafehKar"
          },
          {
            "name": "EsRoozeMamooriyat",
            "dataType": "int64",
            "sourceColumn": "EsRoozeMamooriyat"
          },
          {
            "name": "HoghogheMabna2",
            "dataType": "double",
            "sourceColumn": "HoghogheMabna2"
          },
          {
            "name": "EsShabkari",
            "dataType": "double",
            "sourceColumn": "EsShabkari"
          },
          {
            "name": "ZaribTatilKari",
            "dataType": "double",
            "sourceColumn": "ZaribTatilKari"
          },
          {
            "name": "EsKarkardTatilkari",
            "dataType": "double",
            "sourceColumn": "EsKarkardTatilkari"
          },
          {
            "name": "TatilKari",
            "dataType": "double",
            "sourceColumn": "TatilKari"
          },
          {
            "name": "ZaribShabKari",
            "dataType": "double",
            "sourceColumn": "ZaribShabKari"
          },
          {
            "name": "ShabKari",
            "dataType": "double",
            "sourceColumn": "ShabKari"
          },
          {
            "name": "HagheNahar",
            "dataType": "double",
            "sourceColumn": "HagheNahar"
          },
          {
            "name": "HagheBimehBikari",
            "dataType": "double",
            "sourceColumn": "HagheBimehBikari"
          },
          {
            "name": "HagheBimehSahmeKarfarma",
            "dataType": "double",
            "sourceColumn": "HagheBimehSahmeKarfarma"
          },
          {
            "name": "TedadMahePardakhteHoghoogh",
            "dataType": "int64",
            "sourceColumn": "TedadMahePardakhteHoghoogh"
          },
          {
            "name": "JameDaramadeMashmooleBimeh",
            "dataType": "double",
            "sourceColumn": "JameDaramadeMashmooleBimeh"
          },
          {
            "name": "JameDaramdeMashmooleMaliyat",
            "dataType": "double",
            "sourceColumn": "JameDaramdeMashmooleMaliyat"
          },
          {
            "name": "SaghfeMashmooleBimeh",
            "dataType": "double",
            "sourceColumn": "SaghfeMashmooleBimeh"
          },
          {
            "name": "DaramadeMashmooleMaliyateMah",
            "dataType": "double",
            "sourceColumn": "DaramadeMashmooleMaliyateMah"
          },
          {
            "name": "BimeTaminEjtemai",
            "dataType": "double",
            "sourceColumn": "BimeTaminEjtemai"
          },
          {
            "name": "ZaribBimehSahmeKarmand",
            "dataType": "double",
            "sourceColumn": "ZaribBimehSahmeKarmand"
          },
          {
            "name": "SystemInitialDataTaxBaseIncomeYTD",
            "dataType": "double",
            "sourceColumn": "SystemInitialDataTaxBaseIncomeYTD"
          },
          {
            "name": "SystemInitialDataMonthlyPresence",
            "dataType": "int64",
            "sourceColumn": "SystemInitialDataMonthlyPresence"
          },
          {
            "name": "MonthlyPresence",
            "dataType": "int64",
            "sourceColumn": "MonthlyPresence"
          },
          {
            "name": "KolDaramdeMashmooleMaliyat",
            "dataType": "double",
            "sourceColumn": "KolDaramdeMashmooleMaliyat"
          },
          {
            "name": "PaidMonthTax",
            "dataType": "double",
            "sourceColumn": "PaidMonthTax"
          },
          {
            "name": "PaidMaliyatFromStartOfYear",
            "dataType": "double",
            "sourceColumn": "PaidMaliyatFromStartOfYear"
          },
          {
            "name": "ZaribBimehSahmeKarfarma",
            "dataType": "double",
            "sourceColumn": "ZaribBimehSahmeKarfarma"
          },
          {
            "name": "ZaribBimehBikari",
            "dataType": "double",
            "sourceColumn": "ZaribBimehBikari"
          },
          {
            "name": "HoghoghMazayayeMostamarMashmolMaliyat",
            "dataType": "double",
            "sourceColumn": "HoghoghMazayayeMostamarMashmolMaliyat"
          },
          {
            "name": "MazayayeGheyreMostamareMashmolMaliyat",
            "dataType": "double",
            "sourceColumn": "MazayayeGheyreMostamareMashmolMaliyat"
          },
          {
            "name": "JameHagheBimeh",
            "dataType": "double",
            "sourceColumn": "JameHagheBimeh"
          },
          {
            "name": "MaliyatTaklifi",
            "dataType": "double",
            "sourceColumn": "MaliyatTaklifi"
          },
          {
            "name": "MoafiatTaminEjtemaiMaliat",
            "dataType": "double",
            "sourceColumn": "MoafiatTaminEjtemaiMaliat"
          },
          {
            "name": "TedadRoozKarkardSalaneh",
            "dataType": "int64",
            "sourceColumn": "TedadRoozKarkardSalaneh"
          },
          {
            "name": "SaatKareMahaneh3",
            "dataType": "double",
            "sourceColumn": "SaatKareMahaneh3"
          },
          {
            "name": "ZaribeTakhir",
            "dataType": "double",
            "sourceColumn": "ZaribeTakhir"
          },
          {
            "name": "Mosaedeh",
            "dataType": "double",
            "sourceColumn": "Mosaedeh"
          },
          {
            "name": "KasreTankhah",
            "dataType": "double",
            "sourceColumn": "KasreTankhah"
          },
          {
            "name": "NCDefecit1",
            "dataType": "int64",
            "sourceColumn": "NCDefecit1"
          },
          {
            "name": "NCDefecit2",
            "dataType": "int64",
            "sourceColumn": "NCDefecit2"
          },
          {
            "name": "NCDefecit3",
            "dataType": "int64",
            "sourceColumn": "NCDefecit3"
          },
          {
            "name": "NCDefecit4",
            "dataType": "int64",
            "sourceColumn": "NCDefecit4"
          },
          {
            "name": "AlalHesabPorsant",
            "dataType": "double",
            "sourceColumn": "AlalHesabPorsant"
          },
          {
            "name": "JarimeHoghogh",
            "dataType": "double",
            "sourceColumn": "JarimeHoghogh"
          },
          {
            "name": "HoghogheMabna",
            "dataType": "double",
            "sourceColumn": "HoghogheMabna"
          },
          {
            "name": "EsSaatTakhir",
            "dataType": "double",
            "sourceColumn": "EsSaatTakhir"
          },
          {
            "name": "JarimehTakhir",
            "dataType": "double",
            "sourceColumn": "JarimehTakhir"
          },
          {
            "name": "RemainSavingType227",
            "dataType": "double",
            "sourceColumn": "RemainSavingType227"
          },
          {
            "name": "KharidPersoneli",
            "dataType": "double",
            "sourceColumn": "KharidPersoneli"
          },
          {
            "name": "SavingType1091",
            "dataType": "int64",
            "sourceColumn": "SavingType1091"
          },
          {
            "name": "LoanType1092",
            "dataType": "double",
            "sourceColumn": "LoanType1092"
          },
          {
            "name": "LoanType1093",
            "dataType": "double",
            "sourceColumn": "LoanType1093"
          },
          {
            "name": "LoanType1094",
            "dataType": "double",
            "sourceColumn": "LoanType1094"
          },
          {
            "name": "RemineLoanType1092",
            "dataType": "double",
            "sourceColumn": "RemineLoanType1092"
          },
          {
            "name": "RemineLoanType1093",
            "dataType": "double",
            "sourceColumn": "RemineLoanType1093"
          },
          {
            "name": "RemineLoanType1094",
            "dataType": "double",
            "sourceColumn": "RemineLoanType1094"
          },
          {
            "name": "EsSaatMandeMorakhasiManfi",
            "dataType": "double",
            "sourceColumn": "EsSaatMandeMorakhasiManfi"
          },
          {
            "name": "MandemorakhasiManfi2",
            "dataType": "string",
            "sourceColumn": "MandemorakhasiManfi2"
          },
          {
            "name": "JarimehMorakhasi",
            "dataType": "double",
            "sourceColumn": "JarimehMorakhasi"
          },
          {
            "name": "LoanType90069",
            "dataType": "double",
            "sourceColumn": "LoanType90069"
          },
          {
            "name": "RemainLoanType90069",
            "dataType": "double",
            "sourceColumn": "RemainLoanType90069"
          },
          {
            "name": "HaddeaghaDastmozdeMahaneh",
            "dataType": "double",
            "sourceColumn": "HaddeaghaDastmozdeMahaneh"
          },
          {
            "name": "SaatKareMahaneh2",
            "dataType": "double",
            "sourceColumn": "SaatKareMahaneh2"
          },
          {
            "name": "WSEidiVaSanavat_",
            "dataType": "double",
            "sourceColumn": "WSEidiVaSanavat_"
          },
          {
            "name": "KarkardMohasebatiEidiVaSanavatSalaneh",
            "dataType": "int64",
            "sourceColumn": "KarkardMohasebatiEidiVaSanavatSalaneh"
          },
          {
            "name": "MoafiatMaliatEidi",
            "dataType": "double",
            "sourceColumn": "MoafiatMaliatEidi"
          },
          {
            "name": "KhalesEidi",
            "dataType": "int64",
            "sourceColumn": "KhalesEidi"
          },
          {
            "name": "MandeMorakhasiMotealeghe",
            "dataType": "double",
            "sourceColumn": "MandeMorakhasiMotealeghe"
          },
          {
            "name": "TarkKar",
            "dataType": "int64",
            "sourceColumn": "TarkKar"
          },
          {
            "name": "SanavatKhedmat",
            "dataType": "double",
            "sourceColumn": "SanavatKhedmat"
          },
          {
            "name": "EidiMotealeghe",
            "dataType": "int64",
            "sourceColumn": "EidiMotealeghe"
          },
          {
            "name": "KarkardSanavat",
            "dataType": "int64",
            "sourceColumn": "KarkardSanavat"
          },
          {
            "name": "KarkardEidi",
            "dataType": "int64",
            "sourceColumn": "KarkardEidi"
          },
          {
            "name": "MaliatEidi",
            "dataType": "int64",
            "sourceColumn": "MaliatEidi"
          },
          {
            "name": "MandeMorakhasiMohasebati",
            "dataType": "double",
            "sourceColumn": "MandeMorakhasiMohasebati"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    PA_MonthlySalary = Source{[Schema=\"PA\",Item=\"MonthlySalary\"]}[Data]",
                "in",
                "    PA_MonthlySalary"
              ]
            }
          }
        ]
      },
      {
        "name": "PA OrgChar",
        "columns": [
          {
            "name": "OrgChartId_Level1",
            "dataType": "int64",
            "sourceColumn": "OrgChartId_Level1"
          },
          {
            "name": "OrgChartName_Level1",
            "dataType": "string",
            "sourceColumn": "OrgChartName_Level1"
          },
          {
            "name": "OrgChartId_Level2",
            "dataType": "int64",
            "sourceColumn": "OrgChartId_Level2"
          },
          {
            "name": "OrgChartName_Level2",
            "dataType": "string",
            "sourceColumn": "OrgChartName_Level2"
          },
          {
            "name": "OrgChartId_Level3",
            "dataType": "int64",
            "sourceColumn": "OrgChartId_Level3"
          },
          {
            "name": "OrgChartName_Level3",
            "dataType": "string",
            "sourceColumn": "OrgChartName_Level3"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    PA_OrgChar = Source{[Schema=\"PA\",Item=\"OrgChar\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(PA_OrgChar,\"ي\",\"ی\",Replacer.ReplaceText,{\"OrgChartName_Level1\", \"OrgChartName_Level2\", \"OrgChartName_Level3\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ]
      },
      {
        "name": "PA PersonnelInfo",
        "columns": [
          {
            "name": "PersonnelInfoId",
            "dataType": "int64",
            "sourceColumn": "PersonnelInfoId"
          },
          {
            "name": "PersonnelInfoCode",
            "dataType": "string",
            "sourceColumn": "PersonnelInfoCode"
          },
          {
            "name": "FatherName",
            "dataType": "string",
            "sourceColumn": "FatherName"
          },
          {
            "name": "IdNo",
            "dataType": "string",
            "sourceColumn": "IdNo"
          },
          {
            "name": "NationalCode",
            "dataType": "string",
            "sourceColumn": "NationalCode"
          },
          {
            "name": "DLId",
            "dataType": "int64",
            "sourceColumn": "DLId"
          },
          {
            "name": "Birthday",
            "dataType": "string",
            "sourceColumn": "Birthday"
          },
          {
            "name": "InsuranceNo",
            "dataType": "string",
            "sourceColumn": "InsuranceNo"
          },
          {
            "name": "PersonnelInfoStatusTypeName",
            "dataType": "string",
            "sourceColumn": "PersonnelInfoStatusTypeName"
          },
          {
            "name": "UnderSupportChildernCountTypeName",
            "dataType": "string",
            "sourceColumn": "UnderSupportChildernCountTypeName"
          },
          {
            "name": "FieldStudyName",
            "dataType": "string",
            "sourceColumn": "FieldStudyName"
          },
          {
            "name": "EducationalDegreeTypeName",
            "dataType": "string",
            "sourceColumn": "EducationalDegreeTypeName"
          },
          {
            "name": "NationalityTypeName",
            "dataType": "string",
            "sourceColumn": "NationalityTypeName"
          },
          {
            "name": "MaritalStatusTypeName",
            "dataType": "string",
            "sourceColumn": "MaritalStatusTypeName"
          },
          {
            "name": "ReligionName",
            "dataType": "string",
            "sourceColumn": "ReligionName"
          },
          {
            "name": "GenderTypeName",
            "dataType": "string",
            "sourceColumn": "GenderTypeName"
          },
          {
            "name": "BirthCity_name",
            "dataType": "string",
            "sourceColumn": "BirthCity_name"
          },
          {
            "name": "IssueCity_name",
            "dataType": "string",
            "sourceColumn": "IssueCity_name"
          },
          {
            "name": "fullname",
            "dataType": "string",
            "sourceColumn": "fullname"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    PA_PersonnelInfo = Source{[Schema=\"PA\",Item=\"PersonnelInfo\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(PA_PersonnelInfo,\"ي\",\"ی\",Replacer.ReplaceText,{\"FatherName\", \"PersonnelInfoStatusTypeName\", \"EducationalDegreeTypeName\", \"NationalityTypeName\", \"MaritalStatusTypeName\", \"ReligionName\", \"GenderTypeName\", \"BirthCity_name\", \"IssueCity_name\", \"fullname\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ]
      },
      {
        "name": "BI dollar_price",
        "columns": [
          {
            "name": "open_price",
            "dataType": "int64",
            "sourceColumn": "open_price"
          },
          {
            "name": "low_price",
            "dataType": "int64",
            "sourceColumn": "low_price"
          },
          {
            "name": "high_price",
            "dataType": "int64",
            "sourceColumn": "high_price"
          },
          {
            "name": "close_price",
            "dataType": "int64",
            "description": "#,#",
            "sourceColumn": "close_price"
          },
          {
            "name": "miladi_date",
            "dataType": "string",
            "sourceColumn": "miladi_date"
          },
          {
            "name": "jalali_date",
            "dataType": "string",
            "sourceColumn": "jalali_date"
          },
          {
            "name": "change%",
            "dataType": "string",
            "sourceColumn": "change%"
          },
          {
            "name": "change",
            "dataType": "string",
            "sourceColumn": "change"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    BI_dollar_price = Source{[Schema=\"BI\",Item=\"dollar_price\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(BI_dollar_price,{{\"close_price\", Int64.Type}, {\"high_price\", Int64.Type}, {\"low_price\", Int64.Type}, {\"open_price\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "001_ maxClose Price_Dollar",
            "description": "ماکزیمم قیمت دلار ",
            "expression": [
              "",
              "                      AVERAGE('BI dollar_price'[close_price])",
              "",
              "--- ماکزیمم قیمت دلار "
            ],
            "formatString": "#,#"
          }
        ]
      },
      {
        "name": "NL personnel_HR_history",
        "columns": [
          {
            "name": "unic_code",
            "dataType": "string",
            "sourceColumn": "unic_code"
          },
          {
            "name": "personnel number",
            "dataType": "string",
            "sourceColumn": "personnel number"
          },
          {
            "name": "status",
            "dataType": "string",
            "sourceColumn": "status"
          },
          {
            "name": "type",
            "dataType": "string",
            "sourceColumn": "type"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    NL_personnel_HR_history = Source{[Schema=\"NL\",Item=\"personnel_HR_history\"]}[Data]",
                "in",
                "    NL_personnel_HR_history"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "001_PersonelCount(History)",
            "description": "تعداد پرسنل ",
            "expression": [
              " ",
              "                                       DISTINCTCOUNT('NL personnel_HR'[personnel number])",
              "                                       -- تعداد پرسنل "
            ]
          },
          {
            "name": "002_ Number of employed personnel",
            "description": "تعداد پرسنل استخدام شده ",
            "expression": [
              " ",
              "       CALCULATE(  DISTINCTCOUNT('NL personnel_HR_history'[personnel number]), ",
              "          FILTER('NL personnel_HR_history' , 'NL personnel_HR_history'[type] = \"استخدام\"))",
              "",
              "-- تعداد پرسنل استخدامی "
            ]
          },
          {
            "name": "003_ The number of personnel left",
            "description": "تعداد پرسنل خارج شده",
            "expression": [
              " ",
              "       CALCULATE(  DISTINCTCOUNT('NL personnel_HR_history'[personnel number]), ",
              "          FILTER('NL personnel_HR_history' , 'NL personnel_HR_history'[type] = \"خروج\"))",
              "",
              "-- تعداد پرسنل خارج شده"
            ]
          },
          {
            "name": "004_Active Persobel",
            "expression": [
              " 1",
              "       /*             var monthh = MONTH(TODAY())",
              "                    var selectt = SELECTEDVALUE('NL personnel_HR_history'[type])",
              "",
              "return ",
              "",
              "    CALCULATE(selectt = \"فعال\",",
              "                     DISTINCTCOUNT('NL personnel_HR_history'[personnel number]) ,",
              "                                   FILTER('BI DIM_DATE', 'BI DIM_DATE'[jmonthN]= monthh),",
              "                                     DISTINCTCOUNT('NL personnel_HR_history'[personnel number]))",
              "                                     ",
              "                                     ",
              "                                     */"
            ]
          }
        ]
      },
      {
        "name": "NL after_sales_service",
        "columns": [
          {
            "name": "acceptance number",
            "dataType": "int64",
            "sourceColumn": "acceptance number"
          },
          {
            "name": "normal_customer_name",
            "dataType": "string",
            "sourceColumn": "normal_customer_name"
          },
          {
            "name": "Acceptable date",
            "dataType": "dateTime",
            "description": "تاریخ میلادی پذیرش",
            "sourceColumn": "Acceptable date"
          },
          {
            "name": "Date of departure or delivery or filing",
            "dataType": "dateTime",
            "description": "تاریخ میلادی خروج -تحویل یا بایگانی",
            "sourceColumn": "Date of departure or delivery or filing"
          },
          {
            "name": "device_brand",
            "dataType": "string",
            "description": "مارک دستگاه ",
            "sourceColumn": "device_brand"
          },
          {
            "name": "device type",
            "dataType": "string",
            "description": "نوع دستگاه",
            "sourceColumn": "device type"
          },
          {
            "name": "device_model",
            "dataType": "string",
            "description": "مدل دستگاه",
            "sourceColumn": "device_model"
          },
          {
            "name": "device_serial_number",
            "dataType": "string",
            "description": "شماره سریال دستگاه",
            "sourceColumn": "device_serial_number"
          },
          {
            "name": "customer_address",
            "dataType": "string",
            "description": "آدرس مشتری",
            "sourceColumn": "customer_address"
          },
          {
            "name": "Customer_phone_number",
            "dataType": "string",
            "description": "تلفن مشتری",
            "sourceColumn": "Customer_phone_number"
          },
          {
            "name": "service_type",
            "dataType": "string",
            "description": "نوع سرویس",
            "sourceColumn": "service_type"
          },
          {
            "name": "serviced",
            "dataType": "string",
            "description": "سرویس شده ",
            "sourceColumn": "serviced"
          },
          {
            "name": "solar_date_of_exit_or_delivery_or_archive",
            "dataType": "string",
            "description": "تاریخ شمسی خروج یا تحویل یا بایگانی",
            "sourceColumn": "solar_date_of_exit_or_delivery_or_archive"
          },
          {
            "name": "Acceptable solar date",
            "dataType": "string",
            "description": "تاریخ شمسی پذیرش",
            "sourceColumn": "Acceptable solar date"
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City"
          },
          {
            "name": "name_service_representative",
            "dataType": "string",
            "description": "نام نماینده خدمت ",
            "sourceColumn": "name_service_representative"
          },
          {
            "name": "representative_code",
            "dataType": "int64",
            "description": "کد نماینده خدمت ",
            "sourceColumn": "representative_code"
          },
          {
            "name": "date_of_the_year_of_archiving_operations",
            "dataType": "dateTime",
            "description": "تاریخ میلادی انجام عملیات بایگانی",
            "sourceColumn": "date_of_the_year_of_archiving_operations"
          },
          {
            "name": "solar_date_of_archiving_operations",
            "dataType": "string",
            "description": "تاریخ شمسی انجام عملیات بایگانی",
            "sourceColumn": "solar_date_of_archiving_operations"
          },
          {
            "name": "issuing_code",
            "dataType": "string",
            "description": "کد صادر کننده",
            "sourceColumn": "issuing_code"
          },
          {
            "name": "issuer_name",
            "dataType": "string",
            "description": "نا صادر کننده",
            "sourceColumn": "issuer_name"
          },
          {
            "name": "file_name",
            "dataType": "string",
            "description": "نام بایگان",
            "sourceColumn": "file_name"
          },
          {
            "name": "Time_Archive",
            "dataType": "dateTime",
            "description": "ساعت بایگانی",
            "sourceColumn": "Time_Archive"
          },
          {
            "name": "service_end_time",
            "dataType": "string",
            "description": "ساعت اتمام سرویس",
            "sourceColumn": "service_end_time"
          },
          {
            "name": "Acceptance time",
            "dataType": "dateTime",
            "description": "ساعت پذیرش",
            "sourceColumn": "Acceptance time"
          },
          {
            "name": "Acceptable_registration_code",
            "dataType": "string",
            "description": "کد ثبت پذیرش",
            "sourceColumn": "Acceptable_registration_code"
          },
          {
            "name": "solar_date_of_service_completion",
            "dataType": "string",
            "description": "تاریخ شمسی اتمام سرویس",
            "sourceColumn": "solar_date_of_service_completion"
          },
          {
            "name": "date_of_formation_of_invoice_acceptance",
            "dataType": "string",
            "description": "تاریخ تشکیل قبض پذیرش",
            "sourceColumn": "date_of_formation_of_invoice_acceptance"
          },
          {
            "type": "calculated",
            "name": "001_The distance between admission and departure",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "description": "تفاضل پذیرش تا تحویل ",
            "expression": [
              " ",
              "       ",
              "         DATEDIFF('NL after_sales_service'[Acceptable date],",
              "                            'NL after_sales_service'[Date of departure or delivery or filing],DAY)",
              "",
              "--تفاضل پذیرش تا تحویل "
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    NL_after_sales_service = Source{[Schema=\"NL\",Item=\"after_sales_service\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(NL_after_sales_service,\"ي\",\"ی\",Replacer.ReplaceText,{\"normal_customer_name\", \"device_brand\", \"device type\", \"customer_address\", \"service_type\", \"State\", \"City\", \"name_service_representative\", \"issuer_name\", \"file_name\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "002_count acceptance",
            "description": " تعداد پذیرش ",
            "expression": [
              " ",
              "",
              "  DISTINCTCOUNT('NL after_sales_service'[Acceptable date])",
              "",
              "-- تعداد پذیرش "
            ]
          }
        ]
      },
      {
        "name": "NL jalasat_report",
        "columns": [
          {
            "name": "session_number",
            "dataType": "int64",
            "description": "شماره جلسه",
            "sourceColumn": "session_number"
          },
          {
            "name": "row",
            "dataType": "int64",
            "sourceColumn": "row"
          },
          {
            "name": "secretary_meeting",
            "dataType": "int64",
            "sourceColumn": "secretary_meeting"
          },
          {
            "name": "description_of_the_meeting_secretary",
            "dataType": "string",
            "sourceColumn": "description_of_the_meeting_secretary"
          },
          {
            "name": "deadline_date",
            "dataType": "string",
            "sourceColumn": "deadline_date"
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description"
          },
          {
            "name": "Executive_Descriptions",
            "dataType": "string",
            "sourceColumn": "Executive_Descriptions"
          },
          {
            "name": "Follower_explanations",
            "dataType": "string",
            "sourceColumn": "Follower_explanations"
          },
          {
            "name": "The name of the follow-up officer",
            "dataType": "string",
            "sourceColumn": "The name of the follow-up officer"
          },
          {
            "name": "explanations",
            "dataType": "string",
            "sourceColumn": "explanations"
          },
          {
            "name": "Work_teams",
            "dataType": "string",
            "sourceColumn": "Work_teams"
          },
          {
            "name": "present_in_the_meeting",
            "dataType": "string",
            "sourceColumn": "present_in_the_meeting"
          },
          {
            "name": "from_hour",
            "dataType": "string",
            "sourceColumn": "from_hour"
          },
          {
            "name": "until",
            "dataType": "string",
            "sourceColumn": "until"
          },
          {
            "name": "Explanations 2",
            "dataType": "string",
            "sourceColumn": "Explanations 2"
          },
          {
            "name": "personnel_code",
            "dataType": "int64",
            "sourceColumn": "personnel_code"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    NL_jalasat_report = Source{[Schema=\"NL\",Item=\"jalasat_report\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(NL_jalasat_report,\"ي\",\"ی\",Replacer.ReplaceText,{\"explanations\", \"Executive_Descriptions\", \"Explanations 2\", \"description_of_the_meeting_secretary\", \"Description\", \"The name of the follow-up officer\", \"Follower_explanations\", \"Work_teams\", \"present_in_the_meeting\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ]
      },
      {
        "name": "NL survey_on_employment",
        "columns": [
          {
            "name": "1) What_job_position",
            "dataType": "string",
            "sourceColumn": "1) What_job_position"
          },
          {
            "name": "2) What_category_organization",
            "dataType": "string",
            "sourceColumn": "2) What_category_organization"
          },
          {
            "name": "3) Who_have_you_interacted",
            "dataType": "string",
            "sourceColumn": "3) Who_have_you_interacted"
          },
          {
            "name": "4) How_long_process",
            "dataType": "string",
            "sourceColumn": "4) How_long_process"
          },
          {
            "name": "5)interview_held_at_appointed_time",
            "dataType": "string",
            "sourceColumn": "5)interview_held_at_appointed_time"
          },
          {
            "name": "6)final_time_announcing_ result",
            "dataType": "string",
            "sourceColumn": "6)final_time_announcing_ result"
          },
          {
            "name": "7) recommend_Arva_company",
            "dataType": "string",
            "sourceColumn": "7) recommend_Arva_company"
          },
          {
            "name": "8)positive_points",
            "dataType": "string",
            "sourceColumn": "8)positive_points"
          },
          {
            "name": "9)improved_way",
            "dataType": "string",
            "sourceColumn": "9)improved_way"
          },
          {
            "name": "full_name",
            "dataType": "string",
            "sourceColumn": "full_name"
          },
          {
            "name": "ID",
            "dataType": "string",
            "sourceColumn": "ID"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    NL_survey_on_employment = Source{[Schema=\"NL\",Item=\"survey_on_employment\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(NL_survey_on_employment,\"ي\",\"ی\",Replacer.ReplaceText,{\"1) What_job_position\", \"2) What_category_organization\", \"3) Who_have_you_interacted\", \"4) How_long_process\", \"5)interview_held_at_appointed_time\", \"6)final_time_announcing_ result\", \"7) recommend_Arva_company\", \"8)positive_points\", \"9)improved_way\", \"full_name\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ]
      },
      {
        "name": "NL survey_on_employment_detail",
        "columns": [
          {
            "name": "Question",
            "dataType": "string",
            "sourceColumn": "Question"
          },
          {
            "name": "ID",
            "dataType": "string",
            "sourceColumn": "ID"
          },
          {
            "name": "Score",
            "dataType": "double",
            "sourceColumn": "Score"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    NL_survey_on_employment_detail = Source{[Schema=\"NL\",Item=\"survey_on_employment_detail\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(NL_survey_on_employment_detail,\"ي\",\"ی\",Replacer.ReplaceText,{\"Question\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ]
      },
      {
        "name": "VN Visitor_Path_History",
        "description": "جدول سوابق مسیر ویزیتورها",
        "columns": [
          {
            "name": "SalePathRef",
            "dataType": "int64",
            "sourceColumn": "SalePathRef"
          },
          {
            "name": "SalePathNo",
            "dataType": "int64",
            "sourceColumn": "SalePathNo"
          },
          {
            "name": "SalePathName",
            "dataType": "string",
            "sourceColumn": "SalePathName"
          },
          {
            "name": "SaleAreaRef",
            "dataType": "int64",
            "sourceColumn": "SaleAreaRef"
          },
          {
            "name": "SaleAreaNo",
            "dataType": "int64",
            "sourceColumn": "SaleAreaNo"
          },
          {
            "name": "DealerRef",
            "dataType": "int64",
            "sourceColumn": "DealerRef"
          },
          {
            "name": "SaleAreaName",
            "dataType": "string",
            "sourceColumn": "SaleAreaName"
          },
          {
            "name": "SaleZoneRef",
            "dataType": "int64",
            "sourceColumn": "SaleZoneRef"
          },
          {
            "name": "SaleZoneNo",
            "dataType": "int64",
            "sourceColumn": "SaleZoneNo"
          },
          {
            "name": "SaleZoneName",
            "dataType": "string",
            "sourceColumn": "SaleZoneName"
          },
          {
            "name": "AreaRef",
            "dataType": "int64",
            "sourceColumn": "AreaRef"
          },
          {
            "name": "insertDate",
            "dataType": "string",
            "sourceColumn": "insertdate"
          },
          {
            "name": "StateCode",
            "dataType": "string",
            "sourceColumn": "StateCode"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    VN_Visitor_Path_History = Source{[Schema=\"VN\",Item=\"Visitor_Path_History\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(VN_Visitor_Path_History,\"ي\",\"ی\",Replacer.ReplaceText,{\"SalePathName\", \"SaleAreaName\", \"SaleZoneName\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ]
      },
      {
        "name": "NL CRM",
        "columns": [
          {
            "name": "No._complaint_PK",
            "dataType": "int64",
            "sourceColumn": "No._complaint_PK"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "description": "سال ",
            "sourceColumn": "Year"
          },
          {
            "name": "Complaint number",
            "dataType": "int64",
            "description": "شماره شکایت ",
            "sourceColumn": "Complaint number"
          },
          {
            "name": "sort",
            "dataType": "string",
            "description": "دسته بندی ",
            "sourceColumn": "sort"
          },
          {
            "name": "Category description",
            "dataType": "string",
            "description": "شرح دسته بندی",
            "sourceColumn": "Category description"
          },
          {
            "name": "Complaint_date",
            "dataType": "string",
            "description": "تاریخ شکایت ",
            "sourceColumn": "Complaint_date"
          },
          {
            "name": "Complaint time",
            "dataType": "string",
            "description": "زمان شکایت ",
            "sourceColumn": "Complaint time"
          },
          {
            "name": "registrant_user",
            "dataType": "string",
            "description": "کاربر ثبت کننده",
            "sourceColumn": "registrant_user"
          },
          {
            "name": "Canceled by the customer",
            "dataType": "string",
            "description": "کنسلی توسط مشتری ",
            "sourceColumn": "Canceled by the customer"
          },
          {
            "name": "contact_code",
            "dataType": "int64",
            "description": "کد مخاطب ",
            "sourceColumn": "contact_code"
          },
          {
            "name": "complaint_basis",
            "dataType": "string",
            "description": "شکایت مبنا",
            "sourceColumn": "complaint_basis"
          },
          {
            "name": "Audience",
            "dataType": "string",
            "description": "مخاطب",
            "sourceColumn": "Audience"
          },
          {
            "name": "subject_complaint",
            "dataType": "string",
            "description": "موضوع شکایت ",
            "sourceColumn": "subject_complaint"
          },
          {
            "name": "employer_code",
            "dataType": "string",
            "description": "کد کارفرما",
            "sourceColumn": "employer_code"
          },
          {
            "name": "employer_description",
            "dataType": "string",
            "description": "شرح کارفرما",
            "sourceColumn": "employer_description"
          },
          {
            "name": "Sufficiency",
            "dataType": "string",
            "description": "کفایت ",
            "sourceColumn": "Sufficiency"
          },
          {
            "name": "subjectivity",
            "dataType": "string",
            "description": "موضوعیت ",
            "sourceColumn": "subjectivity"
          },
          {
            "name": "effective",
            "dataType": "string",
            "description": "اثربخشی ",
            "sourceColumn": "effective"
          },
          {
            "name": "effective_date",
            "dataType": "string",
            "description": "تاریخ  اثربخشی",
            "sourceColumn": "effective_date"
          },
          {
            "name": "customer_satisfaction_survey",
            "dataType": "string",
            "description": "رضایت سنجی مشتری ",
            "sourceColumn": "customer_satisfaction_survey"
          },
          {
            "name": "Date_of_satisfaction_survey",
            "dataType": "string",
            "description": "تاریخ رضایت سنجی",
            "sourceColumn": "Date_of_satisfaction_survey"
          },
          {
            "name": "representative_code",
            "dataType": "string",
            "description": "کد رضایت سنجی ",
            "sourceColumn": "representative_code"
          },
          {
            "name": "Representative_Description",
            "dataType": "string",
            "description": "شرح نماینده",
            "sourceColumn": "Representative_Description"
          },
          {
            "name": "audience_description",
            "dataType": "string",
            "description": "شرح مخاطب ",
            "sourceColumn": "audience_description"
          },
          {
            "name": "Along",
            "dataType": "int64",
            "sourceColumn": "Along"
          },
          {
            "name": "priority",
            "dataType": "string",
            "description": "اولویت ",
            "sourceColumn": "priority"
          },
          {
            "name": "Phone",
            "dataType": "string",
            "description": "تلفن ",
            "sourceColumn": "Phone"
          },
          {
            "name": "contact_address",
            "dataType": "string",
            "description": "آدرس مخاطب ",
            "sourceColumn": "contact_address"
          },
          {
            "name": "Complaint type",
            "dataType": "string",
            "description": "نوع شکایت ",
            "sourceColumn": "Complaint type"
          },
          {
            "name": "Description of the type of complaint",
            "dataType": "string",
            "description": "شرح نوع شکایت ",
            "sourceColumn": "Description of the type of complaint"
          },
          {
            "name": "report_date",
            "dataType": "string",
            "sourceColumn": "report_date"
          },
          {
            "type": "calculated",
            "name": "002_miladi Date complaints",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "description": "تاریخ میلادی شکایت ",
            "expression": [
              " ",
              "                LOOKUPVALUE('BI DIM_DATE'[Miladi],'BI DIM_DATE'[Jalali_1], 'NL CRM'[Complaint_date])",
              "",
              "   -- تاریخ میلادی شکایت "
            ],
            "formatString": "General Date"
          },
          {
            "type": "calculated",
            "name": "003_Miladi Date of satisfaction",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "description": "تاریخ میلادی نظرسنجی",
            "expression": [
              " ",
              "        if( 'NL CRM'[Date_of_satisfaction_survey] = BLANK() , TODAY(), ",
              "          LOOKUPVALUE('BI DIM_DATE'[Miladi],'BI DIM_DATE'[Jalali_1], 'NL CRM'[Date_of_satisfaction_survey]))",
              "",
              " -- تاریخ میلادی نظرسنجی "
            ]
          },
          {
            "type": "calculated",
            "name": "004_DateDiff complaint and survy",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "description": "اختلاف تاریخ ثبت شکایت و نظرسنجی",
            "expression": [
              "",
              "                   DATEDIFF( 'NL CRM'[002_miladi Date complaints] ,'NL CRM'[003_Miladi Date of satisfaction], DAY)",
              "",
              "-- اختلاف تاریخ ثبت شکایت و نظرسنجی"
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    NL_CRM = Source{[Schema=\"NL\",Item=\"CRM\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(NL_CRM,\"ي\",\"ی\",Replacer.ReplaceText,{\"Category description\", \"Canceled by the customer\", \"Audience\", \"subject_complaint\", \"employer_description\", \"Sufficiency\", \"subjectivity\", \"effective\", \"customer_satisfaction_survey\", \"audience_description\", \"priority\", \"Phone\", \"contact_address\", \"Description of the type of complaint\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "001_Number of customer complaints",
            "description": "تعداد شکایت مشتریان ",
            "expression": [
              " ",
              "",
              "                CALCULATE(  DISTINCTCOUNT('NL CRM'[Complaint number]) ,",
              "                                      USERELATIONSHIP('NL CRM'[Complaint_date], 'BI DIM_DATE'[Jalali_1]))",
              "",
              "-- تعداد شکایت مشتریان "
            ]
          },
          {
            "name": "005_Average satisfaction",
            "description": "متوسط رضایت سنجی",
            "expression": [
              " ",
              "",
              "            sum('NL CRM'[004_DateDiff complaint and survy])",
              "                    / ",
              "                      'NL CRM'[001_Number of customer complaints]",
              "",
              "--متوسط رضایت سنجی"
            ],
            "formatString": "0.00"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "6baeca40-a82c-4403-998d-6b541a21619d",
        "fromTable": "VN Fact_int_Vocher_Itm_Qty",
        "fromColumn": "GoodsRef",
        "toTable": "VN Dim_Goods",
        "toColumn": "Goods_ID"
      },
      {
        "name": "f5fe40bb-4ce0-429b-8d9f-43893bcd0560",
        "fromTable": "VN Fact_int_Vocher_Itm_Qty",
        "fromColumn": "StockDCRef",
        "toTable": "VN Dim_Stock",
        "toColumn": "StockDC_ID"
      },
      {
        "name": "5b25d755-6830-4be1-a22b-4080b33a81bd",
        "fromTable": "VN Fact_int_Vocher_Itm_Qty",
        "fromColumn": "VocherDate",
        "toTable": "BI DIM_DATE",
        "toColumn": "Jalali_1"
      },
      {
        "name": "aa61cb7c-9de1-4f84-94f5-59c190f3872c",
        "fromTable": "BI last_refresh_time_knime",
        "fromColumn": "Date",
        "toTable": "BI DIM_DATE",
        "toColumn": "Jalali_1"
      },
      {
        "name": "0789e9d5-972c-490b-a637-0e5e032db74b",
        "fromTable": "VN Fact_int_Vocher_Itm_Qty_history",
        "fromColumn": "StockDCRef",
        "toTable": "VN Dim_Stock",
        "toColumn": "StockDC_ID"
      },
      {
        "name": "4b70da09-6fcc-477d-9596-c79b15c23ed0",
        "fromTable": "VN Fact_int_Vocher_Itm_Qty_history",
        "fromColumn": "VocherDate",
        "toTable": "BI DIM_DATE",
        "toColumn": "Jalali_1"
      },
      {
        "name": "767ab058-c049-419c-a7c0-67e6fb310c2e",
        "fromTable": "VN Fact_int_Vocher_Itm_Qty_history",
        "fromColumn": "GoodsRef",
        "toTable": "VN Dim_Goods",
        "toColumn": "Goods_ID"
      },
      {
        "name": "4ed638d1-000d-4315-8373-6a839cb24ac8",
        "fromTable": "VN Fact_Order",
        "fromColumn": "OrderDate",
        "toTable": "BI DIM_DATE",
        "toColumn": "Jalali_1"
      },
      {
        "name": "86253f4e-9193-4288-9a32-9e2797a1119f",
        "fromTable": "VN Fact_Order",
        "fromColumn": "ShipDate",
        "toTable": "BI DIM_DATE",
        "toColumn": "Jalali_1",
        "isActive": false
      },
      {
        "name": "db2254c9-14bf-4b02-a498-471838e76834",
        "fromTable": "VN Fact_Order",
        "fromColumn": "ConfirmDate",
        "toTable": "BI DIM_DATE",
        "toColumn": "Jalali_1",
        "isActive": false
      },
      {
        "name": "19695839-f77e-4ada-bda6-be0abce75c51",
        "fromTable": "VN Fact_Order",
        "fromColumn": "StockDcRef",
        "toTable": "VN Dim_Stock",
        "toColumn": "StockDC_ID"
      },
      {
        "name": "eea9792d-6a8c-43ef-ace8-8e225544689f",
        "fromTable": "VN Fact_Order",
        "fromColumn": "GoodsRef",
        "toTable": "VN Dim_Goods",
        "toColumn": "Goods_ID"
      },
      {
        "name": "3ced8d0f-1e8a-471f-9ed6-f0be9ad4a63f",
        "fromTable": "VN Fact_Order",
        "fromColumn": "CustRef",
        "toTable": "VN Dim_Cust",
        "toColumn": "tblCust_ID"
      },
      {
        "name": "b49c24ea-32c8-4622-84f3-88b3fd475d01",
        "fromTable": "VN Fact_Sale",
        "fromColumn": "GoodsRef",
        "toTable": "VN Dim_Goods",
        "toColumn": "Goods_ID"
      },
      {
        "name": "dda11403-1650-445c-9431-496ac158aa55",
        "fromTable": "VN Fact_Sale",
        "fromColumn": "CustRef",
        "toTable": "VN Dim_Cust",
        "toColumn": "tblCust_ID"
      },
      {
        "name": "daa73da5-cefb-4014-b19c-29f84d1750d1",
        "toCardinality": "many",
        "fromTable": "VN Fact_Order",
        "fromColumn": "tblOrderHdr_ID",
        "toTable": "VN Fact_Sale",
        "toColumn": "OrderRef",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "3de30480-7c70-417d-bfcc-f272a232c370",
        "fromTable": "VN Dim_Cust",
        "fromColumn": "AreaRef",
        "toTable": "BI Dim_Geographic",
        "toColumn": "ID"
      },
      {
        "name": "1282abdf-dd9f-4329-8b95-fea6f67f3a3a",
        "fromTable": "VN Fact_Sale",
        "fromColumn": "SaleDate",
        "toTable": "BI DIM_DATE",
        "toColumn": "Jalali_1"
      },
      {
        "name": "41e94d30-9983-4808-9ab7-659822317bc4",
        "fromTable": "VN Fact_RetSale",
        "fromColumn": "SaleDate",
        "toTable": "BI DIM_DATE",
        "toColumn": "Jalali_1"
      },
      {
        "name": "299f56c1-a3c9-4637-a62b-27da744e5178",
        "fromTable": "VN Fact_RetSale",
        "fromColumn": "CustRef",
        "toTable": "VN Dim_Cust",
        "toColumn": "tblCust_ID"
      },
      {
        "name": "2fdc9c7c-b4c8-4ce2-8230-1e869f235fb4",
        "fromTable": "VN Fact_RetSale",
        "fromColumn": "GoodsRef",
        "toTable": "VN Dim_Goods",
        "toColumn": "Goods_ID"
      },
      {
        "name": "34e41b7a-bae1-40c0-abc6-a169b5d126b9",
        "fromTable": "VN Fact_Target",
        "fromColumn": "Jalali_1",
        "toTable": "BI DIM_DATE",
        "toColumn": "Jalali_1"
      },
      {
        "name": "710e867f-c16c-4b91-b457-979afb04477a",
        "toCardinality": "many",
        "fromTable": "BI Dim_Geographic",
        "fromColumn": "StateCode",
        "toTable": "VN Fact_Target",
        "toColumn": "StateCode",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "f1fbe34b-eed9-4bf9-8427-f4fee668a73c",
        "fromTable": "VN Fact_Sale",
        "fromColumn": "DealerRef",
        "toTable": "VN Dim_Personnel",
        "toColumn": "PersonnelId"
      },
      {
        "name": "d93bfa85-72b0-4cdd-ad81-519862ed14ec",
        "fromTable": "VN Fact_Order",
        "fromColumn": "DealerRef",
        "toTable": "VN Dim_Personnel",
        "toColumn": "PersonnelId"
      },
      {
        "name": "07ad84f4-b926-481a-8886-d24d36b2cbee",
        "fromTable": "VN Fact_RetSale",
        "fromColumn": "DealerRef",
        "toTable": "VN Dim_Personnel",
        "toColumn": "PersonnelCode"
      },
      {
        "name": "8a522a72-6df3-4dc4-9379-b014ed757760",
        "toCardinality": "many",
        "fromTable": "VN Fact_RetSale",
        "fromColumn": "SaleHdr_ID",
        "toTable": "VN Fact_Sale",
        "toColumn": "SaleHdr_ID",
        "isActive": false,
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "2f966591-b5a1-4f0d-bfd1-2fc253d2b286",
        "fromCardinality": "one",
        "fromTable": "VN Dim_Cust",
        "fromColumn": "tblCust_ID",
        "toTable": "VN RFM",
        "toColumn": "CustRef",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "cc367397-272f-44cb-a648-83f2c5db093b",
        "fromTable": "NL receipt_report",
        "fromColumn": "date_change_status",
        "toTable": "BI DIM_DATE",
        "toColumn": "Jalali_1"
      },
      {
        "name": "990fbab4-487f-4ed2-9ecc-b04829a10011",
        "fromTable": "NL payment_report",
        "fromColumn": "payment_date",
        "toTable": "BI DIM_DATE",
        "toColumn": "Jalali_1"
      },
      {
        "name": "794e2d3f-c64b-46a8-88e2-b6fdefd333eb",
        "toCardinality": "many",
        "fromTable": "VN Fact_int_Vocher_Itm_Qty",
        "fromColumn": "unic_code_int",
        "toTable": "VN Fact_int_Vocher_Itm_Qty_history",
        "toColumn": "unic_code_int",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "a2ae8352-b24b-4f23-9a67-0afcc30d9cd6",
        "fromTable": "GA Google_Search_Console_API",
        "fromColumn": "date",
        "toTable": "BI DIM_DATE",
        "toColumn": "Miladi"
      },
      {
        "name": "a20fe682-5357-4122-a8c7-c9e420bccb9f",
        "fromTable": "GA Google_Analytics",
        "fromColumn": "fromDate",
        "toTable": "BI DIM_DATE",
        "toColumn": "Miladi"
      },
      {
        "name": "d12182eb-e28d-4652-a162-25d872d367da",
        "fromTable": "VN Fact_Tour",
        "fromColumn": "PersonnelCode_agent",
        "toTable": "VN Dim_Personnel",
        "toColumn": "PersonnelCode"
      },
      {
        "name": "4d87000b-6ff4-4c8b-a57a-12ead2304c00",
        "fromTable": "VN Fact_Tour",
        "fromColumn": "TourPDate",
        "toTable": "BI DIM_DATE",
        "toColumn": "Jalali_1"
      },
      {
        "name": "547e966b-ec8c-45ab-817e-89eb8339f7c3",
        "fromTable": "VN Fact_Tour_detail",
        "fromColumn": "CustomerCode",
        "toTable": "VN Dim_Cust",
        "toColumn": "CustCode",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "56c935a7-297b-4eed-a06a-e265907a7c99",
        "toCardinality": "many",
        "fromTable": "VN Fact_Sale",
        "fromColumn": "unic_code",
        "toTable": "VN Fact_Tour_detail",
        "toColumn": "unic_code",
        "isActive": false,
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "986a1095-b6da-470f-9c38-2a563100aeec",
        "toCardinality": "many",
        "fromTable": "VN Fact_Order",
        "fromColumn": "unic_code",
        "toTable": "VN Fact_Tour_detail",
        "toColumn": "unic_code",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "4c2d718b-3688-4fb6-b8be-241a4a812767",
        "fromTable": "VN Fact_Tour_detail",
        "fromColumn": "TourUniqueId",
        "toTable": "VN Fact_Tour",
        "toColumn": "Id",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "2cc33cdb-7f8e-4948-b6a6-63b36b0c6688",
        "fromTable": "oracle VW_BI_INS_PERSONEL",
        "fromColumn": "ID_DAT",
        "toTable": "BI DIM_DATE",
        "toColumn": "Miladi"
      },
      {
        "name": "b091e47d-f142-47d8-a8ce-33f5ab301b88",
        "toCardinality": "many",
        "fromTable": "BI DIM_DATE",
        "fromColumn": "unic_code",
        "toTable": "NL personnel_HR_history",
        "toColumn": "unic_code",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "043da1f2-57e4-4992-8d6f-5356c2400a50",
        "toCardinality": "many",
        "fromTable": "NL personnel_HR_history",
        "fromColumn": "personnel number",
        "toTable": "NL personnel_HR",
        "toColumn": "personnel number",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "0453a074-d529-4dcb-9f91-bdae0fc2c4a6",
        "fromTable": "BI dollar_price",
        "fromColumn": "jalali_date",
        "toTable": "BI DIM_DATE",
        "toColumn": "Jalali_1"
      },
      {
        "name": "8732809c-a618-463e-9a2c-96b1a5c57219",
        "fromTable": "NL jalasat_report",
        "fromColumn": "personnel_code",
        "toTable": "NL personnel_HR",
        "toColumn": "personnel number"
      },
      {
        "name": "0b851f1e-1f5c-4c48-b0b8-08dacd5f815e",
        "fromTable": "NL after_sales_service",
        "fromColumn": "Acceptable date",
        "toTable": "BI DIM_DATE",
        "toColumn": "Miladi"
      },
      {
        "name": "5b4f8c56-b2eb-4524-ac6b-e69025c38dde",
        "fromTable": "NL after_sales_service",
        "fromColumn": "City",
        "toTable": "BI Dim_Geographic",
        "toColumn": "AreaCode"
      },
      {
        "name": "fb89f835-4c85-4f21-806c-27dc645164aa",
        "fromTable": "NL survey_on_employment_detail",
        "fromColumn": "ID",
        "toTable": "NL survey_on_employment",
        "toColumn": "ID"
      },
      {
        "name": "19b94d05-7aa2-4eb7-aae3-882b21f1183b",
        "fromTable": "VN Visitor_Path_History",
        "fromColumn": "DealerRef",
        "toTable": "VN Dim_Personnel",
        "toColumn": "PersonnelId"
      },
      {
        "name": "bef724cd-ed48-4613-9cc1-6f62d8f62e21",
        "fromTable": "VN Visitor_Path_History",
        "fromColumn": "insertDate",
        "toTable": "BI DIM_DATE",
        "toColumn": "Jalali_1"
      },
      {
        "name": "10e70b6a-7c2d-4554-ab0d-b1621f55c55e",
        "fromTable": "NL CRM",
        "fromColumn": "Date_of_satisfaction_survey",
        "toTable": "BI DIM_DATE",
        "toColumn": "Jalali_1"
      },
      {
        "name": "966314f0-2df0-43c1-9e3a-ac904280fb66",
        "fromTable": "NL CRM",
        "fromColumn": "Complaint_date",
        "toTable": "BI DIM_DATE",
        "toColumn": "Jalali_1",
        "isActive": false
      }
    ],
    "roles": [
      {
        "name": "Refresher",
        "modelPermission": "administrator",
        "members": [
          {
            "memberName": "ARVA\\dashti.a",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-1264"
          }
        ]
      },
      {
        "name": "Manager",
        "modelPermission": "administrator",
        "members": [
          {
            "memberName": "ARVA\\dashti.a",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-1264"
          },
          {
            "memberName": "ARVA\\ahmadi.fr",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-4114"
          },
          {
            "memberName": "ARVA\\gholami",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-1478"
          }
        ]
      },
      {
        "name": "BI_Admins",
        "description": "گروه جهت دسترسی ادیمن های BI",
        "modelPermission": "administrator",
        "members": [
          {
            "memberName": "ARVA\\BI_Admins",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-4319"
          },
          {
            "memberName": "ARVA\\dashti.a",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-1264"
          }
        ]
      },
      {
        "name": "BI_CEO_Fullview",
        "description": "گروه جهت دسترسی مدیران",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_CEO_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-4314"
          }
        ]
      },
      {
        "name": "BI_Ahvaz_Fullview",
        "description": "گروه جهت دسترسی استان بوشهر",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_Ahvaz_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3308"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": "'BI Dim_Geographic'[StateCode] = 16"
          }
        ]
      },
      {
        "name": "BI_Fars_Fullview",
        "description": "گروه جهت دسترسی استان فارس",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_Fars_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-4320"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": "'BI Dim_Geographic'[StateCode] = 17"
          }
        ]
      },
      {
        "name": "BI_Esfahan_Fullview",
        "description": "گروه جهت دسترسی استان فارس",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_Esfahan_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3309"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": " 'BI Dim_Geographic'[StateCode] =20"
          }
        ]
      },
      {
        "name": "BI_Tehran_Fullview",
        "description": "گروه جهت دسترسی به استان تهران",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_Tehran_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3310"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": " 'BI Dim_Geographic'[StateCode]=10"
          }
        ]
      },
      {
        "name": "BI_Kerman_Fullview",
        "description": "گروه جهت دسترسی به استان کرمان ",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_Kerman_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3315"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": " 'BI Dim_Geographic'[StateCode]=18  "
          }
        ]
      },
      {
        "name": "BI_Kermanshah_Fullview",
        "description": "گروه جهت دسترسی به  استان کرمانشاه",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_Kermanshah_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3314"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": " 'BI Dim_Geographic'[StateCode]= 15"
          }
        ]
      },
      {
        "name": "BI_Ghom_Fullview",
        "description": "گروه جهت دسترسی به استان قم",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_Ghom_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3333"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": " 'BI Dim_Geographic'[StateCode]=62"
          }
        ]
      },
      {
        "name": "BI_Zanjan_Fullview",
        "description": "گروه جهت دسترسی به استان زنجان",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_Zanjan_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3328"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": " 'BI Dim_Geographic'[StateCode]=29"
          }
        ]
      },
      {
        "name": "BI_Markazi_Fullview",
        "description": "گروه جهت دسترسی به  استان مرکزی",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_Markazi_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3329"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": " 'BI Dim_Geographic'[StateCode]=44"
          }
        ]
      },
      {
        "name": "BI_Hamedan_Fullview",
        "description": "گروه جهت دسترسی به استان همدان",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_Hamedan_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3323"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": " 'BI Dim_Geographic'[StateCode]= 24"
          }
        ]
      },
      {
        "name": "BI_Telephone Sales_Fullview",
        "description": "گروه جهت دسترسی به همه استان ها (فروش تلفنی)",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_Telephone Sales_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3342"
          }
        ]
      },
      {
        "name": "BI_Kordestan_Fullview",
        "description": "گروه جهت دسترسی به استان کردستان",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_Kordestan_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3319"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": " 'BI Dim_Geographic'[StateCode]=22"
          }
        ]
      },
      {
        "name": "BI_Chaharmahal and bakhtiari_Fullview",
        "description": "گروه جهت دسترسی به استان چهارمحال و بختیاری",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_chaharmahal and bakhtiari_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3324"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": " 'BI Dim_Geographic'[StateCode]=25"
          }
        ]
      },
      {
        "name": "BI_Ilam_Fullview",
        "description": "گروه جهت دسترسی به استان ایلام ",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_Ilam_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3326"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": "'BI Dim_Geographic'[StateCode]=27"
          }
        ]
      },
      {
        "name": "BI_Yazd_Fullview",
        "description": "گروه جهت دسترسی به یزد",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_Yazd_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3334"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": "'BI Dim_Geographic'[StateCode]=77"
          }
        ]
      },
      {
        "name": "BI_Ghazvin_Fullview",
        "description": "گروه جهت دسترسی به قزوین",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_Ghazvin_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3335"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": " 'BI Dim_Geographic'[StateCode]=63"
          }
        ]
      },
      {
        "name": "BI_Alborz_Fullview",
        "description": "گروه جهت دسترسی به البرز",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_Alborz_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3330"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": "'BI Dim_Geographic'[StateCode]=49"
          }
        ]
      },
      {
        "name": "BI_Gilan_Fullview",
        "description": "گروه جهت دسترسی به گیلان",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_Gilan_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3331"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": "'BI Dim_Geographic'[StateCode]=55"
          }
        ]
      },
      {
        "name": "BI_mazandaran_Fullview",
        "description": "گروه جهت دسترسی به مازندران ",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_mazandaran_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3311"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": " 'BI Dim_Geographic'[StateCode]=12"
          }
        ]
      },
      {
        "name": "BI_Golestan_Fullview",
        "description": "گروه جهت دسترسی به گلستان ",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_Golestan_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3336"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": "'BI Dim_Geographic'[StateCode]=64"
          }
        ]
      },
      {
        "name": "BI_Boshehr_Fullview",
        "description": "گروه جهت دسترسی به بوشهر",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_Boshehr_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3320"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": "'BI Dim_Geographic'[StateCode]=88"
          }
        ]
      },
      {
        "name": "BI_SalesPlanning_Fullview",
        "description": "گروه جهت دسترسی ب برنامه ریزی فروش ",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_SalesPlanning_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3343"
          }
        ]
      },
      {
        "name": "BI_Finance_Fullview",
        "description": "گروه جهت دسترسی  واحد مالی ",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_Finance_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3344"
          }
        ]
      },
      {
        "name": "BI_KhorasanJonobi_Fullview",
        "description": "گروه جهت دسترسی به خراسان جنوبی",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_KhorasanJonobi_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3317"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": " 'BI Dim_Geographic'[StateCode]=31"
          }
        ]
      },
      {
        "name": "BI_KhorasanRazavi_Fullview",
        "description": "گروه جهت دسترسی به خراسان رضوی",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_KhorasanRazavi_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3316"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": "'BI Dim_Geographic'[StateCode]=19"
          }
        ]
      },
      {
        "name": "BI_KhorasanShomali_Fullview",
        "description": "گروه جهت دسترسی به خراسان شمالی",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_KhorasanShomali_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3318"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": " 'BI Dim_Geographic'[StateCode]=21"
          }
        ]
      },
      {
        "name": "BI_Lorestan_Fullview",
        "description": "گروه جهت دسترسی به لرستان ",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_Lorestan_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3325"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": "'BI Dim_Geographic'[StateCode]=26"
          }
        ]
      },
      {
        "name": "BI_Azarvayejangharbi_Fullview",
        "description": "گروه جهت دسترسی به آذربایجان غربی ",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_Azarvayejangharbi_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3312"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": " 'BI Dim_Geographic'[StateCode]=14"
          }
        ]
      },
      {
        "name": "BI_Azarbayejansharghi_Fullview",
        "description": "گروه جهت دسترسی به آذربایجان شرقی ",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_Azarbayejansharghi_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3313"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": " 'BI Dim_Geographic'[StateCode]= 13"
          }
        ]
      },
      {
        "name": "BI_Ardebil_Fullview",
        "description": "گروه جهت دسترسی به اردبیل ",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_Ardebil_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3332"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": " 'BI Dim_Geographic'[StateCode]=61"
          }
        ]
      },
      {
        "name": "BI_Hormozgan_Fullview",
        "description": "گروه جهت دسترسی به هرمزگان",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_Hormozgan_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3322"
          }
        ],
        "tablePermissions": [
          {
            "name": "BI Dim_Geographic",
            "filterExpression": " 'BI Dim_Geographic'[StateCode]=23"
          }
        ]
      },
      {
        "name": "BSC_HR",
        "description": "گروه جهت دسترسی به BSC منابع",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BSC_HR",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-4375"
          }
        ],
        "tablePermissions": [
          {
            "name": "NL BSC",
            "filterExpression": "'NL BSC'[Unit code] =13"
          }
        ]
      },
      {
        "name": "BSC_Sales",
        "description": "گروه جهت دسترسی به  BSC  فروش  ",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BSC_Sales",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3365"
          }
        ],
        "tablePermissions": [
          {
            "name": "NL BSC",
            "filterExpression": "'NL BSC'[Index code] =10"
          }
        ]
      },
      {
        "name": "BSC_CRM",
        "description": "گروه جهت  دسترسی BSC CRM",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BSC_CRM",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3370"
          }
        ],
        "tablePermissions": [
          {
            "name": "NL BSC",
            "filterExpression": " 'NL BSC'[Unit code] = 1"
          }
        ]
      },
      {
        "name": "BSC_Services",
        "description": "گروه جهت دسترسی BSC  خدمات",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BSC_Services",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3371"
          }
        ],
        "tablePermissions": [
          {
            "name": "NL BSC",
            "filterExpression": "'NL BSC'[Unit code]= 9"
          }
        ]
      },
      {
        "name": "BSC_Support and supply",
        "description": "گروه جهت دسترسی به BSC پشتیبانی و  تامین ",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BSC_Support and supply",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3369"
          }
        ],
        "tablePermissions": [
          {
            "name": "NL BSC",
            "filterExpression": " 'NL BSC'[Unit code]=12 ||  'NL BSC'[Unit code]= 6 || 'NL BSC'[Unit code]=7 || 'NL BSC'[Unit code] =14"
          }
        ]
      },
      {
        "name": "BSC_Production",
        "description": "گروه جهت دسترسی به BSC تولید ",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BSC_Production",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3372"
          }
        ],
        "tablePermissions": [
          {
            "name": "NL BSC",
            "filterExpression": "'NL BSC'[Unit code]=8"
          }
        ]
      },
      {
        "name": "BSC_planning",
        "description": "گروه جهت دسترسی به  BSC برنامه ریزی ",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BSC_planning",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3373"
          }
        ],
        "tablePermissions": [
          {
            "name": "NL BSC",
            "filterExpression": "'NL BSC'[Unit code]=5"
          }
        ]
      },
      {
        "name": "BSC_Finance",
        "description": "گروه جهت دسترسی به BSC  مالی ",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BSC_Finance",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3383"
          }
        ],
        "tablePermissions": [
          {
            "name": "NL BSC",
            "filterExpression": " 'NL BSC'[Unit code]=11"
          }
        ]
      },
      {
        "name": "BI_Marketing_Fullview",
        "description": "گروه جهت دسترسی به گزارش مارکتینگ گوگل آنالیتیکس",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BI_Marketing_Fullview",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3425"
          }
        ]
      },
      {
        "name": "BSC_Admin",
        "description": "ادمین BSC",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BSC_Admin",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3428"
          }
        ]
      },
      {
        "name": "BSC_Net",
        "description": "گروه جهت دسترسی به BSC نت ",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BSC_Net",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3461"
          }
        ],
        "tablePermissions": [
          {
            "name": "NL BSC",
            "filterExpression": "'NL BSC'[Unit code]=15"
          }
        ]
      },
      {
        "name": "BSC_Engineering",
        "description": "گروه جهت دسترسی به BSC مهندسی ",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BSC_Engineering",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3462"
          }
        ],
        "tablePermissions": [
          {
            "name": "NL BSC",
            "filterExpression": " 'NL BSC'[Unit code]= 17"
          }
        ]
      },
      {
        "name": "BSC_QC",
        "description": "گروه جهت دسترسی به bsc QC",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ARVA\\BSC_QC",
            "memberId": "S-1-5-21-455356666-4183223732-1480618698-3463"
          }
        ],
        "tablePermissions": [
          {
            "name": "NL BSC",
            "filterExpression": " 'NL BSC'[Unit code]=16"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "600"
      }
    ]
  },
  "id": "SemanticModel"
}