{
  "name": "SemanticModel",
  "compatibilityLevel": 1500,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/192 168 1 28;ARVA_BI",
        "description": "اتصال به دیتاورهوس جدید که برای اتصال به سیستم جدید طراحی شده است",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "192.168.1.28",
            "database": "ARVA_BI"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "kind": "SQL",
          "path": "192.168.1.28;ARVA_BI",
          "Username": "sa",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "BI DIM_DATE",
        "description": "جدول تقویم",
        "columns": [
          {
            "name": "Miladi",
            "dataType": "dateTime",
            "description": "تاریخ میلادی",
            "sourceColumn": "Miladi"
          },
          {
            "name": "Jalali_1",
            "dataType": "string",
            "description": "تاریخ شمسی",
            "sourceColumn": "Jalali_1"
          },
          {
            "name": "jyear",
            "dataType": "int64",
            "sourceColumn": "jyear",
            "formatString": "0"
          },
          {
            "name": "jmonthN",
            "dataType": "int64",
            "description": "شماره ماه شمسی",
            "sourceColumn": "jmonthN"
          },
          {
            "name": "jmonthT",
            "dataType": "string",
            "description": "نام مه شمسی",
            "sourceColumn": "jmonthT",
            "sortByColumn": "jmonthN"
          },
          {
            "name": "jnime",
            "dataType": "string",
            "description": "نام نیمه سال شمسی",
            "sourceColumn": "jnime"
          },
          {
            "name": "JquarterN",
            "dataType": "int64",
            "description": "شماره فصل شمسی",
            "sourceColumn": "JquarterN"
          },
          {
            "name": "JQuarterT",
            "dataType": "string",
            "description": "نام فصل شمسی",
            "sourceColumn": "JQuarterT",
            "sortByColumn": "JquarterN"
          },
          {
            "name": "JWeekDay",
            "dataType": "string",
            "description": "روز هفته شمسی",
            "sourceColumn": "JWeekDay"
          },
          {
            "name": "JWeekNum",
            "dataType": "int64",
            "description": "شماره روز هفته",
            "sourceColumn": "JWeekNum"
          },
          {
            "name": "date_Counter",
            "dataType": "int64",
            "sourceColumn": "date_Counter"
          },
          {
            "name": "Is Holiday",
            "dataType": "string",
            "description": "جدول مشخص کننده روزهای تعطیل",
            "sourceColumn": "Is Holiday"
          },
          {
            "name": "day",
            "dataType": "string",
            "description": "روز",
            "sourceColumn": "day"
          },
          {
            "name": "end_month",
            "dataType": "int64",
            "sourceColumn": "end_month"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    BI_DIM_DATE = Source{[Schema=\"BI\",Item=\"DIM_DATE\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(BI_DIM_DATE,{\"Jalali_2\", \"Miladi_1\", \"mmonthN\", \"mmonthT\", \"mnime\", \"MquarterN\", \"MWeekDay\", \"MWeekNum\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Removed Columns\",\"ي\",\"ی\",Replacer.ReplaceText,{\"jmonthT\", \"jnime\", \"JQuarterT\", \"JWeekDay\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ]
      },
      {
        "name": "BI DIM_Geographic",
        "description": "جدول مشخصات شهر ها و استان ها",
        "columns": [
          {
            "name": "Id",
            "dataType": "int64",
            "description": "id شهر",
            "sourceColumn": "Id"
          },
          {
            "name": "StateFars",
            "dataType": "string",
            "sourceColumn": "StateFars"
          },
          {
            "name": "CityFars",
            "dataType": "string",
            "description": "نام شهر فارسی",
            "sourceColumn": "CityFars"
          },
          {
            "name": "Lat",
            "dataType": "double",
            "sourceColumn": "Lat"
          },
          {
            "name": "Long",
            "dataType": "double",
            "sourceColumn": "Long"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    BI_DIM_Geographic = Source{[Schema=\"BI\",Item=\"DIM_Geographic\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(BI_DIM_Geographic,{\"CityEng\", \"StateEng\", \"StateCity\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Removed Columns\",\"ي\",\"ی\",Replacer.ReplaceText,{\"StateFars\", \"CityFars\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ]
      },
      {
        "name": "VN Dim_Stock",
        "description": "جدول مشخصات انبارها",
        "columns": [
          {
            "name": "StockDC_ID",
            "dataType": "int64",
            "description": "شماره یونیک انبار id",
            "sourceColumn": "StockDC_ID"
          },
          {
            "name": "StockDCName",
            "dataType": "string",
            "description": "نام انبار",
            "sourceColumn": "StockDCName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    VN_Dim_Stock = Source{[Schema=\"VN\",Item=\"Dim_Stock\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(VN_Dim_Stock,\"ي\",\"ی\",Replacer.ReplaceText,{\"StockDCName\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ]
      },
      {
        "name": "VN Dim_Goods",
        "description": "جدول مشخصات کالاها",
        "columns": [
          {
            "name": "Goods_ID",
            "dataType": "int64",
            "description": "id محصول",
            "sourceColumn": "Goods_ID"
          },
          {
            "name": "GoodsCode",
            "dataType": "string",
            "description": "کد تعریف شده کالا",
            "sourceColumn": "GoodsCode"
          },
          {
            "name": "GoodsName",
            "dataType": "string",
            "description": "نام کالا",
            "sourceColumn": "GoodsName"
          },
          {
            "name": "GoodsGroupName",
            "dataType": "string",
            "description": "نام دسته بندی فرعی کالا",
            "sourceColumn": "GoodsGroupName"
          },
          {
            "name": "GoodsGroupName_Parent",
            "dataType": "string",
            "description": "نام دسه بندی اصلی کالا",
            "sourceColumn": "GoodsGroupName_Parent"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    VN_Dim_Goods = Source{[Schema=\"VN\",Item=\"Dim_Goods\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(VN_Dim_Goods,\"ي\",\"ی\",Replacer.ReplaceText,{\"GoodsName\", \"GoodsGroupName\", \"GoodsGroupName_Parent\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ]
      },
      {
        "name": "VN Fact_int_Vocher_Itm_Qty",
        "description": "جدول موجودی هر کالا در هر انبار براساس داده های سندهای رسید انبار",
        "columns": [
          {
            "name": "tblVocherItm_ID",
            "dataType": "int64",
            "description": "id سند های انبار",
            "sourceColumn": "tblVocherItm_ID"
          },
          {
            "name": "GoodsRef",
            "dataType": "int64",
            "description": "id کالا",
            "sourceColumn": "GoodsRef"
          },
          {
            "name": "TotalQty",
            "dataType": "double",
            "description": "تعداد ورودی یا خروجی",
            "sourceColumn": "TotalQty",
            "formatString": "0"
          },
          {
            "name": "StockDCRef",
            "dataType": "int64",
            "description": "شماره انبار",
            "sourceColumn": "StockDCRef"
          },
          {
            "name": "VocherNo",
            "dataType": "int64",
            "description": "شماره سند رسید انبار",
            "sourceColumn": "VocherNo"
          },
          {
            "name": "VocherDate",
            "dataType": "string",
            "description": "تاریخ سند رسید انبار",
            "sourceColumn": "VocherDate"
          },
          {
            "name": "VocherTypeName",
            "dataType": "string",
            "description": "نوع سند رسید انبار",
            "sourceColumn": "VocherTypeName"
          },
          {
            "name": "AccYear",
            "dataType": "int64",
            "sourceColumn": "AccYear"
          },
          {
            "name": "SalePrice",
            "dataType": "double",
            "sourceColumn": "SalePrice"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    VN_Fact_int_Vocher_Itm_Qty = Source{[Schema=\"VN\",Item=\"Fact_int_Vocher_Itm_Qty\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(VN_Fact_int_Vocher_Itm_Qty,\"ي\",\"ی\",Replacer.ReplaceText,{\"VocherTypeName\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "02_NumberSold",
            "description": "تعداد فروش رفته ",
            "expression": [
              "",
              "   (  ( CALCULATE(sum('VN Fact_int_Vocher_Itm_Qty'[TotalQty]),",
              "                         FILTER('VN Fact_int_Vocher_Itm_Qty', 'VN Fact_int_Vocher_Itm_Qty'[VocherTypeName] = ",
              "\"خروجی\"",
              "",
              "",
              "      )))*-1)",
              "-",
              " (  ( CALCULATE(sum('VN Fact_int_Vocher_Itm_Qty'[TotalQty]),",
              "                         FILTER('VN Fact_int_Vocher_Itm_Qty', 'VN Fact_int_Vocher_Itm_Qty'[VocherTypeName] = ",
              "\"برگشت حواله\"",
              "))))"
            ],
            "formatString": "#,#"
          },
          {
            "name": "06_RialSold",
            "description": "فروش ریالی ",
            "expression": [
              "",
              "     ( CALCULATE(sum('VN Fact_int_Vocher_Itm_Qty'[SalePrice]),",
              "                         FILTER('VN Fact_int_Vocher_Itm_Qty', 'VN Fact_int_Vocher_Itm_Qty'[VocherTypeName] = ",
              "\"خروجی\"",
              "",
              "",
              "      )))",
              "-",
              "  ( CALCULATE(sum('VN Fact_int_Vocher_Itm_Qty'[SalePrice]),",
              "                         FILTER('VN Fact_int_Vocher_Itm_Qty', 'VN Fact_int_Vocher_Itm_Qty'[VocherTypeName] = ",
              "\"برگشت حواله\"",
              ")))"
            ],
            "formatString": "#,#"
          }
        ]
      },
      {
        "name": "BI last_refresh_time_knime",
        "description": "جدول نشان دهنده آخرین تاریخ و زمان رفرش",
        "columns": [
          {
            "name": "Time",
            "dataType": "string",
            "description": "زمان آخرین رفرش گزارشات",
            "sourceColumn": "Time"
          },
          {
            "name": "Date",
            "dataType": "string",
            "description": "تاریخ آخرین رفرش گزارشات",
            "sourceColumn": "Date"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    BI_last_refresh_time_knime = Source{[Schema=\"BI\",Item=\"last_refresh_time_knime\"]}[Data]",
                "in",
                "    BI_last_refresh_time_knime"
              ]
            }
          }
        ]
      },
      {
        "name": "VN Fact_int_Vocher_Itm_Qty_history",
        "description": "جدول سوابق روزانه موجودی هر کالا در هر انبار براساس داده های سندهای رسید انبار",
        "columns": [
          {
            "name": "StockDCRef",
            "dataType": "int64",
            "description": "کد انبار",
            "sourceColumn": "StockDCRef"
          },
          {
            "name": "GoodsRef",
            "dataType": "int64",
            "description": "id کالا",
            "sourceColumn": "GoodsRef"
          },
          {
            "name": "Sum(TotalQty)",
            "dataType": "double",
            "description": "تعداد موجودی انبار در هر روز در هر انبار",
            "sourceColumn": "Sum(TotalQty)",
            "formatString": "0"
          },
          {
            "name": "VocherDate",
            "dataType": "string",
            "description": "تاریخ",
            "sourceColumn": "VocherDate"
          },
          {
            "name": "SalePrice",
            "dataType": "int64",
            "description": "قیمت هر روز یک کالا در بک انبار",
            "sourceColumn": "SalePrice",
            "formatString": "#,#"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 1 28;ARVA_BI\",",
                "    VN_Fact_int_Vocher_Itm_Qty_history = Source{[Schema=\"VN\",Item=\"Fact_int_Vocher_Itm_Qty_history\"]}[Data]",
                "in",
                "    VN_Fact_int_Vocher_Itm_Qty_history"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "01_product_in_stock_in_last_day",
            "description": "موجودی پایان دوره",
            "expression": [
              " ",
              "     CALCULATE(SUM('VN Fact_int_Vocher_Itm_Qty_history'[Sum(TotalQty)]) , FILTER('BI DIM_DATE','BI DIM_DATE'[end_month] =1)",
              ")"
            ],
            "formatString": "#,#"
          },
          {
            "name": "02_ product_in_stock_in_frist_day",
            "description": "موجودی ابتدای دوره",
            "expression": [
              "",
              "     CALCULATE(SUM('VN Fact_int_Vocher_Itm_Qty_history'[Sum(TotalQty)]) , FILTER('BI DIM_DATE','BI DIM_DATE'[end_month] =2)",
              ")"
            ],
            "formatString": "#,#"
          },
          {
            "name": "04_ average invetory",
            "description": "میانگین موجودی انبار ( ابتدا و انتهای دوره )",
            "expression": "( 'VN Fact_int_Vocher_Itm_Qty_history'[01_product_in_stock_in_last_day] + 'VN Fact_int_Vocher_Itm_Qty_history'[02_ product_in_stock_in_frist_day] )/2",
            "formatString": "#,#"
          },
          {
            "name": "05_real ITR",
            "description": "محاسبه ITR ",
            "expression": [
              "  if (MAX('VN Dim_Stock'[StockDC_ID]) <> 2, ",
              "    DIVIDE('VN Fact_int_Vocher_Itm_Qty'[02_NumberSold],'VN Fact_int_Vocher_Itm_Qty_history'[04_ average invetory]),",
              "            DIVIDE(CALCULATE(sum('VN Fact_int_Vocher_Itm_Qty'[TotalQty]),FILTER('VN Fact_int_Vocher_Itm_Qty', 'VN Fact_int_Vocher_Itm_Qty'[VocherTypeName] =",
              "\"انبار به انبار بستانكار\"))",
              " , [04_ average invetory]))",
              "",
              "",
              "",
              ""
            ]
          },
          {
            "name": "07_Current inventory",
            "description": "موجودی ریالی لحظه ای انبار",
            "expression": " sum('VN Fact_int_Vocher_Itm_Qty_history'[Sum(TotalQty)]) *  sum('VN Fact_int_Vocher_Itm_Qty_history'[SalePrice])"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "6baeca40-a82c-4403-998d-6b541a21619d",
        "fromTable": "VN Fact_int_Vocher_Itm_Qty",
        "fromColumn": "GoodsRef",
        "toTable": "VN Dim_Goods",
        "toColumn": "Goods_ID"
      },
      {
        "name": "f5fe40bb-4ce0-429b-8d9f-43893bcd0560",
        "fromTable": "VN Fact_int_Vocher_Itm_Qty",
        "fromColumn": "StockDCRef",
        "toTable": "VN Dim_Stock",
        "toColumn": "StockDC_ID"
      },
      {
        "name": "5b25d755-6830-4be1-a22b-4080b33a81bd",
        "fromTable": "VN Fact_int_Vocher_Itm_Qty",
        "fromColumn": "VocherDate",
        "toTable": "BI DIM_DATE",
        "toColumn": "Jalali_1"
      },
      {
        "name": "aa61cb7c-9de1-4f84-94f5-59c190f3872c",
        "fromTable": "BI last_refresh_time_knime",
        "fromColumn": "Date",
        "toTable": "BI DIM_DATE",
        "toColumn": "Jalali_1"
      },
      {
        "name": "0789e9d5-972c-490b-a637-0e5e032db74b",
        "fromTable": "VN Fact_int_Vocher_Itm_Qty_history",
        "fromColumn": "StockDCRef",
        "toTable": "VN Dim_Stock",
        "toColumn": "StockDC_ID"
      },
      {
        "name": "4b70da09-6fcc-477d-9596-c79b15c23ed0",
        "fromTable": "VN Fact_int_Vocher_Itm_Qty_history",
        "fromColumn": "VocherDate",
        "toTable": "BI DIM_DATE",
        "toColumn": "Jalali_1"
      },
      {
        "name": "767ab058-c049-419c-a7c0-67e6fb310c2e",
        "fromTable": "VN Fact_int_Vocher_Itm_Qty_history",
        "fromColumn": "GoodsRef",
        "toTable": "VN Dim_Goods",
        "toColumn": "Goods_ID"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "600"
      }
    ]
  },
  "id": "SemanticModel"
}